// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alameda_api/v1alpha1/datahub/predict.proto

package containers_ai_alameda_v1alpha1_datahub

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RecommendationPolicy int32

const (
	RecommendationPolicy_RECOMMENDATIONPOLICY_UNDEFINED RecommendationPolicy = 0
	RecommendationPolicy_STABLE                         RecommendationPolicy = 1
	RecommendationPolicy_COMPACT                        RecommendationPolicy = 2
)

var RecommendationPolicy_name = map[int32]string{
	0: "RECOMMENDATIONPOLICY_UNDEFINED",
	1: "STABLE",
	2: "COMPACT",
}
var RecommendationPolicy_value = map[string]int32{
	"RECOMMENDATIONPOLICY_UNDEFINED": 0,
	"STABLE":                         1,
	"COMPACT":                        2,
}

func (x RecommendationPolicy) String() string {
	return proto.EnumName(RecommendationPolicy_name, int32(x))
}
func (RecommendationPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_predict_8049160bb7a2fbcd, []int{0}
}

type TimeSeriesData struct {
	DataPoint            []*Sample `protobuf:"bytes,1,rep,name=data_point,json=dataPoint,proto3" json:"data_point,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TimeSeriesData) Reset()         { *m = TimeSeriesData{} }
func (m *TimeSeriesData) String() string { return proto.CompactTextString(m) }
func (*TimeSeriesData) ProtoMessage()    {}
func (*TimeSeriesData) Descriptor() ([]byte, []int) {
	return fileDescriptor_predict_8049160bb7a2fbcd, []int{0}
}
func (m *TimeSeriesData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeSeriesData.Unmarshal(m, b)
}
func (m *TimeSeriesData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeSeriesData.Marshal(b, m, deterministic)
}
func (dst *TimeSeriesData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeSeriesData.Merge(dst, src)
}
func (m *TimeSeriesData) XXX_Size() int {
	return xxx_messageInfo_TimeSeriesData.Size(m)
}
func (m *TimeSeriesData) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeSeriesData.DiscardUnknown(m)
}

var xxx_messageInfo_TimeSeriesData proto.InternalMessageInfo

func (m *TimeSeriesData) GetDataPoint() []*Sample {
	if m != nil {
		return m.DataPoint
	}
	return nil
}

type PredictContainer struct {
	Name                          string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RowPredictData                []*MetricData `protobuf:"bytes,2,rep,name=row_predict_data,json=rowPredictData,proto3" json:"row_predict_data,omitempty"`
	LimitPredictData              []*MetricData `protobuf:"bytes,3,rep,name=limit_predict_data,json=limitPredictData,proto3" json:"limit_predict_data,omitempty"`
	RequestPredictData            []*MetricData `protobuf:"bytes,4,rep,name=request_predict_data,json=requestPredictData,proto3" json:"request_predict_data,omitempty"`
	InitialLimitPredictResource   []*MetricData `protobuf:"bytes,5,rep,name=initial_limit_predict_resource,json=initialLimitPredictResource,proto3" json:"initial_limit_predict_resource,omitempty"`
	InitialRequestPredictResource []*MetricData `protobuf:"bytes,6,rep,name=initial_request_predict_resource,json=initialRequestPredictResource,proto3" json:"initial_request_predict_resource,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}      `json:"-"`
	XXX_unrecognized              []byte        `json:"-"`
	XXX_sizecache                 int32         `json:"-"`
}

func (m *PredictContainer) Reset()         { *m = PredictContainer{} }
func (m *PredictContainer) String() string { return proto.CompactTextString(m) }
func (*PredictContainer) ProtoMessage()    {}
func (*PredictContainer) Descriptor() ([]byte, []int) {
	return fileDescriptor_predict_8049160bb7a2fbcd, []int{1}
}
func (m *PredictContainer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictContainer.Unmarshal(m, b)
}
func (m *PredictContainer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictContainer.Marshal(b, m, deterministic)
}
func (dst *PredictContainer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictContainer.Merge(dst, src)
}
func (m *PredictContainer) XXX_Size() int {
	return xxx_messageInfo_PredictContainer.Size(m)
}
func (m *PredictContainer) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictContainer.DiscardUnknown(m)
}

var xxx_messageInfo_PredictContainer proto.InternalMessageInfo

func (m *PredictContainer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PredictContainer) GetRowPredictData() []*MetricData {
	if m != nil {
		return m.RowPredictData
	}
	return nil
}

func (m *PredictContainer) GetLimitPredictData() []*MetricData {
	if m != nil {
		return m.LimitPredictData
	}
	return nil
}

func (m *PredictContainer) GetRequestPredictData() []*MetricData {
	if m != nil {
		return m.RequestPredictData
	}
	return nil
}

func (m *PredictContainer) GetInitialLimitPredictResource() []*MetricData {
	if m != nil {
		return m.InitialLimitPredictResource
	}
	return nil
}

func (m *PredictContainer) GetInitialRequestPredictResource() []*MetricData {
	if m != nil {
		return m.InitialRequestPredictResource
	}
	return nil
}

type PredictPod struct {
	Uid                  string              `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Namespace            string              `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string              `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PredictContainers    []*PredictContainer `protobuf:"bytes,4,rep,name=predict_containers,json=predictContainers,proto3" json:"predict_containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PredictPod) Reset()         { *m = PredictPod{} }
func (m *PredictPod) String() string { return proto.CompactTextString(m) }
func (*PredictPod) ProtoMessage()    {}
func (*PredictPod) Descriptor() ([]byte, []int) {
	return fileDescriptor_predict_8049160bb7a2fbcd, []int{2}
}
func (m *PredictPod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictPod.Unmarshal(m, b)
}
func (m *PredictPod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictPod.Marshal(b, m, deterministic)
}
func (dst *PredictPod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictPod.Merge(dst, src)
}
func (m *PredictPod) XXX_Size() int {
	return xxx_messageInfo_PredictPod.Size(m)
}
func (m *PredictPod) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictPod.DiscardUnknown(m)
}

var xxx_messageInfo_PredictPod proto.InternalMessageInfo

func (m *PredictPod) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PredictPod) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PredictPod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PredictPod) GetPredictContainers() []*PredictContainer {
	if m != nil {
		return m.PredictContainers
	}
	return nil
}

type PredictNode struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RowPredictData       []*MetricData `protobuf:"bytes,2,rep,name=row_predict_data,json=rowPredictData,proto3" json:"row_predict_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PredictNode) Reset()         { *m = PredictNode{} }
func (m *PredictNode) String() string { return proto.CompactTextString(m) }
func (*PredictNode) ProtoMessage()    {}
func (*PredictNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_predict_8049160bb7a2fbcd, []int{3}
}
func (m *PredictNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictNode.Unmarshal(m, b)
}
func (m *PredictNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictNode.Marshal(b, m, deterministic)
}
func (dst *PredictNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictNode.Merge(dst, src)
}
func (m *PredictNode) XXX_Size() int {
	return xxx_messageInfo_PredictNode.Size(m)
}
func (m *PredictNode) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictNode.DiscardUnknown(m)
}

var xxx_messageInfo_PredictNode proto.InternalMessageInfo

func (m *PredictNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PredictNode) GetRowPredictData() []*MetricData {
	if m != nil {
		return m.RowPredictData
	}
	return nil
}

type MetricData struct {
	MetricType MetricType `protobuf:"varint,1,opt,name=metric_type,json=metricType,proto3,enum=containers_ai.alameda.v1alpha1.datahub.MetricType" json:"metric_type,omitempty"`
	// Types that are valid to be assigned to PredictData:
	//	*MetricData_TimeSeriesData
	//	*MetricData_Value
	PredictData          isMetricData_PredictData `protobuf_oneof:"predict_data"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MetricData) Reset()         { *m = MetricData{} }
func (m *MetricData) String() string { return proto.CompactTextString(m) }
func (*MetricData) ProtoMessage()    {}
func (*MetricData) Descriptor() ([]byte, []int) {
	return fileDescriptor_predict_8049160bb7a2fbcd, []int{4}
}
func (m *MetricData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricData.Unmarshal(m, b)
}
func (m *MetricData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricData.Marshal(b, m, deterministic)
}
func (dst *MetricData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricData.Merge(dst, src)
}
func (m *MetricData) XXX_Size() int {
	return xxx_messageInfo_MetricData.Size(m)
}
func (m *MetricData) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricData.DiscardUnknown(m)
}

var xxx_messageInfo_MetricData proto.InternalMessageInfo

func (m *MetricData) GetMetricType() MetricType {
	if m != nil {
		return m.MetricType
	}
	return MetricType_METRICTYPE_UNDEFINED
}

type isMetricData_PredictData interface {
	isMetricData_PredictData()
}

type MetricData_TimeSeriesData struct {
	TimeSeriesData *TimeSeriesData `protobuf:"bytes,2,opt,name=time_series_data,json=timeSeriesData,proto3,oneof"`
}

type MetricData_Value struct {
	Value string `protobuf:"bytes,3,opt,name=value,proto3,oneof"`
}

func (*MetricData_TimeSeriesData) isMetricData_PredictData() {}

func (*MetricData_Value) isMetricData_PredictData() {}

func (m *MetricData) GetPredictData() isMetricData_PredictData {
	if m != nil {
		return m.PredictData
	}
	return nil
}

func (m *MetricData) GetTimeSeriesData() *TimeSeriesData {
	if x, ok := m.GetPredictData().(*MetricData_TimeSeriesData); ok {
		return x.TimeSeriesData
	}
	return nil
}

func (m *MetricData) GetValue() string {
	if x, ok := m.GetPredictData().(*MetricData_Value); ok {
		return x.Value
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MetricData) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MetricData_OneofMarshaler, _MetricData_OneofUnmarshaler, _MetricData_OneofSizer, []interface{}{
		(*MetricData_TimeSeriesData)(nil),
		(*MetricData_Value)(nil),
	}
}

func _MetricData_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MetricData)
	// predict_data
	switch x := m.PredictData.(type) {
	case *MetricData_TimeSeriesData:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TimeSeriesData); err != nil {
			return err
		}
	case *MetricData_Value:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Value)
	case nil:
	default:
		return fmt.Errorf("MetricData.PredictData has unexpected type %T", x)
	}
	return nil
}

func _MetricData_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MetricData)
	switch tag {
	case 2: // predict_data.time_series_data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TimeSeriesData)
		err := b.DecodeMessage(msg)
		m.PredictData = &MetricData_TimeSeriesData{msg}
		return true, err
	case 3: // predict_data.value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.PredictData = &MetricData_Value{x}
		return true, err
	default:
		return false, nil
	}
}

func _MetricData_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MetricData)
	// predict_data
	switch x := m.PredictData.(type) {
	case *MetricData_TimeSeriesData:
		s := proto.Size(x.TimeSeriesData)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MetricData_Value:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Value)))
		n += len(x.Value)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*TimeSeriesData)(nil), "containers_ai.alameda.v1alpha1.datahub.TimeSeriesData")
	proto.RegisterType((*PredictContainer)(nil), "containers_ai.alameda.v1alpha1.datahub.PredictContainer")
	proto.RegisterType((*PredictPod)(nil), "containers_ai.alameda.v1alpha1.datahub.PredictPod")
	proto.RegisterType((*PredictNode)(nil), "containers_ai.alameda.v1alpha1.datahub.PredictNode")
	proto.RegisterType((*MetricData)(nil), "containers_ai.alameda.v1alpha1.datahub.MetricData")
	proto.RegisterEnum("containers_ai.alameda.v1alpha1.datahub.RecommendationPolicy", RecommendationPolicy_name, RecommendationPolicy_value)
}

func init() {
	proto.RegisterFile("alameda_api/v1alpha1/datahub/predict.proto", fileDescriptor_predict_8049160bb7a2fbcd)
}

var fileDescriptor_predict_8049160bb7a2fbcd = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0x4d, 0x8b, 0x1a, 0x31,
	0x18, 0xc7, 0x1d, 0x75, 0x2d, 0x3e, 0x16, 0x99, 0x86, 0xa5, 0x48, 0x5f, 0x16, 0x99, 0x43, 0xb1,
	0x7b, 0x18, 0x59, 0x0b, 0xa5, 0x57, 0x57, 0x2d, 0x2b, 0xf8, 0x32, 0x44, 0x7b, 0x28, 0x14, 0xa6,
	0x71, 0x26, 0x74, 0x03, 0x93, 0x49, 0x9a, 0x89, 0x2b, 0xd2, 0x43, 0x3f, 0x57, 0xaf, 0xfd, 0x3e,
	0xfd, 0x0e, 0x65, 0xc6, 0x8c, 0x6f, 0x87, 0x62, 0x3d, 0xec, 0x2d, 0xf3, 0x98, 0xfc, 0x7e, 0xf9,
	0x9b, 0x87, 0x07, 0xae, 0x49, 0x44, 0x38, 0x0d, 0x89, 0x4f, 0x24, 0x6b, 0x3f, 0xdc, 0x90, 0x48,
	0xde, 0x93, 0x9b, 0x76, 0x48, 0x34, 0xb9, 0x5f, 0x2e, 0xda, 0x52, 0xd1, 0x90, 0x05, 0xda, 0x95,
	0x4a, 0x68, 0x81, 0xde, 0x04, 0x22, 0xd6, 0x84, 0xc5, 0x54, 0x25, 0x3e, 0x61, 0xae, 0x39, 0xe9,
	0xe6, 0xa7, 0x5c, 0x73, 0xea, 0xc5, 0xdb, 0x7f, 0x32, 0x39, 0xd5, 0x8a, 0x05, 0x1b, 0xa4, 0xe3,
	0x43, 0x7d, 0xce, 0x38, 0x9d, 0x51, 0xc5, 0x68, 0xd2, 0x27, 0x9a, 0xa0, 0x31, 0x40, 0xba, 0xd3,
	0x97, 0x82, 0xc5, 0xba, 0x61, 0x35, 0x4b, 0xad, 0x5a, 0xc7, 0x75, 0x4f, 0x33, 0xbb, 0x33, 0xc2,
	0x65, 0x44, 0x71, 0x35, 0xfd, 0xf6, 0x52, 0x80, 0xf3, 0xbb, 0x0c, 0xb6, 0xb7, 0x49, 0xd1, 0xcb,
	0x19, 0x08, 0x41, 0x39, 0x26, 0x9c, 0x36, 0xac, 0xa6, 0xd5, 0xaa, 0xe2, 0x6c, 0x8d, 0xbe, 0x80,
	0xad, 0xc4, 0xca, 0x37, 0x89, 0xfd, 0x94, 0xd0, 0x28, 0x66, 0xf6, 0xce, 0xa9, 0xf6, 0x71, 0x96,
	0x2c, 0x4d, 0x81, 0xeb, 0x4a, 0xac, 0x8c, 0x36, 0x4b, 0xf5, 0x15, 0x50, 0xc4, 0x38, 0xd3, 0x87,
	0xfc, 0xd2, 0xd9, 0x7c, 0x3b, 0xa3, 0xed, 0x1b, 0x42, 0xb8, 0x54, 0xf4, 0xfb, 0x92, 0x26, 0x47,
	0x8e, 0xf2, 0xd9, 0x0e, 0x64, 0x78, 0xfb, 0x96, 0x15, 0x5c, 0xb1, 0x98, 0x69, 0x46, 0x22, 0xff,
	0x30, 0x8f, 0xa2, 0x89, 0x58, 0xaa, 0x80, 0x36, 0x2e, 0xce, 0xf6, 0xbd, 0x34, 0xe4, 0xd1, 0x5e,
	0x34, 0x6c, 0xb0, 0xe8, 0x07, 0x34, 0x73, 0xf1, 0x71, 0xcc, 0xad, 0xba, 0x72, 0xb6, 0xfa, 0xb5,
	0x61, 0xe3, 0x83, 0xc4, 0xb9, 0xdc, 0xf9, 0x65, 0x01, 0x98, 0x9a, 0x27, 0x42, 0x64, 0x43, 0x69,
	0xc9, 0x42, 0xd3, 0x3d, 0xe9, 0x12, 0xbd, 0x82, 0x6a, 0xda, 0x44, 0x89, 0x24, 0x01, 0x6d, 0x14,
	0xb3, 0xfa, 0xae, 0xb0, 0x6d, 0xb7, 0xd2, 0x5e, 0xbb, 0x7d, 0x03, 0x94, 0xdf, 0x7f, 0x77, 0x5d,
	0xf3, 0x58, 0x1f, 0x4e, 0x4d, 0x70, 0xdc, 0xd8, 0xf8, 0x99, 0x3c, 0xaa, 0x24, 0xce, 0x4f, 0xa8,
	0x99, 0x6d, 0x13, 0x11, 0xd2, 0xc7, 0x6f, 0x7d, 0xe7, 0x8f, 0x05, 0xb0, 0xfb, 0x19, 0xcd, 0xa0,
	0xb6, 0x99, 0x00, 0xbe, 0x5e, 0xcb, 0xcd, 0x3d, 0xea, 0xff, 0xeb, 0x99, 0xaf, 0x25, 0xc5, 0xc0,
	0xb7, 0x6b, 0xb4, 0x00, 0x5b, 0x33, 0x4e, 0xfd, 0x24, 0x9b, 0x23, 0x79, 0x02, 0xab, 0x55, 0xeb,
	0xbc, 0x3f, 0x95, 0x7c, 0x38, 0x86, 0xee, 0x0a, 0xb8, 0xae, 0x0f, 0x07, 0xd3, 0x73, 0xb8, 0x78,
	0x20, 0xd1, 0xd2, 0x3c, 0xe3, 0x5d, 0x01, 0x6f, 0x3e, 0x6f, 0xeb, 0xf0, 0x74, 0xff, 0x9f, 0xbb,
	0x9e, 0xc1, 0x25, 0xa6, 0x81, 0xe0, 0x9c, 0xc6, 0x21, 0xd1, 0x4c, 0xc4, 0x9e, 0x88, 0x58, 0xb0,
	0x46, 0x0e, 0x5c, 0xe1, 0x41, 0x6f, 0x3a, 0x1e, 0x0f, 0x26, 0xfd, 0xee, 0x7c, 0x38, 0x9d, 0x78,
	0xd3, 0xd1, 0xb0, 0xf7, 0xd9, 0xff, 0x34, 0xe9, 0x0f, 0x3e, 0x0e, 0x27, 0x83, 0xbe, 0x5d, 0x40,
	0x00, 0x95, 0xd9, 0xbc, 0x7b, 0x3b, 0x1a, 0xd8, 0x16, 0xaa, 0xc1, 0x93, 0xde, 0x74, 0xec, 0x75,
	0x7b, 0x73, 0xbb, 0xb8, 0xa8, 0x64, 0xe3, 0xf2, 0xdd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd1,
	0xd8, 0xe1, 0x27, 0xaf, 0x05, 0x00, 0x00,
}
