// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alameda_api/v1alpha1/datahub/resource.proto

package containers_ai_alameda_v1alpha1_datahub

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Container struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LimitResource        []*MetricData `protobuf:"bytes,2,rep,name=limit_resource,json=limitResource,proto3" json:"limit_resource,omitempty"`
	RequestResource      []*MetricData `protobuf:"bytes,3,rep,name=request_resource,json=requestResource,proto3" json:"request_resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_0a8d67315dc06ce7, []int{0}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (dst *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(dst, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Container) GetLimitResource() []*MetricData {
	if m != nil {
		return m.LimitResource
	}
	return nil
}

func (m *Container) GetRequestResource() []*MetricData {
	if m != nil {
		return m.RequestResource
	}
	return nil
}

type AlamedaPod struct {
	Namespace            string       `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ResourceLink         string       `protobuf:"bytes,3,opt,name=resource_link,json=resourceLink,proto3" json:"resource_link,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AlamedaPod) Reset()         { *m = AlamedaPod{} }
func (m *AlamedaPod) String() string { return proto.CompactTextString(m) }
func (*AlamedaPod) ProtoMessage()    {}
func (*AlamedaPod) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_0a8d67315dc06ce7, []int{1}
}
func (m *AlamedaPod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlamedaPod.Unmarshal(m, b)
}
func (m *AlamedaPod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlamedaPod.Marshal(b, m, deterministic)
}
func (dst *AlamedaPod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlamedaPod.Merge(dst, src)
}
func (m *AlamedaPod) XXX_Size() int {
	return xxx_messageInfo_AlamedaPod.Size(m)
}
func (m *AlamedaPod) XXX_DiscardUnknown() {
	xxx_messageInfo_AlamedaPod.DiscardUnknown(m)
}

var xxx_messageInfo_AlamedaPod proto.InternalMessageInfo

func (m *AlamedaPod) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *AlamedaPod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AlamedaPod) GetResourceLink() string {
	if m != nil {
		return m.ResourceLink
	}
	return ""
}

func (m *AlamedaPod) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type AlamedaNode struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlamedaNode) Reset()         { *m = AlamedaNode{} }
func (m *AlamedaNode) String() string { return proto.CompactTextString(m) }
func (*AlamedaNode) ProtoMessage()    {}
func (*AlamedaNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_0a8d67315dc06ce7, []int{2}
}
func (m *AlamedaNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlamedaNode.Unmarshal(m, b)
}
func (m *AlamedaNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlamedaNode.Marshal(b, m, deterministic)
}
func (dst *AlamedaNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlamedaNode.Merge(dst, src)
}
func (m *AlamedaNode) XXX_Size() int {
	return xxx_messageInfo_AlamedaNode.Size(m)
}
func (m *AlamedaNode) XXX_DiscardUnknown() {
	xxx_messageInfo_AlamedaNode.DiscardUnknown(m)
}

var xxx_messageInfo_AlamedaNode proto.InternalMessageInfo

func (m *AlamedaNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Container)(nil), "containers_ai.alameda.v1alpha1.datahub.Container")
	proto.RegisterType((*AlamedaPod)(nil), "containers_ai.alameda.v1alpha1.datahub.AlamedaPod")
	proto.RegisterType((*AlamedaNode)(nil), "containers_ai.alameda.v1alpha1.datahub.AlamedaNode")
}

func init() {
	proto.RegisterFile("alameda_api/v1alpha1/datahub/resource.proto", fileDescriptor_resource_0a8d67315dc06ce7)
}

var fileDescriptor_resource_0a8d67315dc06ce7 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x53, 0x84, 0x4c, 0xad, 0xca, 0x9e, 0x82, 0x78, 0xa8, 0x11, 0xa4, 0x28, 0x6c,
	0x48, 0x7d, 0x02, 0xd1, 0xa3, 0x8a, 0xe6, 0xe6, 0x41, 0xc2, 0x34, 0x19, 0xe8, 0xd2, 0x24, 0xbb,
	0x6e, 0x36, 0x3e, 0x9a, 0xef, 0xe2, 0xdb, 0x88, 0xdb, 0xdd, 0x36, 0x07, 0x91, 0xe2, 0x6d, 0x99,
	0xe5, 0xff, 0xf8, 0xfe, 0x19, 0xb8, 0xc6, 0x1a, 0x1b, 0xaa, 0xb0, 0x40, 0x25, 0xd2, 0x8f, 0x0c,
	0x6b, 0xb5, 0xc2, 0x2c, 0xad, 0xd0, 0xe0, 0xaa, 0x5f, 0xa6, 0x9a, 0x3a, 0xd9, 0xeb, 0x92, 0xb8,
	0xd2, 0xd2, 0x48, 0x76, 0x59, 0xca, 0xd6, 0xa0, 0x68, 0x49, 0x77, 0x05, 0x0a, 0xee, 0xa2, 0xdc,
	0xc7, 0xb8, 0x8b, 0x9d, 0x5e, 0xfd, 0x09, 0x55, 0x9a, 0x2a, 0x51, 0x9a, 0x0d, 0x33, 0xf9, 0x0a,
	0x20, 0xba, 0xf3, 0x58, 0xc6, 0x60, 0xdc, 0x62, 0x43, 0x71, 0x30, 0x0b, 0xe6, 0x51, 0x6e, 0xdf,
	0xec, 0x15, 0x8e, 0x6a, 0xd1, 0x08, 0x53, 0x78, 0x9b, 0x78, 0x34, 0x0b, 0xe7, 0x93, 0xc5, 0x82,
	0xef, 0xa7, 0xc3, 0x1f, 0xc9, 0x68, 0x51, 0xde, 0xa3, 0xc1, 0x7c, 0x6a, 0x49, 0xb9, 0x03, 0xb1,
	0x37, 0x38, 0xd1, 0xf4, 0xde, 0x53, 0x37, 0x80, 0x87, 0xff, 0x86, 0x1f, 0x3b, 0x96, 0xc7, 0x27,
	0x9f, 0x01, 0xc0, 0xed, 0x26, 0xf8, 0x2c, 0x2b, 0x76, 0x06, 0xd1, 0x4f, 0xa1, 0x4e, 0x61, 0xe9,
	0x1b, 0xee, 0x06, 0xdb, 0xea, 0xa3, 0x41, 0xf5, 0x0b, 0x98, 0x7a, 0xaf, 0xa2, 0x16, 0xed, 0x3a,
	0x0e, 0xed, 0xe7, 0xa1, 0x1f, 0x3e, 0x88, 0x76, 0xcd, 0x5e, 0x00, 0x76, 0xae, 0xf1, 0xd8, 0xea,
	0x67, 0xfb, 0xea, 0x6f, 0x57, 0x9f, 0x0f, 0x20, 0xc9, 0x39, 0x4c, 0x9c, 0xf7, 0x93, 0xac, 0xe8,
	0xb7, 0xab, 0x2c, 0x0f, 0xec, 0xf9, 0x6e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x7c, 0x19,
	0x79, 0x41, 0x02, 0x00, 0x00,
}
