// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alameda_api/v1alpha1/datahub/resource.proto

package containers_ai_alameda_v1alpha1_datahub

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Represents kubernetes resource kind
//
type Kind int32

const (
	Kind_POD              Kind = 0
	Kind_DEPLOYMENT       Kind = 1
	Kind_DEPLOYMENTCONFIG Kind = 2
	Kind_ALAMEDASCALER    Kind = 3
)

var Kind_name = map[int32]string{
	0: "POD",
	1: "DEPLOYMENT",
	2: "DEPLOYMENTCONFIG",
	3: "ALAMEDASCALER",
}
var Kind_value = map[string]int32{
	"POD":              0,
	"DEPLOYMENT":       1,
	"DEPLOYMENTCONFIG": 2,
	"ALAMEDASCALER":    3,
}

func (x Kind) String() string {
	return proto.EnumName(Kind_name, int32(x))
}
func (Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_resource_1d3ac57a7d6ddef7, []int{0}
}

// *
// Represents kubernetes pod status (lifecycle)
//
type PodStatus int32

const (
	PodStatus_Pending          PodStatus = 0
	PodStatus_Running          PodStatus = 1
	PodStatus_Succeeded        PodStatus = 2
	PodStatus_Failed           PodStatus = 3
	PodStatus_Unknown          PodStatus = 4
	PodStatus_Completed        PodStatus = 5
	PodStatus_CrashLoopBackOff PodStatus = 6
)

var PodStatus_name = map[int32]string{
	0: "Pending",
	1: "Running",
	2: "Succeeded",
	3: "Failed",
	4: "Unknown",
	5: "Completed",
	6: "CrashLoopBackOff",
}
var PodStatus_value = map[string]int32{
	"Pending":          0,
	"Running":          1,
	"Succeeded":        2,
	"Failed":           3,
	"Unknown":          4,
	"Completed":        5,
	"CrashLoopBackOff": 6,
}

func (x PodStatus) String() string {
	return proto.EnumName(PodStatus_name, int32(x))
}
func (PodStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_resource_1d3ac57a7d6ddef7, []int{1}
}

// *
// Represents a container and its containing limit and requeset configurations
//
type Container struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LimitResource        []*MetricData `protobuf:"bytes,2,rep,name=limit_resource,json=limitResource,proto3" json:"limit_resource,omitempty"`
	RequestResource      []*MetricData `protobuf:"bytes,3,rep,name=request_resource,json=requestResource,proto3" json:"request_resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_1d3ac57a7d6ddef7, []int{0}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (dst *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(dst, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Container) GetLimitResource() []*MetricData {
	if m != nil {
		return m.LimitResource
	}
	return nil
}

func (m *Container) GetRequestResource() []*MetricData {
	if m != nil {
		return m.RequestResource
	}
	return nil
}

// *
// Represents a Kubernetes pod
//
type Pod struct {
	NamespacedName       *NamespacedName      `protobuf:"bytes,1,opt,name=namespaced_name,json=namespacedName,proto3" json:"namespaced_name,omitempty"`
	ResourceLink         string               `protobuf:"bytes,2,opt,name=resource_link,json=resourceLink,proto3" json:"resource_link,omitempty"`
	Containers           []*Container         `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	IsAlameda            bool                 `protobuf:"varint,4,opt,name=is_alameda,json=isAlameda,proto3" json:"is_alameda,omitempty"`
	AlamedaScaler        *NamespacedName      `protobuf:"bytes,5,opt,name=alameda_scaler,json=alamedaScaler,proto3" json:"alameda_scaler,omitempty"`
	NodeName             string               `protobuf:"bytes,6,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Policy               RecommendationPolicy `protobuf:"varint,8,opt,name=policy,proto3,enum=containers_ai.alameda.v1alpha1.datahub.RecommendationPolicy" json:"policy,omitempty"`
	TopController        *TopController       `protobuf:"bytes,9,opt,name=top_controller,json=topController,proto3" json:"top_controller,omitempty"`
	UsedRecommendationId string               `protobuf:"bytes,10,opt,name=used_recommendation_id,json=usedRecommendationId,proto3" json:"used_recommendation_id,omitempty"`
	Status               PodStatus            `protobuf:"varint,11,opt,name=status,proto3,enum=containers_ai.alameda.v1alpha1.datahub.PodStatus" json:"status,omitempty"`
	Reason               string               `protobuf:"bytes,12,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Pod) Reset()         { *m = Pod{} }
func (m *Pod) String() string { return proto.CompactTextString(m) }
func (*Pod) ProtoMessage()    {}
func (*Pod) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_1d3ac57a7d6ddef7, []int{1}
}
func (m *Pod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pod.Unmarshal(m, b)
}
func (m *Pod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pod.Marshal(b, m, deterministic)
}
func (dst *Pod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pod.Merge(dst, src)
}
func (m *Pod) XXX_Size() int {
	return xxx_messageInfo_Pod.Size(m)
}
func (m *Pod) XXX_DiscardUnknown() {
	xxx_messageInfo_Pod.DiscardUnknown(m)
}

var xxx_messageInfo_Pod proto.InternalMessageInfo

func (m *Pod) GetNamespacedName() *NamespacedName {
	if m != nil {
		return m.NamespacedName
	}
	return nil
}

func (m *Pod) GetResourceLink() string {
	if m != nil {
		return m.ResourceLink
	}
	return ""
}

func (m *Pod) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Pod) GetIsAlameda() bool {
	if m != nil {
		return m.IsAlameda
	}
	return false
}

func (m *Pod) GetAlamedaScaler() *NamespacedName {
	if m != nil {
		return m.AlamedaScaler
	}
	return nil
}

func (m *Pod) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *Pod) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Pod) GetPolicy() RecommendationPolicy {
	if m != nil {
		return m.Policy
	}
	return RecommendationPolicy_RECOMMENDATIONPOLICY_UNDEFINED
}

func (m *Pod) GetTopController() *TopController {
	if m != nil {
		return m.TopController
	}
	return nil
}

func (m *Pod) GetUsedRecommendationId() string {
	if m != nil {
		return m.UsedRecommendationId
	}
	return ""
}

func (m *Pod) GetStatus() PodStatus {
	if m != nil {
		return m.Status
	}
	return PodStatus_Pending
}

func (m *Pod) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// *
// Represents the capacity of a Kubernetes node
//
type Capacity struct {
	CpuCores                 int64    `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryBytes              int64    `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	NetwotkMegabitsPerSecond int64    `protobuf:"varint,3,opt,name=netwotk_megabits_per_second,json=netwotkMegabitsPerSecond,proto3" json:"netwotk_megabits_per_second,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *Capacity) Reset()         { *m = Capacity{} }
func (m *Capacity) String() string { return proto.CompactTextString(m) }
func (*Capacity) ProtoMessage()    {}
func (*Capacity) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_1d3ac57a7d6ddef7, []int{2}
}
func (m *Capacity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Capacity.Unmarshal(m, b)
}
func (m *Capacity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Capacity.Marshal(b, m, deterministic)
}
func (dst *Capacity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capacity.Merge(dst, src)
}
func (m *Capacity) XXX_Size() int {
	return xxx_messageInfo_Capacity.Size(m)
}
func (m *Capacity) XXX_DiscardUnknown() {
	xxx_messageInfo_Capacity.DiscardUnknown(m)
}

var xxx_messageInfo_Capacity proto.InternalMessageInfo

func (m *Capacity) GetCpuCores() int64 {
	if m != nil {
		return m.CpuCores
	}
	return 0
}

func (m *Capacity) GetMemoryBytes() int64 {
	if m != nil {
		return m.MemoryBytes
	}
	return 0
}

func (m *Capacity) GetNetwotkMegabitsPerSecond() int64 {
	if m != nil {
		return m.NetwotkMegabitsPerSecond
	}
	return 0
}

// *
// Represents a Kubernetes node
//
type Node struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Capacity             *Capacity            `protobuf:"bytes,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_1d3ac57a7d6ddef7, []int{3}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetCapacity() *Capacity {
	if m != nil {
		return m.Capacity
	}
	return nil
}

func (m *Node) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

// *
// Represents top controller of the pod
//
type TopController struct {
	NamespacedName       *NamespacedName `protobuf:"bytes,1,opt,name=namespaced_name,json=namespacedName,proto3" json:"namespaced_name,omitempty"`
	Kind                 Kind            `protobuf:"varint,2,opt,name=kind,proto3,enum=containers_ai.alameda.v1alpha1.datahub.Kind" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TopController) Reset()         { *m = TopController{} }
func (m *TopController) String() string { return proto.CompactTextString(m) }
func (*TopController) ProtoMessage()    {}
func (*TopController) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_1d3ac57a7d6ddef7, []int{4}
}
func (m *TopController) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopController.Unmarshal(m, b)
}
func (m *TopController) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopController.Marshal(b, m, deterministic)
}
func (dst *TopController) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopController.Merge(dst, src)
}
func (m *TopController) XXX_Size() int {
	return xxx_messageInfo_TopController.Size(m)
}
func (m *TopController) XXX_DiscardUnknown() {
	xxx_messageInfo_TopController.DiscardUnknown(m)
}

var xxx_messageInfo_TopController proto.InternalMessageInfo

func (m *TopController) GetNamespacedName() *NamespacedName {
	if m != nil {
		return m.NamespacedName
	}
	return nil
}

func (m *TopController) GetKind() Kind {
	if m != nil {
		return m.Kind
	}
	return Kind_POD
}

func init() {
	proto.RegisterType((*Container)(nil), "containers_ai.alameda.v1alpha1.datahub.Container")
	proto.RegisterType((*Pod)(nil), "containers_ai.alameda.v1alpha1.datahub.Pod")
	proto.RegisterType((*Capacity)(nil), "containers_ai.alameda.v1alpha1.datahub.Capacity")
	proto.RegisterType((*Node)(nil), "containers_ai.alameda.v1alpha1.datahub.Node")
	proto.RegisterType((*TopController)(nil), "containers_ai.alameda.v1alpha1.datahub.TopController")
	proto.RegisterEnum("containers_ai.alameda.v1alpha1.datahub.Kind", Kind_name, Kind_value)
	proto.RegisterEnum("containers_ai.alameda.v1alpha1.datahub.PodStatus", PodStatus_name, PodStatus_value)
}

func init() {
	proto.RegisterFile("alameda_api/v1alpha1/datahub/resource.proto", fileDescriptor_resource_1d3ac57a7d6ddef7)
}

var fileDescriptor_resource_1d3ac57a7d6ddef7 = []byte{
	// 804 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xdd, 0x6e, 0xe3, 0x44,
	0x18, 0x5d, 0xd7, 0xd9, 0x34, 0xf9, 0xd2, 0x64, 0xcd, 0x68, 0xb5, 0xb2, 0xba, 0x42, 0x94, 0x20,
	0xa1, 0x52, 0x50, 0x42, 0xc3, 0x8f, 0x84, 0x04, 0x12, 0xd9, 0xb4, 0x0b, 0x15, 0x69, 0x1b, 0x9c,
	0x72, 0xb1, 0x12, 0x2b, 0x6b, 0x32, 0xf3, 0xb5, 0x1d, 0xc5, 0x9e, 0x31, 0x33, 0x63, 0x56, 0xbd,
	0xe4, 0x92, 0xe7, 0xe0, 0x0d, 0x78, 0x1b, 0xde, 0x06, 0xcd, 0xc4, 0xce, 0xb6, 0x08, 0x95, 0x00,
	0xda, 0x3b, 0x9f, 0xf1, 0x39, 0xe7, 0xfb, 0x99, 0x63, 0xc3, 0x87, 0x34, 0xa3, 0x39, 0x72, 0x9a,
	0xd2, 0x42, 0x0c, 0x7f, 0x3e, 0xa4, 0x59, 0x71, 0x4d, 0x0f, 0x87, 0x9c, 0x5a, 0x7a, 0x5d, 0x2e,
	0x86, 0x1a, 0x8d, 0x2a, 0x35, 0xc3, 0x41, 0xa1, 0x95, 0x55, 0xe4, 0x7d, 0xa6, 0xa4, 0xa5, 0x42,
	0xa2, 0x36, 0x29, 0x15, 0x83, 0x4a, 0x3a, 0xa8, 0x65, 0x83, 0x4a, 0xb6, 0x7b, 0x70, 0xaf, 0x69,
	0xa1, 0x91, 0x0b, 0x66, 0x57, 0x9e, 0xbb, 0xef, 0x5c, 0x29, 0x75, 0x95, 0xe1, 0xd0, 0xa3, 0x45,
	0x79, 0x39, 0xb4, 0x22, 0x47, 0x63, 0x69, 0x5e, 0x54, 0x84, 0xfb, 0x3b, 0xcc, 0xd1, 0x52, 0xf7,
	0x5c, 0x91, 0x3f, 0xf8, 0x27, 0xb2, 0x16, 0x6c, 0x45, 0xed, 0xff, 0x11, 0x40, 0x7b, 0x52, 0xcf,
	0x43, 0x08, 0x34, 0x24, 0xcd, 0x31, 0x0e, 0xf6, 0x82, 0xfd, 0x76, 0xe2, 0x9f, 0xc9, 0x0b, 0xe8,
	0x65, 0x22, 0x17, 0x36, 0xad, 0xd7, 0x10, 0x6f, 0xed, 0x85, 0xfb, 0x9d, 0xd1, 0x68, 0xb0, 0xd9,
	0x1e, 0x06, 0xa7, 0xbe, 0xde, 0x11, 0xb5, 0x34, 0xe9, 0x7a, 0xa7, 0xa4, 0x32, 0x22, 0x2f, 0x21,
	0xd2, 0xf8, 0x53, 0x89, 0xe6, 0x96, 0x79, 0xf8, 0x9f, 0xcd, 0x1f, 0x55, 0x5e, 0xb5, 0x7d, 0xff,
	0x97, 0x26, 0x84, 0x33, 0xc5, 0x49, 0x0a, 0x8f, 0xdc, 0x24, 0xa6, 0xa0, 0x0c, 0x79, 0xba, 0x1e,
	0xb0, 0x33, 0xfa, 0x7c, 0xd3, 0x2a, 0x67, 0x6b, 0xb9, 0x7b, 0x4a, 0x7a, 0xf2, 0x0e, 0x26, 0xef,
	0x41, 0xb7, 0xee, 0x3f, 0xcd, 0x84, 0x5c, 0xc6, 0x5b, 0x7e, 0x7f, 0x3b, 0xf5, 0xe1, 0x54, 0xc8,
	0x25, 0xf9, 0x1e, 0xe0, 0x75, 0xb5, 0x6a, 0xcc, 0xc3, 0x4d, 0x1b, 0x58, 0x5f, 0x51, 0x72, 0xcb,
	0x84, 0xbc, 0x0d, 0x20, 0x4c, 0x5a, 0x89, 0xe2, 0xc6, 0x5e, 0xb0, 0xdf, 0x4a, 0xda, 0xc2, 0x8c,
	0x57, 0x07, 0xe4, 0x25, 0xf4, 0xea, 0x20, 0x18, 0x46, 0x33, 0xd4, 0xf1, 0xc3, 0xff, 0x35, 0x76,
	0xb7, 0x22, 0xce, 0xbd, 0x19, 0x79, 0x0a, 0x6d, 0xa9, 0x38, 0xae, 0x16, 0xda, 0xf4, 0x13, 0xb7,
	0xdc, 0x81, 0x5f, 0xc9, 0x17, 0x00, 0xc6, 0x52, 0x6d, 0x53, 0x17, 0xe4, 0x78, 0xdb, 0xd7, 0xdd,
	0x1d, 0xac, 0x52, 0x3e, 0xa8, 0x53, 0x3e, 0xb8, 0xa8, 0x53, 0x9e, 0xb4, 0x3d, 0xdb, 0x61, 0x72,
	0x01, 0xcd, 0x42, 0x65, 0x82, 0xdd, 0xc4, 0xad, 0xbd, 0x60, 0xbf, 0x37, 0xfa, 0x72, 0xd3, 0x76,
	0x13, 0x64, 0x2a, 0xcf, 0x51, 0x72, 0x6a, 0x85, 0x92, 0x33, 0xef, 0x91, 0x54, 0x5e, 0xe4, 0x47,
	0xe8, 0x59, 0x55, 0xa4, 0xce, 0x4a, 0xab, 0xcc, 0x2d, 0xa3, 0xed, 0x9b, 0xfa, 0x6c, 0x53, 0xf7,
	0x0b, 0x55, 0x4c, 0xd6, 0xe2, 0xa4, 0x6b, 0x6f, 0x43, 0xf2, 0x29, 0x3c, 0x29, 0x0d, 0xf2, 0x54,
	0xdf, 0x69, 0x21, 0x15, 0x3c, 0x06, 0xbf, 0x98, 0xc7, 0xee, 0xed, 0xdd, 0xfe, 0x4e, 0x38, 0x39,
	0x81, 0xa6, 0xb1, 0xd4, 0x96, 0x26, 0xee, 0xf8, 0x49, 0x37, 0x8e, 0xc3, 0x4c, 0xf1, 0xb9, 0x17,
	0x26, 0x95, 0x01, 0x79, 0x02, 0x4d, 0x8d, 0xd4, 0x28, 0x19, 0xef, 0xf8, 0x82, 0x15, 0xea, 0xff,
	0x1a, 0x40, 0x6b, 0x42, 0x0b, 0xca, 0x84, 0xbd, 0x71, 0x37, 0xc6, 0x8a, 0x32, 0x65, 0x4a, 0xa3,
	0xf1, 0x9f, 0x40, 0x98, 0xb4, 0x58, 0x51, 0x4e, 0x1c, 0x26, 0xef, 0xc2, 0x4e, 0x8e, 0xb9, 0xd2,
	0x37, 0xe9, 0xe2, 0xc6, 0xa2, 0xf1, 0x19, 0x0e, 0x93, 0xce, 0xea, 0xec, 0x99, 0x3b, 0x22, 0x5f,
	0xc1, 0x53, 0x89, 0xf6, 0x95, 0xb2, 0xcb, 0x34, 0xc7, 0x2b, 0xba, 0x10, 0xd6, 0xa4, 0x05, 0xea,
	0xd4, 0x20, 0x53, 0x92, 0xc7, 0xa1, 0x57, 0xc4, 0x15, 0xe5, 0xb4, 0x62, 0xcc, 0x50, 0xcf, 0xfd,
	0xfb, 0xfe, 0x6f, 0x01, 0x34, 0xce, 0x14, 0xc7, 0xbf, 0xfd, 0xcd, 0x4c, 0xa1, 0xc5, 0xaa, 0x3e,
	0x7d, 0xe9, 0xce, 0xe8, 0xe3, 0x8d, 0x3f, 0x8e, 0x4a, 0x97, 0xac, 0x1d, 0xfe, 0x12, 0xbf, 0xf0,
	0x5f, 0xc4, 0xaf, 0xff, 0x7b, 0x00, 0xdd, 0x3b, 0x77, 0xfd, 0xe6, 0xff, 0x1f, 0x5f, 0x43, 0x63,
	0x29, 0x24, 0xf7, 0x73, 0xf7, 0x46, 0x1f, 0x6d, 0xea, 0xfa, 0x9d, 0x90, 0x3c, 0xf1, 0xca, 0x83,
	0x6f, 0xa1, 0xe1, 0x10, 0xd9, 0x86, 0x70, 0x76, 0x7e, 0x14, 0x3d, 0x20, 0x3d, 0x80, 0xa3, 0xe3,
	0xd9, 0xf4, 0xfc, 0xc5, 0xe9, 0xf1, 0xd9, 0x45, 0x14, 0x90, 0xc7, 0x10, 0xbd, 0xc6, 0x93, 0xf3,
	0xb3, 0xe7, 0x27, 0xdf, 0x44, 0x5b, 0xe4, 0x2d, 0xe8, 0x8e, 0xa7, 0xe3, 0xd3, 0xe3, 0xa3, 0xf1,
	0x7c, 0x32, 0x9e, 0x1e, 0x27, 0x51, 0x78, 0xa0, 0xa1, 0xbd, 0x4e, 0x17, 0xe9, 0xc0, 0xf6, 0x0c,
	0x25, 0x17, 0xf2, 0x2a, 0x7a, 0xe0, 0x40, 0x52, 0x4a, 0xe9, 0x40, 0x40, 0xba, 0xd0, 0x9e, 0x97,
	0x8c, 0x21, 0x72, 0xe4, 0xd1, 0x16, 0x01, 0x68, 0x3e, 0xa7, 0x22, 0x43, 0x1e, 0x85, 0x8e, 0xf7,
	0x83, 0x5c, 0x4a, 0xf5, 0x4a, 0x46, 0x0d, 0xc7, 0x9b, 0xa8, 0xbc, 0xc8, 0xd0, 0x22, 0x8f, 0x1e,
	0xba, 0x36, 0x26, 0x9a, 0x9a, 0xeb, 0xa9, 0x52, 0xc5, 0x33, 0xca, 0x96, 0xe7, 0x97, 0x97, 0x51,
	0x73, 0xd1, 0xf4, 0x37, 0xf2, 0xc9, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x5d, 0xa8, 0xf7,
	0x87, 0x07, 0x00, 0x00,
}
