# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from alameda_api.v1alpha1.datahub import server_pb2 as alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class DatahubServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListMetrics = channel.unary_unary(
        '/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListMetrics',
        request_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.ListMetricsRequest.SerializeToString,
        response_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.ListMetricsResponse.FromString,
        )
    self.ListMetricsSum = channel.unary_unary(
        '/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListMetricsSum',
        request_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.ListMetricsSumRequest.SerializeToString,
        response_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.ListMetricsSumResponse.FromString,
        )
    self.RegisterAlamedaPod = channel.unary_unary(
        '/containers_ai.alameda.v1alpha1.datahub.DatahubService/RegisterAlamedaPod',
        request_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.RegisterAlamedaPodRequest.SerializeToString,
        response_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.Response.FromString,
        )
    self.DeregisterAlamedaPod = channel.unary_unary(
        '/containers_ai.alameda.v1alpha1.datahub.DatahubService/DeregisterAlamedaPod',
        request_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.DeregisterAlamedaPodRequest.SerializeToString,
        response_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.Response.FromString,
        )
    self.RegisterAlamedaNode = channel.unary_unary(
        '/containers_ai.alameda.v1alpha1.datahub.DatahubService/RegisterAlamedaNode',
        request_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.RegisterAlamedaNodeRequest.SerializeToString,
        response_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.Response.FromString,
        )
    self.DeregisterAlamedaNode = channel.unary_unary(
        '/containers_ai.alameda.v1alpha1.datahub.DatahubService/DeregisterAlamedaNode',
        request_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.DeregisterAlamedaNodeRequest.SerializeToString,
        response_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.Response.FromString,
        )
    self.ListAlamedaPods = channel.unary_unary(
        '/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListAlamedaPods',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.Response.FromString,
        )
    self.ListAlamedaNodes = channel.unary_unary(
        '/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListAlamedaNodes',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.Response.FromString,
        )
    self.CreatePredictPods = channel.unary_unary(
        '/containers_ai.alameda.v1alpha1.datahub.DatahubService/CreatePredictPods',
        request_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.CreatePredictPodsRequest.SerializeToString,
        response_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.Response.FromString,
        )
    self.CreatePredictNodes = channel.unary_unary(
        '/containers_ai.alameda.v1alpha1.datahub.DatahubService/CreatePredictNodes',
        request_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.CreatePredictNodesRequest.SerializeToString,
        response_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.Response.FromString,
        )
    self.GetPodPredictResult = channel.unary_unary(
        '/containers_ai.alameda.v1alpha1.datahub.DatahubService/GetPodPredictResult',
        request_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.GetPodPredictRequest.SerializeToString,
        response_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.GetPodPredictResponse.FromString,
        )
    self.GetNodePredictResult = channel.unary_unary(
        '/containers_ai.alameda.v1alpha1.datahub.DatahubService/GetNodePredictResult',
        request_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.GetNodePredictRequest.SerializeToString,
        response_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.GetNodePredictResponse.FromString,
        )


class DatahubServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListMetrics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListMetricsSum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RegisterAlamedaPod(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeregisterAlamedaPod(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RegisterAlamedaNode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeregisterAlamedaNode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListAlamedaPods(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListAlamedaNodes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreatePredictPods(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreatePredictNodes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPodPredictResult(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNodePredictResult(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DatahubServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListMetrics': grpc.unary_unary_rpc_method_handler(
          servicer.ListMetrics,
          request_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.ListMetricsRequest.FromString,
          response_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.ListMetricsResponse.SerializeToString,
      ),
      'ListMetricsSum': grpc.unary_unary_rpc_method_handler(
          servicer.ListMetricsSum,
          request_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.ListMetricsSumRequest.FromString,
          response_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.ListMetricsSumResponse.SerializeToString,
      ),
      'RegisterAlamedaPod': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterAlamedaPod,
          request_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.RegisterAlamedaPodRequest.FromString,
          response_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.Response.SerializeToString,
      ),
      'DeregisterAlamedaPod': grpc.unary_unary_rpc_method_handler(
          servicer.DeregisterAlamedaPod,
          request_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.DeregisterAlamedaPodRequest.FromString,
          response_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.Response.SerializeToString,
      ),
      'RegisterAlamedaNode': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterAlamedaNode,
          request_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.RegisterAlamedaNodeRequest.FromString,
          response_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.Response.SerializeToString,
      ),
      'DeregisterAlamedaNode': grpc.unary_unary_rpc_method_handler(
          servicer.DeregisterAlamedaNode,
          request_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.DeregisterAlamedaNodeRequest.FromString,
          response_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.Response.SerializeToString,
      ),
      'ListAlamedaPods': grpc.unary_unary_rpc_method_handler(
          servicer.ListAlamedaPods,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.Response.SerializeToString,
      ),
      'ListAlamedaNodes': grpc.unary_unary_rpc_method_handler(
          servicer.ListAlamedaNodes,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.Response.SerializeToString,
      ),
      'CreatePredictPods': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePredictPods,
          request_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.CreatePredictPodsRequest.FromString,
          response_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.Response.SerializeToString,
      ),
      'CreatePredictNodes': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePredictNodes,
          request_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.CreatePredictNodesRequest.FromString,
          response_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.Response.SerializeToString,
      ),
      'GetPodPredictResult': grpc.unary_unary_rpc_method_handler(
          servicer.GetPodPredictResult,
          request_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.GetPodPredictRequest.FromString,
          response_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.GetPodPredictResponse.SerializeToString,
      ),
      'GetNodePredictResult': grpc.unary_unary_rpc_method_handler(
          servicer.GetNodePredictResult,
          request_deserializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.GetNodePredictRequest.FromString,
          response_serializer=alameda__api_dot_v1alpha1_dot_datahub_dot_server__pb2.GetNodePredictResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'containers_ai.alameda.v1alpha1.datahub.DatahubService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
