// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alameda_api/v1alpha1/datahub/server.proto

package containers_ai_alameda_v1alpha1_datahub

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import status "google.golang.org/genproto/googleapis/rpc/status"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Represents a request for listing metric data of a pod
//
type ListPodMetricsRequest struct {
	NamespacedName       *NamespacedName `protobuf:"bytes,1,opt,name=namespaced_name,json=namespacedName,proto3" json:"namespaced_name,omitempty"`
	TimeRange            *TimeRange      `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListPodMetricsRequest) Reset()         { *m = ListPodMetricsRequest{} }
func (m *ListPodMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPodMetricsRequest) ProtoMessage()    {}
func (*ListPodMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{0}
}
func (m *ListPodMetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodMetricsRequest.Unmarshal(m, b)
}
func (m *ListPodMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodMetricsRequest.Marshal(b, m, deterministic)
}
func (dst *ListPodMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodMetricsRequest.Merge(dst, src)
}
func (m *ListPodMetricsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPodMetricsRequest.Size(m)
}
func (m *ListPodMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodMetricsRequest proto.InternalMessageInfo

func (m *ListPodMetricsRequest) GetNamespacedName() *NamespacedName {
	if m != nil {
		return m.NamespacedName
	}
	return nil
}

func (m *ListPodMetricsRequest) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

// *
// Represents a response for a listing pod metric data request
//
type ListPodMetricsResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PodMetrics           []*PodMetric   `protobuf:"bytes,2,rep,name=pod_metrics,json=podMetrics,proto3" json:"pod_metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListPodMetricsResponse) Reset()         { *m = ListPodMetricsResponse{} }
func (m *ListPodMetricsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPodMetricsResponse) ProtoMessage()    {}
func (*ListPodMetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{1}
}
func (m *ListPodMetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodMetricsResponse.Unmarshal(m, b)
}
func (m *ListPodMetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodMetricsResponse.Marshal(b, m, deterministic)
}
func (dst *ListPodMetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodMetricsResponse.Merge(dst, src)
}
func (m *ListPodMetricsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPodMetricsResponse.Size(m)
}
func (m *ListPodMetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodMetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodMetricsResponse proto.InternalMessageInfo

func (m *ListPodMetricsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListPodMetricsResponse) GetPodMetrics() []*PodMetric {
	if m != nil {
		return m.PodMetrics
	}
	return nil
}

// *
// Represents a request for listing metric data of a node
//
type ListNodeMetricsRequest struct {
	NodeNames            []string   `protobuf:"bytes,1,rep,name=node_names,json=nodeNames,proto3" json:"node_names,omitempty"`
	TimeRange            *TimeRange `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListNodeMetricsRequest) Reset()         { *m = ListNodeMetricsRequest{} }
func (m *ListNodeMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*ListNodeMetricsRequest) ProtoMessage()    {}
func (*ListNodeMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{2}
}
func (m *ListNodeMetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodeMetricsRequest.Unmarshal(m, b)
}
func (m *ListNodeMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodeMetricsRequest.Marshal(b, m, deterministic)
}
func (dst *ListNodeMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodeMetricsRequest.Merge(dst, src)
}
func (m *ListNodeMetricsRequest) XXX_Size() int {
	return xxx_messageInfo_ListNodeMetricsRequest.Size(m)
}
func (m *ListNodeMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodeMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodeMetricsRequest proto.InternalMessageInfo

func (m *ListNodeMetricsRequest) GetNodeNames() []string {
	if m != nil {
		return m.NodeNames
	}
	return nil
}

func (m *ListNodeMetricsRequest) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

// *
// Represents a response for a listing node metrics request
//
type ListNodeMetricsResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NodeMetrics          []*NodeMetric  `protobuf:"bytes,2,rep,name=node_metrics,json=nodeMetrics,proto3" json:"node_metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListNodeMetricsResponse) Reset()         { *m = ListNodeMetricsResponse{} }
func (m *ListNodeMetricsResponse) String() string { return proto.CompactTextString(m) }
func (*ListNodeMetricsResponse) ProtoMessage()    {}
func (*ListNodeMetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{3}
}
func (m *ListNodeMetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodeMetricsResponse.Unmarshal(m, b)
}
func (m *ListNodeMetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodeMetricsResponse.Marshal(b, m, deterministic)
}
func (dst *ListNodeMetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodeMetricsResponse.Merge(dst, src)
}
func (m *ListNodeMetricsResponse) XXX_Size() int {
	return xxx_messageInfo_ListNodeMetricsResponse.Size(m)
}
func (m *ListNodeMetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodeMetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodeMetricsResponse proto.InternalMessageInfo

func (m *ListNodeMetricsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListNodeMetricsResponse) GetNodeMetrics() []*NodeMetric {
	if m != nil {
		return m.NodeMetrics
	}
	return nil
}

// *
// Represents a response for a listing pods request
//
type ListPodsResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Pods                 []*Pod         `protobuf:"bytes,2,rep,name=pods,proto3" json:"pods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListPodsResponse) Reset()         { *m = ListPodsResponse{} }
func (m *ListPodsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPodsResponse) ProtoMessage()    {}
func (*ListPodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{4}
}
func (m *ListPodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodsResponse.Unmarshal(m, b)
}
func (m *ListPodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodsResponse.Marshal(b, m, deterministic)
}
func (dst *ListPodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodsResponse.Merge(dst, src)
}
func (m *ListPodsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPodsResponse.Size(m)
}
func (m *ListPodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodsResponse proto.InternalMessageInfo

func (m *ListPodsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListPodsResponse) GetPods() []*Pod {
	if m != nil {
		return m.Pods
	}
	return nil
}

// *
// Represents a request for listing pods that need to be predicted
//
type ListAlamedaPodsRequest struct {
	AlamedaScaler        *NamespacedName `protobuf:"bytes,1,opt,name=alameda_scaler,json=alamedaScaler,proto3" json:"alameda_scaler,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListAlamedaPodsRequest) Reset()         { *m = ListAlamedaPodsRequest{} }
func (m *ListAlamedaPodsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAlamedaPodsRequest) ProtoMessage()    {}
func (*ListAlamedaPodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{5}
}
func (m *ListAlamedaPodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAlamedaPodsRequest.Unmarshal(m, b)
}
func (m *ListAlamedaPodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAlamedaPodsRequest.Marshal(b, m, deterministic)
}
func (dst *ListAlamedaPodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAlamedaPodsRequest.Merge(dst, src)
}
func (m *ListAlamedaPodsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAlamedaPodsRequest.Size(m)
}
func (m *ListAlamedaPodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAlamedaPodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAlamedaPodsRequest proto.InternalMessageInfo

func (m *ListAlamedaPodsRequest) GetAlamedaScaler() *NamespacedName {
	if m != nil {
		return m.AlamedaScaler
	}
	return nil
}

// *
// Represents a response for a listing nodes request
//
type ListNodesResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Nodes                []*Node        `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListNodesResponse) Reset()         { *m = ListNodesResponse{} }
func (m *ListNodesResponse) String() string { return proto.CompactTextString(m) }
func (*ListNodesResponse) ProtoMessage()    {}
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{6}
}
func (m *ListNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodesResponse.Unmarshal(m, b)
}
func (m *ListNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodesResponse.Marshal(b, m, deterministic)
}
func (dst *ListNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodesResponse.Merge(dst, src)
}
func (m *ListNodesResponse) XXX_Size() int {
	return xxx_messageInfo_ListNodesResponse.Size(m)
}
func (m *ListNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodesResponse proto.InternalMessageInfo

func (m *ListNodesResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListNodesResponse) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// *
// Represents a request for listing predictions of pods
//
type ListPodPredictionsRequest struct {
	NamespacedName       *NamespacedName `protobuf:"bytes,1,opt,name=namespaced_name,json=namespacedName,proto3" json:"namespaced_name,omitempty"`
	TimeRange            *TimeRange      `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListPodPredictionsRequest) Reset()         { *m = ListPodPredictionsRequest{} }
func (m *ListPodPredictionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPodPredictionsRequest) ProtoMessage()    {}
func (*ListPodPredictionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{7}
}
func (m *ListPodPredictionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodPredictionsRequest.Unmarshal(m, b)
}
func (m *ListPodPredictionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodPredictionsRequest.Marshal(b, m, deterministic)
}
func (dst *ListPodPredictionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodPredictionsRequest.Merge(dst, src)
}
func (m *ListPodPredictionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPodPredictionsRequest.Size(m)
}
func (m *ListPodPredictionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodPredictionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodPredictionsRequest proto.InternalMessageInfo

func (m *ListPodPredictionsRequest) GetNamespacedName() *NamespacedName {
	if m != nil {
		return m.NamespacedName
	}
	return nil
}

func (m *ListPodPredictionsRequest) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

// *
// Represents a response for a listing predictions of pods request
//
type ListPodPredictionsResponse struct {
	Status               *status.Status   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PodPredictions       []*PodPrediction `protobuf:"bytes,2,rep,name=pod_predictions,json=podPredictions,proto3" json:"pod_predictions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListPodPredictionsResponse) Reset()         { *m = ListPodPredictionsResponse{} }
func (m *ListPodPredictionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPodPredictionsResponse) ProtoMessage()    {}
func (*ListPodPredictionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{8}
}
func (m *ListPodPredictionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodPredictionsResponse.Unmarshal(m, b)
}
func (m *ListPodPredictionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodPredictionsResponse.Marshal(b, m, deterministic)
}
func (dst *ListPodPredictionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodPredictionsResponse.Merge(dst, src)
}
func (m *ListPodPredictionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPodPredictionsResponse.Size(m)
}
func (m *ListPodPredictionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodPredictionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodPredictionsResponse proto.InternalMessageInfo

func (m *ListPodPredictionsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListPodPredictionsResponse) GetPodPredictions() []*PodPrediction {
	if m != nil {
		return m.PodPredictions
	}
	return nil
}

// *
// Represents a request for listing predictions of nodes
//
type ListNodePredictionsRequest struct {
	NodeName             []string   `protobuf:"bytes,1,rep,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	TimeRange            *TimeRange `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListNodePredictionsRequest) Reset()         { *m = ListNodePredictionsRequest{} }
func (m *ListNodePredictionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListNodePredictionsRequest) ProtoMessage()    {}
func (*ListNodePredictionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{9}
}
func (m *ListNodePredictionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodePredictionsRequest.Unmarshal(m, b)
}
func (m *ListNodePredictionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodePredictionsRequest.Marshal(b, m, deterministic)
}
func (dst *ListNodePredictionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodePredictionsRequest.Merge(dst, src)
}
func (m *ListNodePredictionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListNodePredictionsRequest.Size(m)
}
func (m *ListNodePredictionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodePredictionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodePredictionsRequest proto.InternalMessageInfo

func (m *ListNodePredictionsRequest) GetNodeName() []string {
	if m != nil {
		return m.NodeName
	}
	return nil
}

func (m *ListNodePredictionsRequest) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

// *
// Represents a response for a listing predictions of nodes request
//
type ListNodePredictionsResponse struct {
	Status               *status.Status    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NodePredictions      []*NodePrediction `protobuf:"bytes,2,rep,name=node_predictions,json=nodePredictions,proto3" json:"node_predictions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListNodePredictionsResponse) Reset()         { *m = ListNodePredictionsResponse{} }
func (m *ListNodePredictionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListNodePredictionsResponse) ProtoMessage()    {}
func (*ListNodePredictionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{10}
}
func (m *ListNodePredictionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodePredictionsResponse.Unmarshal(m, b)
}
func (m *ListNodePredictionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodePredictionsResponse.Marshal(b, m, deterministic)
}
func (dst *ListNodePredictionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodePredictionsResponse.Merge(dst, src)
}
func (m *ListNodePredictionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListNodePredictionsResponse.Size(m)
}
func (m *ListNodePredictionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodePredictionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodePredictionsResponse proto.InternalMessageInfo

func (m *ListNodePredictionsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListNodePredictionsResponse) GetNodePredictions() []*NodePrediction {
	if m != nil {
		return m.NodePredictions
	}
	return nil
}

// *
// Represents a request for listing recommendations of pods
//
type ListPodRecommendationsRequest struct {
	NamespacedName       *NamespacedName `protobuf:"bytes,1,opt,name=namespaced_name,json=namespacedName,proto3" json:"namespaced_name,omitempty"`
	TimeRange            *TimeRange      `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListPodRecommendationsRequest) Reset()         { *m = ListPodRecommendationsRequest{} }
func (m *ListPodRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPodRecommendationsRequest) ProtoMessage()    {}
func (*ListPodRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{11}
}
func (m *ListPodRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodRecommendationsRequest.Unmarshal(m, b)
}
func (m *ListPodRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodRecommendationsRequest.Marshal(b, m, deterministic)
}
func (dst *ListPodRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodRecommendationsRequest.Merge(dst, src)
}
func (m *ListPodRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPodRecommendationsRequest.Size(m)
}
func (m *ListPodRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodRecommendationsRequest proto.InternalMessageInfo

func (m *ListPodRecommendationsRequest) GetNamespacedName() *NamespacedName {
	if m != nil {
		return m.NamespacedName
	}
	return nil
}

func (m *ListPodRecommendationsRequest) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

// *
// Represents a response for listing pod recommendations request
//
type ListPodRecommendationsResponse struct {
	Status               *status.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PodRecommendations   []*PodRecommendation `protobuf:"bytes,2,rep,name=pod_recommendations,json=podRecommendations,proto3" json:"pod_recommendations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListPodRecommendationsResponse) Reset()         { *m = ListPodRecommendationsResponse{} }
func (m *ListPodRecommendationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPodRecommendationsResponse) ProtoMessage()    {}
func (*ListPodRecommendationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{12}
}
func (m *ListPodRecommendationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodRecommendationsResponse.Unmarshal(m, b)
}
func (m *ListPodRecommendationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodRecommendationsResponse.Marshal(b, m, deterministic)
}
func (dst *ListPodRecommendationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodRecommendationsResponse.Merge(dst, src)
}
func (m *ListPodRecommendationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPodRecommendationsResponse.Size(m)
}
func (m *ListPodRecommendationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodRecommendationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodRecommendationsResponse proto.InternalMessageInfo

func (m *ListPodRecommendationsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListPodRecommendationsResponse) GetPodRecommendations() []*PodRecommendation {
	if m != nil {
		return m.PodRecommendations
	}
	return nil
}

// *
// Represents a request for listing pods by a node name
//
type ListPodsByNodeNameRequest struct {
	NodeName             []string `protobuf:"bytes,1,rep,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPodsByNodeNameRequest) Reset()         { *m = ListPodsByNodeNameRequest{} }
func (m *ListPodsByNodeNameRequest) String() string { return proto.CompactTextString(m) }
func (*ListPodsByNodeNameRequest) ProtoMessage()    {}
func (*ListPodsByNodeNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{13}
}
func (m *ListPodsByNodeNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodsByNodeNameRequest.Unmarshal(m, b)
}
func (m *ListPodsByNodeNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodsByNodeNameRequest.Marshal(b, m, deterministic)
}
func (dst *ListPodsByNodeNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodsByNodeNameRequest.Merge(dst, src)
}
func (m *ListPodsByNodeNameRequest) XXX_Size() int {
	return xxx_messageInfo_ListPodsByNodeNameRequest.Size(m)
}
func (m *ListPodsByNodeNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodsByNodeNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodsByNodeNameRequest proto.InternalMessageInfo

func (m *ListPodsByNodeNameRequest) GetNodeName() []string {
	if m != nil {
		return m.NodeName
	}
	return nil
}

// *
// Represents a request for listing system scores of pod scheduled on node
//
type ListSimulatedSchedulingScoresRequest struct {
	TimeRange            *TimeRange `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListSimulatedSchedulingScoresRequest) Reset()         { *m = ListSimulatedSchedulingScoresRequest{} }
func (m *ListSimulatedSchedulingScoresRequest) String() string { return proto.CompactTextString(m) }
func (*ListSimulatedSchedulingScoresRequest) ProtoMessage()    {}
func (*ListSimulatedSchedulingScoresRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{14}
}
func (m *ListSimulatedSchedulingScoresRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSimulatedSchedulingScoresRequest.Unmarshal(m, b)
}
func (m *ListSimulatedSchedulingScoresRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSimulatedSchedulingScoresRequest.Marshal(b, m, deterministic)
}
func (dst *ListSimulatedSchedulingScoresRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSimulatedSchedulingScoresRequest.Merge(dst, src)
}
func (m *ListSimulatedSchedulingScoresRequest) XXX_Size() int {
	return xxx_messageInfo_ListSimulatedSchedulingScoresRequest.Size(m)
}
func (m *ListSimulatedSchedulingScoresRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSimulatedSchedulingScoresRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSimulatedSchedulingScoresRequest proto.InternalMessageInfo

func (m *ListSimulatedSchedulingScoresRequest) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

// *
// Represents a response for listing system scores request
//
type ListSimulatedSchedulingScoresResponse struct {
	Scores               []*SimulatedSchedulingScore `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ListSimulatedSchedulingScoresResponse) Reset()         { *m = ListSimulatedSchedulingScoresResponse{} }
func (m *ListSimulatedSchedulingScoresResponse) String() string { return proto.CompactTextString(m) }
func (*ListSimulatedSchedulingScoresResponse) ProtoMessage()    {}
func (*ListSimulatedSchedulingScoresResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{15}
}
func (m *ListSimulatedSchedulingScoresResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSimulatedSchedulingScoresResponse.Unmarshal(m, b)
}
func (m *ListSimulatedSchedulingScoresResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSimulatedSchedulingScoresResponse.Marshal(b, m, deterministic)
}
func (dst *ListSimulatedSchedulingScoresResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSimulatedSchedulingScoresResponse.Merge(dst, src)
}
func (m *ListSimulatedSchedulingScoresResponse) XXX_Size() int {
	return xxx_messageInfo_ListSimulatedSchedulingScoresResponse.Size(m)
}
func (m *ListSimulatedSchedulingScoresResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSimulatedSchedulingScoresResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSimulatedSchedulingScoresResponse proto.InternalMessageInfo

func (m *ListSimulatedSchedulingScoresResponse) GetScores() []*SimulatedSchedulingScore {
	if m != nil {
		return m.Scores
	}
	return nil
}

// *
// Represents a request for creating predictions of containers' metric data belonging to a pod
type CreatePodPredictionsRequest struct {
	PodPredictions       []*PodPrediction `protobuf:"bytes,1,rep,name=pod_predictions,json=podPredictions,proto3" json:"pod_predictions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreatePodPredictionsRequest) Reset()         { *m = CreatePodPredictionsRequest{} }
func (m *CreatePodPredictionsRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePodPredictionsRequest) ProtoMessage()    {}
func (*CreatePodPredictionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{16}
}
func (m *CreatePodPredictionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePodPredictionsRequest.Unmarshal(m, b)
}
func (m *CreatePodPredictionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePodPredictionsRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePodPredictionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePodPredictionsRequest.Merge(dst, src)
}
func (m *CreatePodPredictionsRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePodPredictionsRequest.Size(m)
}
func (m *CreatePodPredictionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePodPredictionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePodPredictionsRequest proto.InternalMessageInfo

func (m *CreatePodPredictionsRequest) GetPodPredictions() []*PodPrediction {
	if m != nil {
		return m.PodPredictions
	}
	return nil
}

// *
// Represents a request for creating predictions of a node metric data
//
type CreateNodePredictionsRequest struct {
	NodePredictions      []*NodePrediction `protobuf:"bytes,1,rep,name=node_predictions,json=nodePredictions,proto3" json:"node_predictions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateNodePredictionsRequest) Reset()         { *m = CreateNodePredictionsRequest{} }
func (m *CreateNodePredictionsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNodePredictionsRequest) ProtoMessage()    {}
func (*CreateNodePredictionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{17}
}
func (m *CreateNodePredictionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNodePredictionsRequest.Unmarshal(m, b)
}
func (m *CreateNodePredictionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNodePredictionsRequest.Marshal(b, m, deterministic)
}
func (dst *CreateNodePredictionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNodePredictionsRequest.Merge(dst, src)
}
func (m *CreateNodePredictionsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNodePredictionsRequest.Size(m)
}
func (m *CreateNodePredictionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNodePredictionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNodePredictionsRequest proto.InternalMessageInfo

func (m *CreateNodePredictionsRequest) GetNodePredictions() []*NodePrediction {
	if m != nil {
		return m.NodePredictions
	}
	return nil
}

// *
// Represents a request for creating a pod's recommendation
//
type CreatePodRecommendationsRequest struct {
	PodRecommendations   []*PodRecommendation `protobuf:"bytes,1,rep,name=pod_recommendations,json=podRecommendations,proto3" json:"pod_recommendations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreatePodRecommendationsRequest) Reset()         { *m = CreatePodRecommendationsRequest{} }
func (m *CreatePodRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePodRecommendationsRequest) ProtoMessage()    {}
func (*CreatePodRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{18}
}
func (m *CreatePodRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePodRecommendationsRequest.Unmarshal(m, b)
}
func (m *CreatePodRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePodRecommendationsRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePodRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePodRecommendationsRequest.Merge(dst, src)
}
func (m *CreatePodRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePodRecommendationsRequest.Size(m)
}
func (m *CreatePodRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePodRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePodRecommendationsRequest proto.InternalMessageInfo

func (m *CreatePodRecommendationsRequest) GetPodRecommendations() []*PodRecommendation {
	if m != nil {
		return m.PodRecommendations
	}
	return nil
}

// *
// Represents a request for creating pods
//
type CreatePodsRequest struct {
	Pods                 []*Pod   `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePodsRequest) Reset()         { *m = CreatePodsRequest{} }
func (m *CreatePodsRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePodsRequest) ProtoMessage()    {}
func (*CreatePodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{19}
}
func (m *CreatePodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePodsRequest.Unmarshal(m, b)
}
func (m *CreatePodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePodsRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePodsRequest.Merge(dst, src)
}
func (m *CreatePodsRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePodsRequest.Size(m)
}
func (m *CreatePodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePodsRequest proto.InternalMessageInfo

func (m *CreatePodsRequest) GetPods() []*Pod {
	if m != nil {
		return m.Pods
	}
	return nil
}

// *
// Represents a request for adding nodes that need to be predicted
//
type CreateAlamedaNodesRequest struct {
	AlamedaNodes         []*Node  `protobuf:"bytes,1,rep,name=alameda_nodes,json=alamedaNodes,proto3" json:"alameda_nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAlamedaNodesRequest) Reset()         { *m = CreateAlamedaNodesRequest{} }
func (m *CreateAlamedaNodesRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAlamedaNodesRequest) ProtoMessage()    {}
func (*CreateAlamedaNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{20}
}
func (m *CreateAlamedaNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAlamedaNodesRequest.Unmarshal(m, b)
}
func (m *CreateAlamedaNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAlamedaNodesRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAlamedaNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAlamedaNodesRequest.Merge(dst, src)
}
func (m *CreateAlamedaNodesRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAlamedaNodesRequest.Size(m)
}
func (m *CreateAlamedaNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAlamedaNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAlamedaNodesRequest proto.InternalMessageInfo

func (m *CreateAlamedaNodesRequest) GetAlamedaNodes() []*Node {
	if m != nil {
		return m.AlamedaNodes
	}
	return nil
}

// *
// Represents a request for adding scheduling scores produced by ai engine
//
type CreateSimulatedSchedulingScoresRequest struct {
	Scores               []*SimulatedSchedulingScore `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CreateSimulatedSchedulingScoresRequest) Reset() {
	*m = CreateSimulatedSchedulingScoresRequest{}
}
func (m *CreateSimulatedSchedulingScoresRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSimulatedSchedulingScoresRequest) ProtoMessage()    {}
func (*CreateSimulatedSchedulingScoresRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{21}
}
func (m *CreateSimulatedSchedulingScoresRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSimulatedSchedulingScoresRequest.Unmarshal(m, b)
}
func (m *CreateSimulatedSchedulingScoresRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSimulatedSchedulingScoresRequest.Marshal(b, m, deterministic)
}
func (dst *CreateSimulatedSchedulingScoresRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSimulatedSchedulingScoresRequest.Merge(dst, src)
}
func (m *CreateSimulatedSchedulingScoresRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSimulatedSchedulingScoresRequest.Size(m)
}
func (m *CreateSimulatedSchedulingScoresRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSimulatedSchedulingScoresRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSimulatedSchedulingScoresRequest proto.InternalMessageInfo

func (m *CreateSimulatedSchedulingScoresRequest) GetScores() []*SimulatedSchedulingScore {
	if m != nil {
		return m.Scores
	}
	return nil
}

// *
// Represents a request for deleting pods data
//
type DeletePodsRequest struct {
	Pods                 []*Pod   `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePodsRequest) Reset()         { *m = DeletePodsRequest{} }
func (m *DeletePodsRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePodsRequest) ProtoMessage()    {}
func (*DeletePodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{22}
}
func (m *DeletePodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePodsRequest.Unmarshal(m, b)
}
func (m *DeletePodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePodsRequest.Marshal(b, m, deterministic)
}
func (dst *DeletePodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePodsRequest.Merge(dst, src)
}
func (m *DeletePodsRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePodsRequest.Size(m)
}
func (m *DeletePodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePodsRequest proto.InternalMessageInfo

func (m *DeletePodsRequest) GetPods() []*Pod {
	if m != nil {
		return m.Pods
	}
	return nil
}

// *
// Represents a request for stoping predicting nodes
//
type DeleteAlamedaNodesRequest struct {
	AlamedaNodes         []*Node  `protobuf:"bytes,1,rep,name=alameda_nodes,json=alamedaNodes,proto3" json:"alameda_nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAlamedaNodesRequest) Reset()         { *m = DeleteAlamedaNodesRequest{} }
func (m *DeleteAlamedaNodesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAlamedaNodesRequest) ProtoMessage()    {}
func (*DeleteAlamedaNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_8768198efcc43fe5, []int{23}
}
func (m *DeleteAlamedaNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAlamedaNodesRequest.Unmarshal(m, b)
}
func (m *DeleteAlamedaNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAlamedaNodesRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteAlamedaNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAlamedaNodesRequest.Merge(dst, src)
}
func (m *DeleteAlamedaNodesRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAlamedaNodesRequest.Size(m)
}
func (m *DeleteAlamedaNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAlamedaNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAlamedaNodesRequest proto.InternalMessageInfo

func (m *DeleteAlamedaNodesRequest) GetAlamedaNodes() []*Node {
	if m != nil {
		return m.AlamedaNodes
	}
	return nil
}

func init() {
	proto.RegisterType((*ListPodMetricsRequest)(nil), "containers_ai.alameda.v1alpha1.datahub.ListPodMetricsRequest")
	proto.RegisterType((*ListPodMetricsResponse)(nil), "containers_ai.alameda.v1alpha1.datahub.ListPodMetricsResponse")
	proto.RegisterType((*ListNodeMetricsRequest)(nil), "containers_ai.alameda.v1alpha1.datahub.ListNodeMetricsRequest")
	proto.RegisterType((*ListNodeMetricsResponse)(nil), "containers_ai.alameda.v1alpha1.datahub.ListNodeMetricsResponse")
	proto.RegisterType((*ListPodsResponse)(nil), "containers_ai.alameda.v1alpha1.datahub.ListPodsResponse")
	proto.RegisterType((*ListAlamedaPodsRequest)(nil), "containers_ai.alameda.v1alpha1.datahub.ListAlamedaPodsRequest")
	proto.RegisterType((*ListNodesResponse)(nil), "containers_ai.alameda.v1alpha1.datahub.ListNodesResponse")
	proto.RegisterType((*ListPodPredictionsRequest)(nil), "containers_ai.alameda.v1alpha1.datahub.ListPodPredictionsRequest")
	proto.RegisterType((*ListPodPredictionsResponse)(nil), "containers_ai.alameda.v1alpha1.datahub.ListPodPredictionsResponse")
	proto.RegisterType((*ListNodePredictionsRequest)(nil), "containers_ai.alameda.v1alpha1.datahub.ListNodePredictionsRequest")
	proto.RegisterType((*ListNodePredictionsResponse)(nil), "containers_ai.alameda.v1alpha1.datahub.ListNodePredictionsResponse")
	proto.RegisterType((*ListPodRecommendationsRequest)(nil), "containers_ai.alameda.v1alpha1.datahub.ListPodRecommendationsRequest")
	proto.RegisterType((*ListPodRecommendationsResponse)(nil), "containers_ai.alameda.v1alpha1.datahub.ListPodRecommendationsResponse")
	proto.RegisterType((*ListPodsByNodeNameRequest)(nil), "containers_ai.alameda.v1alpha1.datahub.ListPodsByNodeNameRequest")
	proto.RegisterType((*ListSimulatedSchedulingScoresRequest)(nil), "containers_ai.alameda.v1alpha1.datahub.ListSimulatedSchedulingScoresRequest")
	proto.RegisterType((*ListSimulatedSchedulingScoresResponse)(nil), "containers_ai.alameda.v1alpha1.datahub.ListSimulatedSchedulingScoresResponse")
	proto.RegisterType((*CreatePodPredictionsRequest)(nil), "containers_ai.alameda.v1alpha1.datahub.CreatePodPredictionsRequest")
	proto.RegisterType((*CreateNodePredictionsRequest)(nil), "containers_ai.alameda.v1alpha1.datahub.CreateNodePredictionsRequest")
	proto.RegisterType((*CreatePodRecommendationsRequest)(nil), "containers_ai.alameda.v1alpha1.datahub.CreatePodRecommendationsRequest")
	proto.RegisterType((*CreatePodsRequest)(nil), "containers_ai.alameda.v1alpha1.datahub.CreatePodsRequest")
	proto.RegisterType((*CreateAlamedaNodesRequest)(nil), "containers_ai.alameda.v1alpha1.datahub.CreateAlamedaNodesRequest")
	proto.RegisterType((*CreateSimulatedSchedulingScoresRequest)(nil), "containers_ai.alameda.v1alpha1.datahub.CreateSimulatedSchedulingScoresRequest")
	proto.RegisterType((*DeletePodsRequest)(nil), "containers_ai.alameda.v1alpha1.datahub.DeletePodsRequest")
	proto.RegisterType((*DeleteAlamedaNodesRequest)(nil), "containers_ai.alameda.v1alpha1.datahub.DeleteAlamedaNodesRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DatahubServiceClient is the client API for DatahubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DatahubServiceClient interface {
	// / Used to list pod metric data
	ListPodMetrics(ctx context.Context, in *ListPodMetricsRequest, opts ...grpc.CallOption) (*ListPodMetricsResponse, error)
	// / Used to list node metric data
	ListNodeMetrics(ctx context.Context, in *ListNodeMetricsRequest, opts ...grpc.CallOption) (*ListNodeMetricsResponse, error)
	// Used to list pods need to be predicted
	ListAlamedaPods(ctx context.Context, in *ListAlamedaPodsRequest, opts ...grpc.CallOption) (*ListPodsResponse, error)
	// Used to list nodes need to be predicted
	ListAlamedaNodes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// / Used to list pod predictions
	ListPodPredictions(ctx context.Context, in *ListPodPredictionsRequest, opts ...grpc.CallOption) (*ListPodPredictionsResponse, error)
	// / Used to list node predictions
	ListNodePredictions(ctx context.Context, in *ListNodePredictionsRequest, opts ...grpc.CallOption) (*ListNodePredictionsResponse, error)
	// / Used to list pod recommenations
	ListPodRecommendations(ctx context.Context, in *ListPodRecommendationsRequest, opts ...grpc.CallOption) (*ListPodRecommendationsResponse, error)
	// / Used to list pods by a node name
	ListPodsByNodeName(ctx context.Context, in *ListPodsByNodeNameRequest, opts ...grpc.CallOption) (*ListPodsResponse, error)
	// / Used to list system scores
	ListSimulatedSchedulingScores(ctx context.Context, in *ListSimulatedSchedulingScoresRequest, opts ...grpc.CallOption) (*ListSimulatedSchedulingScoresResponse, error)
	// / Used to add pods that need to be predicted
	CreatePods(ctx context.Context, in *CreatePodsRequest, opts ...grpc.CallOption) (*status.Status, error)
	// / Used to add nodes that need to be predicted
	CreateAlamedaNodes(ctx context.Context, in *CreateAlamedaNodesRequest, opts ...grpc.CallOption) (*status.Status, error)
	// / Used to create predictions of pods
	CreatePodPredictions(ctx context.Context, in *CreatePodPredictionsRequest, opts ...grpc.CallOption) (*status.Status, error)
	// / Used to create predictions of nodes
	CreateNodePredictions(ctx context.Context, in *CreateNodePredictionsRequest, opts ...grpc.CallOption) (*status.Status, error)
	// / Used to create recommendations of pods
	CreatePodRecommendations(ctx context.Context, in *CreatePodRecommendationsRequest, opts ...grpc.CallOption) (*status.Status, error)
	// / Used to create scores of system
	CreateSimulatedSchedulingScores(ctx context.Context, in *CreateSimulatedSchedulingScoresRequest, opts ...grpc.CallOption) (*status.Status, error)
	// / Used to delete info of pods
	DeletePods(ctx context.Context, in *DeletePodsRequest, opts ...grpc.CallOption) (*status.Status, error)
	// / Used to stop generating predictions for the nodes
	DeleteAlamedaNodes(ctx context.Context, in *DeleteAlamedaNodesRequest, opts ...grpc.CallOption) (*status.Status, error)
}

type datahubServiceClient struct {
	cc *grpc.ClientConn
}

func NewDatahubServiceClient(cc *grpc.ClientConn) DatahubServiceClient {
	return &datahubServiceClient{cc}
}

func (c *datahubServiceClient) ListPodMetrics(ctx context.Context, in *ListPodMetricsRequest, opts ...grpc.CallOption) (*ListPodMetricsResponse, error) {
	out := new(ListPodMetricsResponse)
	err := c.cc.Invoke(ctx, "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListPodMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) ListNodeMetrics(ctx context.Context, in *ListNodeMetricsRequest, opts ...grpc.CallOption) (*ListNodeMetricsResponse, error) {
	out := new(ListNodeMetricsResponse)
	err := c.cc.Invoke(ctx, "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListNodeMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) ListAlamedaPods(ctx context.Context, in *ListAlamedaPodsRequest, opts ...grpc.CallOption) (*ListPodsResponse, error) {
	out := new(ListPodsResponse)
	err := c.cc.Invoke(ctx, "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListAlamedaPods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) ListAlamedaNodes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListAlamedaNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) ListPodPredictions(ctx context.Context, in *ListPodPredictionsRequest, opts ...grpc.CallOption) (*ListPodPredictionsResponse, error) {
	out := new(ListPodPredictionsResponse)
	err := c.cc.Invoke(ctx, "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListPodPredictions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) ListNodePredictions(ctx context.Context, in *ListNodePredictionsRequest, opts ...grpc.CallOption) (*ListNodePredictionsResponse, error) {
	out := new(ListNodePredictionsResponse)
	err := c.cc.Invoke(ctx, "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListNodePredictions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) ListPodRecommendations(ctx context.Context, in *ListPodRecommendationsRequest, opts ...grpc.CallOption) (*ListPodRecommendationsResponse, error) {
	out := new(ListPodRecommendationsResponse)
	err := c.cc.Invoke(ctx, "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListPodRecommendations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) ListPodsByNodeName(ctx context.Context, in *ListPodsByNodeNameRequest, opts ...grpc.CallOption) (*ListPodsResponse, error) {
	out := new(ListPodsResponse)
	err := c.cc.Invoke(ctx, "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListPodsByNodeName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) ListSimulatedSchedulingScores(ctx context.Context, in *ListSimulatedSchedulingScoresRequest, opts ...grpc.CallOption) (*ListSimulatedSchedulingScoresResponse, error) {
	out := new(ListSimulatedSchedulingScoresResponse)
	err := c.cc.Invoke(ctx, "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListSimulatedSchedulingScores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) CreatePods(ctx context.Context, in *CreatePodsRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containers_ai.alameda.v1alpha1.datahub.DatahubService/CreatePods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) CreateAlamedaNodes(ctx context.Context, in *CreateAlamedaNodesRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containers_ai.alameda.v1alpha1.datahub.DatahubService/CreateAlamedaNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) CreatePodPredictions(ctx context.Context, in *CreatePodPredictionsRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containers_ai.alameda.v1alpha1.datahub.DatahubService/CreatePodPredictions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) CreateNodePredictions(ctx context.Context, in *CreateNodePredictionsRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containers_ai.alameda.v1alpha1.datahub.DatahubService/CreateNodePredictions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) CreatePodRecommendations(ctx context.Context, in *CreatePodRecommendationsRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containers_ai.alameda.v1alpha1.datahub.DatahubService/CreatePodRecommendations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) CreateSimulatedSchedulingScores(ctx context.Context, in *CreateSimulatedSchedulingScoresRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containers_ai.alameda.v1alpha1.datahub.DatahubService/CreateSimulatedSchedulingScores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) DeletePods(ctx context.Context, in *DeletePodsRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containers_ai.alameda.v1alpha1.datahub.DatahubService/DeletePods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) DeleteAlamedaNodes(ctx context.Context, in *DeleteAlamedaNodesRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containers_ai.alameda.v1alpha1.datahub.DatahubService/DeleteAlamedaNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatahubServiceServer is the server API for DatahubService service.
type DatahubServiceServer interface {
	// / Used to list pod metric data
	ListPodMetrics(context.Context, *ListPodMetricsRequest) (*ListPodMetricsResponse, error)
	// / Used to list node metric data
	ListNodeMetrics(context.Context, *ListNodeMetricsRequest) (*ListNodeMetricsResponse, error)
	// Used to list pods need to be predicted
	ListAlamedaPods(context.Context, *ListAlamedaPodsRequest) (*ListPodsResponse, error)
	// Used to list nodes need to be predicted
	ListAlamedaNodes(context.Context, *empty.Empty) (*ListNodesResponse, error)
	// / Used to list pod predictions
	ListPodPredictions(context.Context, *ListPodPredictionsRequest) (*ListPodPredictionsResponse, error)
	// / Used to list node predictions
	ListNodePredictions(context.Context, *ListNodePredictionsRequest) (*ListNodePredictionsResponse, error)
	// / Used to list pod recommenations
	ListPodRecommendations(context.Context, *ListPodRecommendationsRequest) (*ListPodRecommendationsResponse, error)
	// / Used to list pods by a node name
	ListPodsByNodeName(context.Context, *ListPodsByNodeNameRequest) (*ListPodsResponse, error)
	// / Used to list system scores
	ListSimulatedSchedulingScores(context.Context, *ListSimulatedSchedulingScoresRequest) (*ListSimulatedSchedulingScoresResponse, error)
	// / Used to add pods that need to be predicted
	CreatePods(context.Context, *CreatePodsRequest) (*status.Status, error)
	// / Used to add nodes that need to be predicted
	CreateAlamedaNodes(context.Context, *CreateAlamedaNodesRequest) (*status.Status, error)
	// / Used to create predictions of pods
	CreatePodPredictions(context.Context, *CreatePodPredictionsRequest) (*status.Status, error)
	// / Used to create predictions of nodes
	CreateNodePredictions(context.Context, *CreateNodePredictionsRequest) (*status.Status, error)
	// / Used to create recommendations of pods
	CreatePodRecommendations(context.Context, *CreatePodRecommendationsRequest) (*status.Status, error)
	// / Used to create scores of system
	CreateSimulatedSchedulingScores(context.Context, *CreateSimulatedSchedulingScoresRequest) (*status.Status, error)
	// / Used to delete info of pods
	DeletePods(context.Context, *DeletePodsRequest) (*status.Status, error)
	// / Used to stop generating predictions for the nodes
	DeleteAlamedaNodes(context.Context, *DeleteAlamedaNodesRequest) (*status.Status, error)
}

func RegisterDatahubServiceServer(s *grpc.Server, srv DatahubServiceServer) {
	s.RegisterService(&_DatahubService_serviceDesc, srv)
}

func _DatahubService_ListPodMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPodMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListPodMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListPodMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListPodMetrics(ctx, req.(*ListPodMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_ListNodeMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodeMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListNodeMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListNodeMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListNodeMetrics(ctx, req.(*ListNodeMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_ListAlamedaPods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlamedaPodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListAlamedaPods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListAlamedaPods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListAlamedaPods(ctx, req.(*ListAlamedaPodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_ListAlamedaNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListAlamedaNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListAlamedaNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListAlamedaNodes(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_ListPodPredictions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPodPredictionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListPodPredictions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListPodPredictions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListPodPredictions(ctx, req.(*ListPodPredictionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_ListNodePredictions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodePredictionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListNodePredictions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListNodePredictions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListNodePredictions(ctx, req.(*ListNodePredictionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_ListPodRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPodRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListPodRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListPodRecommendations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListPodRecommendations(ctx, req.(*ListPodRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_ListPodsByNodeName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPodsByNodeNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListPodsByNodeName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListPodsByNodeName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListPodsByNodeName(ctx, req.(*ListPodsByNodeNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_ListSimulatedSchedulingScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSimulatedSchedulingScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListSimulatedSchedulingScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containers_ai.alameda.v1alpha1.datahub.DatahubService/ListSimulatedSchedulingScores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListSimulatedSchedulingScores(ctx, req.(*ListSimulatedSchedulingScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_CreatePods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).CreatePods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containers_ai.alameda.v1alpha1.datahub.DatahubService/CreatePods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).CreatePods(ctx, req.(*CreatePodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_CreateAlamedaNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlamedaNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).CreateAlamedaNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containers_ai.alameda.v1alpha1.datahub.DatahubService/CreateAlamedaNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).CreateAlamedaNodes(ctx, req.(*CreateAlamedaNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_CreatePodPredictions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePodPredictionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).CreatePodPredictions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containers_ai.alameda.v1alpha1.datahub.DatahubService/CreatePodPredictions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).CreatePodPredictions(ctx, req.(*CreatePodPredictionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_CreateNodePredictions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodePredictionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).CreateNodePredictions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containers_ai.alameda.v1alpha1.datahub.DatahubService/CreateNodePredictions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).CreateNodePredictions(ctx, req.(*CreateNodePredictionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_CreatePodRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePodRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).CreatePodRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containers_ai.alameda.v1alpha1.datahub.DatahubService/CreatePodRecommendations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).CreatePodRecommendations(ctx, req.(*CreatePodRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_CreateSimulatedSchedulingScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSimulatedSchedulingScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).CreateSimulatedSchedulingScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containers_ai.alameda.v1alpha1.datahub.DatahubService/CreateSimulatedSchedulingScores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).CreateSimulatedSchedulingScores(ctx, req.(*CreateSimulatedSchedulingScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_DeletePods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).DeletePods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containers_ai.alameda.v1alpha1.datahub.DatahubService/DeletePods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).DeletePods(ctx, req.(*DeletePodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_DeleteAlamedaNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAlamedaNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).DeleteAlamedaNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containers_ai.alameda.v1alpha1.datahub.DatahubService/DeleteAlamedaNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).DeleteAlamedaNodes(ctx, req.(*DeleteAlamedaNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DatahubService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "containers_ai.alameda.v1alpha1.datahub.DatahubService",
	HandlerType: (*DatahubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPodMetrics",
			Handler:    _DatahubService_ListPodMetrics_Handler,
		},
		{
			MethodName: "ListNodeMetrics",
			Handler:    _DatahubService_ListNodeMetrics_Handler,
		},
		{
			MethodName: "ListAlamedaPods",
			Handler:    _DatahubService_ListAlamedaPods_Handler,
		},
		{
			MethodName: "ListAlamedaNodes",
			Handler:    _DatahubService_ListAlamedaNodes_Handler,
		},
		{
			MethodName: "ListPodPredictions",
			Handler:    _DatahubService_ListPodPredictions_Handler,
		},
		{
			MethodName: "ListNodePredictions",
			Handler:    _DatahubService_ListNodePredictions_Handler,
		},
		{
			MethodName: "ListPodRecommendations",
			Handler:    _DatahubService_ListPodRecommendations_Handler,
		},
		{
			MethodName: "ListPodsByNodeName",
			Handler:    _DatahubService_ListPodsByNodeName_Handler,
		},
		{
			MethodName: "ListSimulatedSchedulingScores",
			Handler:    _DatahubService_ListSimulatedSchedulingScores_Handler,
		},
		{
			MethodName: "CreatePods",
			Handler:    _DatahubService_CreatePods_Handler,
		},
		{
			MethodName: "CreateAlamedaNodes",
			Handler:    _DatahubService_CreateAlamedaNodes_Handler,
		},
		{
			MethodName: "CreatePodPredictions",
			Handler:    _DatahubService_CreatePodPredictions_Handler,
		},
		{
			MethodName: "CreateNodePredictions",
			Handler:    _DatahubService_CreateNodePredictions_Handler,
		},
		{
			MethodName: "CreatePodRecommendations",
			Handler:    _DatahubService_CreatePodRecommendations_Handler,
		},
		{
			MethodName: "CreateSimulatedSchedulingScores",
			Handler:    _DatahubService_CreateSimulatedSchedulingScores_Handler,
		},
		{
			MethodName: "DeletePods",
			Handler:    _DatahubService_DeletePods_Handler,
		},
		{
			MethodName: "DeleteAlamedaNodes",
			Handler:    _DatahubService_DeleteAlamedaNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alameda_api/v1alpha1/datahub/server.proto",
}

func init() {
	proto.RegisterFile("alameda_api/v1alpha1/datahub/server.proto", fileDescriptor_server_8768198efcc43fe5)
}

var fileDescriptor_server_8768198efcc43fe5 = []byte{
	// 1108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0x4f, 0x6f, 0xdc, 0x44,
	0x14, 0xef, 0xb4, 0x10, 0x91, 0x97, 0xb2, 0x69, 0xa6, 0xb4, 0x4d, 0x1d, 0x0a, 0x95, 0x05, 0x55,
	0xda, 0x22, 0xaf, 0x12, 0x44, 0xd5, 0x1e, 0xa0, 0x34, 0x49, 0xe1, 0xd2, 0x46, 0xc1, 0x1b, 0x24,
	0x2e, 0x61, 0x35, 0xb1, 0x87, 0x8d, 0xd1, 0xfa, 0x4f, 0xed, 0xd9, 0x40, 0x0e, 0x08, 0x95, 0x1e,
	0x10, 0x42, 0x3d, 0x20, 0x38, 0x70, 0x00, 0x89, 0x23, 0x48, 0x7c, 0x00, 0x4e, 0x7c, 0x00, 0x0e,
	0x1c, 0xf8, 0x44, 0xc8, 0x9e, 0xf1, 0xec, 0x3a, 0x1e, 0x67, 0x3d, 0xde, 0xdd, 0x4a, 0xbd, 0x79,
	0xe3, 0x79, 0xef, 0xfd, 0xde, 0xef, 0xbd, 0x79, 0xef, 0xe7, 0xc0, 0x75, 0xd2, 0x27, 0x3e, 0x75,
	0x49, 0x97, 0x44, 0x5e, 0xfb, 0x70, 0x8d, 0xf4, 0xa3, 0x03, 0xb2, 0xd6, 0x76, 0x09, 0x23, 0x07,
	0x83, 0xfd, 0x76, 0x42, 0xe3, 0x43, 0x1a, 0x5b, 0x51, 0x1c, 0xb2, 0x10, 0x5f, 0x73, 0xc2, 0x80,
	0x11, 0x2f, 0xa0, 0x71, 0xd2, 0x25, 0x9e, 0x25, 0x0c, 0xad, 0xdc, 0xc8, 0x12, 0x46, 0xc6, 0xa5,
	0x5e, 0x18, 0xf6, 0xfa, 0xb4, 0x1d, 0x47, 0x4e, 0x3b, 0x61, 0x84, 0x0d, 0x12, 0xee, 0xc0, 0x58,
	0x11, 0x2f, 0xb2, 0x5f, 0xfb, 0x83, 0xcf, 0xda, 0xd4, 0x8f, 0xd8, 0x91, 0x78, 0x79, 0xf3, 0x44,
	0x20, 0x3e, 0x65, 0x24, 0x7d, 0x16, 0x87, 0x6f, 0x9c, 0x78, 0x38, 0x8a, 0xa9, 0xeb, 0x39, 0x4c,
	0x9c, 0xbd, 0x3e, 0xce, 0x71, 0xec, 0x39, 0xb5, 0x30, 0xc4, 0x34, 0x09, 0x07, 0xb1, 0x43, 0xc5,
	0xe1, 0xb5, 0x31, 0x87, 0x9d, 0xd0, 0xf7, 0x69, 0xe0, 0x12, 0xe6, 0x85, 0x81, 0x30, 0x59, 0x3d,
	0x99, 0x6c, 0x27, 0x8c, 0x85, 0x73, 0xf3, 0x1f, 0x04, 0x17, 0x1e, 0x78, 0x09, 0xdb, 0x09, 0xdd,
	0x87, 0x19, 0xc2, 0xc4, 0xa6, 0x8f, 0x06, 0x34, 0x61, 0xb8, 0x0b, 0x8b, 0x01, 0xf1, 0x69, 0x12,
	0x11, 0x87, 0xba, 0xdd, 0xf4, 0x71, 0x19, 0x5d, 0x45, 0xab, 0x0b, 0xeb, 0xb7, 0xac, 0x7a, 0xf5,
	0xb1, 0xb6, 0xa5, 0x79, 0xfa, 0x64, 0xb7, 0x82, 0xc2, 0x6f, 0xbc, 0x03, 0xc0, 0x3c, 0x9f, 0x76,
	0x63, 0x12, 0xf4, 0xe8, 0xf2, 0xe9, 0xcc, 0xf7, 0x5a, 0x5d, 0xdf, 0xbb, 0x9e, 0x4f, 0xed, 0xd4,
	0xd0, 0x9e, 0x67, 0xf9, 0xa3, 0xf9, 0x33, 0x82, 0x8b, 0xc7, 0x93, 0x49, 0xa2, 0x30, 0x48, 0x28,
	0xbe, 0x01, 0x73, 0xbc, 0x45, 0x44, 0x12, 0xd8, 0xe2, 0x3d, 0x62, 0xc5, 0x91, 0x63, 0x75, 0xb2,
	0x37, 0xb6, 0x38, 0x81, 0x6d, 0x58, 0x88, 0x42, 0xb7, 0xcb, 0x2b, 0x96, 0x2c, 0x9f, 0xbe, 0x7a,
	0x46, 0x07, 0x99, 0x0c, 0x6e, 0x43, 0x24, 0x71, 0x98, 0xdf, 0x09, 0x68, 0xdb, 0xa1, 0x4b, 0x8f,
	0x11, 0x7d, 0x05, 0x20, 0x08, 0x5d, 0x9a, 0x51, 0x9c, 0xc2, 0x3b, 0xb3, 0x3a, 0x6f, 0xcf, 0xa7,
	0x7f, 0xc9, 0xf8, 0x9b, 0x01, 0x4d, 0xbf, 0x20, 0xb8, 0x54, 0xc2, 0xd2, 0x80, 0xa7, 0x8f, 0xe1,
	0x6c, 0x06, 0xbc, 0x48, 0xd4, 0x7a, 0xed, 0xf6, 0x90, 0xe1, 0xed, 0x85, 0x60, 0x08, 0xc5, 0xfc,
	0x1a, 0xce, 0x89, 0x22, 0x36, 0x83, 0x75, 0x17, 0x5e, 0x88, 0x42, 0x37, 0x87, 0x73, 0x53, 0xa3,
	0x6e, 0x76, 0x66, 0x68, 0x7e, 0xc1, 0x4b, 0x75, 0x8f, 0x9f, 0xe4, 0x38, 0x78, 0xa9, 0xf6, 0xa0,
	0x95, 0xdf, 0xac, 0xc4, 0x21, 0x7d, 0x1a, 0x4f, 0x78, 0x25, 0x5e, 0x16, 0x07, 0x3b, 0x99, 0x33,
	0xf3, 0x09, 0x82, 0xa5, 0xbc, 0x30, 0xcd, 0x72, 0xdf, 0x80, 0x17, 0x53, 0x2a, 0xf3, 0xe4, 0xdf,
	0xd2, 0xa9, 0x85, 0xcd, 0x4d, 0xcd, 0x7f, 0x11, 0x5c, 0x16, 0x05, 0xd8, 0xe1, 0x03, 0xce, 0x0b,
	0x83, 0xe7, 0x79, 0x2c, 0xfc, 0x8e, 0xc0, 0x50, 0x25, 0xd4, 0x80, 0xdf, 0x4f, 0x61, 0x31, 0x1d,
	0x0d, 0xd1, 0xd0, 0x8d, 0x60, 0xfa, 0x1d, 0x8d, 0x36, 0x1b, 0x82, 0xb0, 0x5b, 0x51, 0x01, 0x93,
	0xf9, 0xbd, 0x80, 0x9a, 0xd6, 0x43, 0x41, 0xfe, 0x0a, 0xcc, 0xcb, 0x51, 0x21, 0x26, 0xc5, 0x4b,
	0xf9, 0xa4, 0x98, 0x01, 0x71, 0x7f, 0x22, 0x58, 0x51, 0xa2, 0x69, 0xc0, 0x1c, 0x81, 0x73, 0x19,
	0xf4, 0x32, 0x75, 0xb7, 0x74, 0x9a, 0x74, 0x84, 0xbb, 0xc5, 0xa0, 0x08, 0xcb, 0xfc, 0x0f, 0xc1,
	0x15, 0x51, 0x67, 0xbb, 0xb0, 0x15, 0x9f, 0xe7, 0xe6, 0xfd, 0x0b, 0xc1, 0x6b, 0x55, 0x49, 0x35,
	0x28, 0xc3, 0xe7, 0x70, 0x3e, 0x6d, 0xe0, 0xa2, 0x6a, 0xc8, 0x2b, 0x71, 0x47, 0x67, 0x56, 0x16,
	0x3c, 0xd8, 0x38, 0x2a, 0xe1, 0x33, 0x6f, 0xcb, 0x39, 0x92, 0x6c, 0x1c, 0x6d, 0x8b, 0x36, 0xad,
	0xd3, 0xca, 0xe6, 0x97, 0xf0, 0x46, 0x6a, 0xd9, 0xf1, 0xfc, 0x41, 0x9f, 0x30, 0xea, 0x76, 0x9c,
	0x03, 0xea, 0x0e, 0xfa, 0x5e, 0xd0, 0xeb, 0xa4, 0xda, 0x45, 0xd6, 0xb3, 0x48, 0x37, 0x9a, 0x02,
	0xdd, 0x8f, 0x11, 0xbc, 0x39, 0x26, 0xb4, 0x60, 0xfd, 0x13, 0x98, 0xcb, 0x84, 0x14, 0x5f, 0xd9,
	0x0b, 0xeb, 0xef, 0xd7, 0x8d, 0x5b, 0xe5, 0xda, 0x16, 0xfe, 0xcc, 0xaf, 0x60, 0x65, 0x33, 0xa6,
	0x84, 0x51, 0xf5, 0x04, 0x56, 0xcc, 0x20, 0x34, 0xcd, 0x19, 0xf4, 0x18, 0xc1, 0xab, 0x3c, 0x7e,
	0xc5, 0x14, 0x52, 0x5d, 0x65, 0x34, 0xdd, 0xab, 0xfc, 0x14, 0xc1, 0xeb, 0x92, 0x83, 0x8a, 0xcb,
	0x5c, 0xd1, 0xca, 0x68, 0x16, 0xad, 0xbc, 0x0b, 0x4b, 0x12, 0x8e, 0x04, 0x90, 0x0b, 0x0d, 0xd4,
	0x54, 0x68, 0x04, 0x70, 0x99, 0x7b, 0x15, 0x52, 0x43, 0xec, 0x7d, 0xee, 0xfd, 0x23, 0xc8, 0xd5,
	0x41, 0x97, 0xaf, 0x74, 0xd4, 0x60, 0xa5, 0x9f, 0x25, 0x23, 0x9e, 0xcd, 0x6f, 0x10, 0x5c, 0xe3,
	0x01, 0xc7, 0xde, 0xac, 0xd9, 0x75, 0xf7, 0x2e, 0x2c, 0x6d, 0xd1, 0x3e, 0x9d, 0x3e, 0x95, 0xdc,
	0xeb, 0xb3, 0xa1, 0x72, 0xfd, 0x09, 0x86, 0xd6, 0x16, 0x7f, 0xdd, 0xa1, 0xf1, 0xa1, 0xe7, 0x50,
	0xfc, 0x03, 0x82, 0x56, 0xf1, 0xeb, 0x03, 0xbf, 0x5b, 0x37, 0x82, 0xf2, 0x13, 0xcc, 0x78, 0xaf,
	0xa9, 0x39, 0x1f, 0x51, 0xe6, 0x29, 0xfc, 0x13, 0x82, 0xc5, 0x63, 0x52, 0x1f, 0x6b, 0x79, 0x2d,
	0x7f, 0xaf, 0x18, 0x77, 0x1b, 0xdb, 0x4b, 0x58, 0x4f, 0x05, 0xac, 0x11, 0x89, 0xad, 0x07, 0xab,
	0xac, 0xcd, 0x8d, 0xdb, 0x9a, 0x64, 0x8d, 0xe2, 0xe9, 0xf1, 0x4f, 0x8e, 0xd1, 0xde, 0xc1, 0x17,
	0xf3, 0x2d, 0x9a, 0xff, 0x17, 0xc1, 0xba, 0xef, 0x47, 0xec, 0xc8, 0xb8, 0xa3, 0x9b, 0xfe, 0x68,
	0xa0, 0x5f, 0x11, 0xe0, 0xb2, 0x14, 0xc5, 0xf7, 0x34, 0xb1, 0x97, 0x87, 0xb2, 0xb1, 0x31, 0x89,
	0x0b, 0x89, 0xef, 0x37, 0x04, 0xe7, 0x15, 0x8a, 0x0f, 0x6f, 0xe8, 0x26, 0xad, 0x40, 0xb8, 0x39,
	0x91, 0x0f, 0x09, 0xf1, 0x8f, 0xe1, 0x47, 0xfe, 0xb1, 0x29, 0x8d, 0xef, 0x6b, 0x72, 0xa0, 0x5e,
	0x2c, 0xc6, 0x07, 0x93, 0xba, 0x91, 0x58, 0x7f, 0x1c, 0x96, 0x7b, 0x44, 0x02, 0x69, 0x97, 0xbb,
	0x2c, 0x9f, 0x26, 0xea, 0xf6, 0xbf, 0x85, 0x4e, 0xae, 0x5c, 0x02, 0xf8, 0x81, 0x8e, 0xf7, 0x71,
	0xbb, 0xc4, 0x78, 0x38, 0x25, 0x6f, 0x32, 0x81, 0x3d, 0x80, 0xe1, 0x36, 0xc6, 0xb5, 0x2f, 0x64,
	0x69, 0x83, 0x1b, 0x0a, 0xa5, 0x6c, 0x9e, 0xc2, 0x3e, 0xe0, 0xf2, 0x5a, 0xae, 0x5f, 0xb4, 0xca,
	0x95, 0x5e, 0x11, 0xee, 0x11, 0xbc, 0xa2, 0x92, 0x7b, 0x78, 0x53, 0x3b, 0x2f, 0xc5, 0xa5, 0x53,
	0x87, 0x4c, 0xe0, 0x82, 0x52, 0xe1, 0xe1, 0x2d, 0xbd, 0x98, 0x15, 0x37, 0x5d, 0x1d, 0xf4, 0x08,
	0x96, 0xab, 0x24, 0x1d, 0xfe, 0x50, 0x3b, 0xd7, 0x8a, 0xbb, 0xab, 0x0e, 0xfd, 0xad, 0x94, 0x93,
	0xd5, 0x3d, 0xbf, 0xad, 0x07, 0x61, 0x6c, 0xd7, 0xab, 0x91, 0xec, 0x01, 0x0c, 0xd5, 0x4f, 0xfd,
	0xd6, 0x2d, 0x29, 0xa6, 0xea, 0xd6, 0x2d, 0xcb, 0xa0, 0xfa, 0xad, 0x5b, 0x29, 0xa1, 0xd4, 0xe1,
	0xf6, 0xe7, 0xb2, 0xdd, 0xf8, 0xf6, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x0d, 0x1d, 0xef,
	0xdd, 0x17, 0x00, 0x00,
}
