// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alameda_api/v1alpha1/datahub/resources/resources.proto

package resources

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Represents a container and its containing limit and requeset configurations
type Container struct {
	ObjectMeta           *ObjectMeta           `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Resources            *ResourceRequirements `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	Status               *ContainerStatus      `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_b42f420f5e5b9311, []int{0}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetObjectMeta() *ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *Container) GetResources() *ResourceRequirements {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Container) GetStatus() *ContainerStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// Represents a Kubernetes pod
type Pod struct {
	ObjectMeta           *ObjectMeta          `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	ResourceLink         string               `protobuf:"bytes,2,opt,name=resource_link,json=resourceLink,proto3" json:"resource_link,omitempty"`
	Containers           []*Container         `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	IsAlameda            bool                 `protobuf:"varint,4,opt,name=is_alameda,json=isAlameda,proto3" json:"is_alameda,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	TopController        *Controller          `protobuf:"bytes,6,opt,name=top_controller,json=topController,proto3" json:"top_controller,omitempty"`
	Status               *PodStatus           `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	AppName              string               `protobuf:"bytes,8,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppPartOf            string               `protobuf:"bytes,9,opt,name=app_part_of,json=appPartOf,proto3" json:"app_part_of,omitempty"`
	AlamedaPodSpec       *AlamedaPodSpec      `protobuf:"bytes,10,opt,name=alameda_pod_spec,json=alamedaPodSpec,proto3" json:"alameda_pod_spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Pod) Reset()         { *m = Pod{} }
func (m *Pod) String() string { return proto.CompactTextString(m) }
func (*Pod) ProtoMessage()    {}
func (*Pod) Descriptor() ([]byte, []int) {
	return fileDescriptor_b42f420f5e5b9311, []int{1}
}

func (m *Pod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pod.Unmarshal(m, b)
}
func (m *Pod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pod.Marshal(b, m, deterministic)
}
func (m *Pod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pod.Merge(m, src)
}
func (m *Pod) XXX_Size() int {
	return xxx_messageInfo_Pod.Size(m)
}
func (m *Pod) XXX_DiscardUnknown() {
	xxx_messageInfo_Pod.DiscardUnknown(m)
}

var xxx_messageInfo_Pod proto.InternalMessageInfo

func (m *Pod) GetObjectMeta() *ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *Pod) GetResourceLink() string {
	if m != nil {
		return m.ResourceLink
	}
	return ""
}

func (m *Pod) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Pod) GetIsAlameda() bool {
	if m != nil {
		return m.IsAlameda
	}
	return false
}

func (m *Pod) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Pod) GetTopController() *Controller {
	if m != nil {
		return m.TopController
	}
	return nil
}

func (m *Pod) GetStatus() *PodStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Pod) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *Pod) GetAppPartOf() string {
	if m != nil {
		return m.AppPartOf
	}
	return ""
}

func (m *Pod) GetAlamedaPodSpec() *AlamedaPodSpec {
	if m != nil {
		return m.AlamedaPodSpec
	}
	return nil
}

type Controller struct {
	ObjectMeta            *ObjectMeta            `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Kind                  Kind                   `protobuf:"varint,2,opt,name=kind,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.Kind" json:"kind,omitempty"`
	OwnerReferences       []*OwnerReference      `protobuf:"bytes,3,rep,name=owner_references,json=ownerReferences,proto3" json:"owner_references,omitempty"`
	Replicas              int32                  `protobuf:"varint,4,opt,name=replicas,proto3" json:"replicas,omitempty"`
	SpecReplicas          int32                  `protobuf:"varint,5,opt,name=spec_replicas,json=specReplicas,proto3" json:"spec_replicas,omitempty"`
	AlamedaControllerSpec *AlamedaControllerSpec `protobuf:"bytes,6,opt,name=alameda_controller_spec,json=alamedaControllerSpec,proto3" json:"alameda_controller_spec,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *Controller) Reset()         { *m = Controller{} }
func (m *Controller) String() string { return proto.CompactTextString(m) }
func (*Controller) ProtoMessage()    {}
func (*Controller) Descriptor() ([]byte, []int) {
	return fileDescriptor_b42f420f5e5b9311, []int{2}
}

func (m *Controller) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Controller.Unmarshal(m, b)
}
func (m *Controller) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Controller.Marshal(b, m, deterministic)
}
func (m *Controller) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Controller.Merge(m, src)
}
func (m *Controller) XXX_Size() int {
	return xxx_messageInfo_Controller.Size(m)
}
func (m *Controller) XXX_DiscardUnknown() {
	xxx_messageInfo_Controller.DiscardUnknown(m)
}

var xxx_messageInfo_Controller proto.InternalMessageInfo

func (m *Controller) GetObjectMeta() *ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *Controller) GetKind() Kind {
	if m != nil {
		return m.Kind
	}
	return Kind_POD
}

func (m *Controller) GetOwnerReferences() []*OwnerReference {
	if m != nil {
		return m.OwnerReferences
	}
	return nil
}

func (m *Controller) GetReplicas() int32 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func (m *Controller) GetSpecReplicas() int32 {
	if m != nil {
		return m.SpecReplicas
	}
	return 0
}

func (m *Controller) GetAlamedaControllerSpec() *AlamedaControllerSpec {
	if m != nil {
		return m.AlamedaControllerSpec
	}
	return nil
}

type Application struct {
	ObjectMeta           *ObjectMeta `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_b42f420f5e5b9311, []int{3}
}

func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetObjectMeta() *ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

type Namespace struct {
	ObjectMeta           *ObjectMeta `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Namespace) Reset()         { *m = Namespace{} }
func (m *Namespace) String() string { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()    {}
func (*Namespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_b42f420f5e5b9311, []int{4}
}

func (m *Namespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Namespace.Unmarshal(m, b)
}
func (m *Namespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Namespace.Marshal(b, m, deterministic)
}
func (m *Namespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Namespace.Merge(m, src)
}
func (m *Namespace) XXX_Size() int {
	return xxx_messageInfo_Namespace.Size(m)
}
func (m *Namespace) XXX_DiscardUnknown() {
	xxx_messageInfo_Namespace.DiscardUnknown(m)
}

var xxx_messageInfo_Namespace proto.InternalMessageInfo

func (m *Namespace) GetObjectMeta() *ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

// Represents a Kubernetes node
type Node struct {
	ObjectMeta           *ObjectMeta          `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Capacity             *Capacity            `protobuf:"bytes,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	AlamedaNodeSpcec     *AlamedaNodeSpec     `protobuf:"bytes,4,opt,name=alameda_node_spcec,json=alamedaNodeSpcec,proto3" json:"alameda_node_spcec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_b42f420f5e5b9311, []int{5}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetObjectMeta() *ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *Node) GetCapacity() *Capacity {
	if m != nil {
		return m.Capacity
	}
	return nil
}

func (m *Node) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Node) GetAlamedaNodeSpcec() *AlamedaNodeSpec {
	if m != nil {
		return m.AlamedaNodeSpcec
	}
	return nil
}

type Cluster struct {
	ObjectMeta           *ObjectMeta `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_b42f420f5e5b9311, []int{6}
}

func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (m *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(m, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetObjectMeta() *ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func init() {
	proto.RegisterType((*Container)(nil), "containersai.alameda.v1alpha1.datahub.resources.Container")
	proto.RegisterType((*Pod)(nil), "containersai.alameda.v1alpha1.datahub.resources.Pod")
	proto.RegisterType((*Controller)(nil), "containersai.alameda.v1alpha1.datahub.resources.Controller")
	proto.RegisterType((*Application)(nil), "containersai.alameda.v1alpha1.datahub.resources.Application")
	proto.RegisterType((*Namespace)(nil), "containersai.alameda.v1alpha1.datahub.resources.Namespace")
	proto.RegisterType((*Node)(nil), "containersai.alameda.v1alpha1.datahub.resources.Node")
	proto.RegisterType((*Cluster)(nil), "containersai.alameda.v1alpha1.datahub.resources.Cluster")
}

func init() {
	proto.RegisterFile("alameda_api/v1alpha1/datahub/resources/resources.proto", fileDescriptor_b42f420f5e5b9311)
}

var fileDescriptor_b42f420f5e5b9311 = []byte{
	// 699 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xd6, 0xd6, 0x75, 0x6b, 0x4e, 0xb7, 0x31, 0x59, 0x42, 0x84, 0x4a, 0xc0, 0x54, 0x6e, 0x76,
	0x43, 0xaa, 0x75, 0x1a, 0xd2, 0xe0, 0x02, 0x46, 0x35, 0x24, 0x04, 0x6c, 0x93, 0x01, 0x09, 0x4d,
	0x48, 0xd1, 0xa9, 0xe3, 0x76, 0x5e, 0x93, 0xd8, 0xc4, 0x2e, 0x68, 0x37, 0x3c, 0x09, 0x0f, 0xc0,
	0x73, 0x71, 0xc1, 0x73, 0x20, 0x3b, 0x3f, 0xdd, 0x10, 0x17, 0x4d, 0xa5, 0xde, 0xc5, 0x27, 0xc7,
	0xdf, 0x39, 0xfe, 0xbe, 0x2f, 0x27, 0x86, 0xa7, 0x18, 0x63, 0xc2, 0x23, 0x0c, 0x51, 0x89, 0xde,
	0xb7, 0x7d, 0x8c, 0xd5, 0x25, 0xee, 0xf7, 0x22, 0x34, 0x78, 0x39, 0x1d, 0xf6, 0x32, 0xae, 0xe5,
	0x34, 0x63, 0x5c, 0xcf, 0x9e, 0x02, 0x95, 0x49, 0x23, 0x49, 0x8f, 0xc9, 0xd4, 0xa0, 0x48, 0x79,
	0xa6, 0x51, 0x04, 0x05, 0x48, 0x50, 0x02, 0x04, 0x05, 0x40, 0x50, 0x6d, 0xeb, 0x1c, 0xce, 0x59,
	0x28, 0xe1, 0x06, 0x6d, 0x34, 0xaf, 0xd3, 0x39, 0x98, 0x73, 0x9b, 0x36, 0x68, 0xa6, 0x45, 0x73,
	0x9d, 0xfe, 0x9c, 0x9b, 0xcc, 0xb5, 0x2a, 0x0f, 0xd4, 0x79, 0x34, 0x96, 0x72, 0x1c, 0xf3, 0x9e,
	0x5b, 0x0d, 0xa7, 0xa3, 0x9e, 0x11, 0x09, 0xd7, 0x06, 0x13, 0x95, 0x27, 0x74, 0x7f, 0xad, 0x82,
	0x37, 0x28, 0x0f, 0x4d, 0xbe, 0x40, 0x5b, 0x0e, 0xaf, 0x38, 0x33, 0xa1, 0x6d, 0xd8, 0x5f, 0xd9,
	0x5d, 0xd9, 0x6b, 0xf7, 0x9f, 0x07, 0x35, 0x59, 0x09, 0xce, 0x1c, 0xc6, 0x7b, 0x6e, 0x90, 0x82,
	0xac, 0x9e, 0x09, 0x03, 0xaf, 0xca, 0xf1, 0x57, 0x1d, 0xf6, 0x49, 0x6d, 0x6c, 0x5a, 0x3c, 0x51,
	0xfe, 0x75, 0x2a, 0x32, 0x9e, 0xf0, 0xd4, 0x68, 0x3a, 0xc3, 0x25, 0x9f, 0x61, 0x3d, 0x67, 0xcd,
	0x6f, 0xb8, 0x0a, 0x2f, 0x6b, 0x57, 0xa8, 0xe8, 0xf8, 0xe0, 0x70, 0x68, 0x81, 0xd7, 0xfd, 0xd9,
	0x84, 0xc6, 0xb9, 0x8c, 0x96, 0x4c, 0xd2, 0x63, 0xd8, 0x2a, 0x73, 0xc2, 0x58, 0xa4, 0x13, 0x47,
	0x94, 0x47, 0x37, 0xcb, 0xe0, 0x3b, 0x91, 0x4e, 0xc8, 0x05, 0xc0, 0xac, 0x9c, 0xdf, 0xd8, 0x6d,
	0xec, 0xb5, 0xfb, 0xcf, 0x16, 0x3f, 0x28, 0xbd, 0x81, 0x46, 0x1e, 0x00, 0x08, 0x1d, 0x16, 0xdb,
	0xfd, 0xb5, 0xdd, 0x95, 0xbd, 0x16, 0xf5, 0x84, 0x3e, 0xce, 0x03, 0xe4, 0x08, 0x40, 0x1b, 0xcc,
	0x4c, 0x68, 0x9d, 0xe4, 0x37, 0xdd, 0xe1, 0x3b, 0x41, 0x6e, 0xb3, 0xa0, 0xb4, 0x59, 0xf0, 0xb1,
	0xb4, 0x19, 0xf5, 0x5c, 0xb6, 0x5d, 0x93, 0x21, 0x6c, 0x1b, 0xa9, 0x42, 0x5b, 0x2b, 0x93, 0x71,
	0xcc, 0x33, 0x7f, 0x7d, 0x41, 0xee, 0x06, 0x15, 0x04, 0xdd, 0x32, 0x52, 0xcd, 0x96, 0x84, 0x56,
	0xf2, 0x6f, 0x38, 0xec, 0xfa, 0xac, 0x9c, 0xcb, 0xe8, 0xb6, 0xf0, 0xe4, 0x3e, 0xb4, 0x50, 0xa9,
	0x30, 0xc5, 0x84, 0xfb, 0x2d, 0xa7, 0xc6, 0x06, 0x2a, 0x75, 0x8a, 0x09, 0x27, 0x0f, 0xa1, 0x6d,
	0x5f, 0x29, 0x4b, 0x88, 0x1c, 0xf9, 0x9e, 0x7b, 0xeb, 0xa1, 0x52, 0xe7, 0x98, 0x99, 0xb3, 0x11,
	0x11, 0xb0, 0x53, 0x7e, 0xb5, 0x4a, 0x46, 0xa1, 0x56, 0x9c, 0xf9, 0xe0, 0x1a, 0x7b, 0x51, 0xbb,
	0xb1, 0x42, 0x01, 0xdb, 0x9f, 0xe2, 0x8c, 0x6e, 0xe3, 0xad, 0x75, 0xf7, 0x77, 0x03, 0xe0, 0x06,
	0x11, 0xcb, 0x75, 0xe9, 0x1b, 0x58, 0x9b, 0x88, 0x34, 0x72, 0xe6, 0xdc, 0xee, 0x1f, 0xd6, 0x86,
	0x7d, 0x2b, 0xd2, 0x88, 0x3a, 0x08, 0x72, 0x05, 0x3b, 0xf2, 0x7b, 0xca, 0xb3, 0x30, 0xe3, 0x23,
	0x9e, 0xf1, 0xd4, 0x0e, 0x87, 0xdc, 0xd1, 0xf5, 0x29, 0x3a, 0xb3, 0x40, 0xb4, 0xc4, 0xa1, 0x77,
	0xe4, 0xad, 0xb5, 0x26, 0x1d, 0x68, 0x65, 0x5c, 0xc5, 0x82, 0xa1, 0x76, 0xce, 0x6e, 0xd2, 0x6a,
	0x6d, 0x3f, 0x3c, 0x2b, 0x4f, 0x58, 0x25, 0x34, 0x5d, 0xc2, 0xa6, 0x0d, 0xd2, 0x32, 0xe9, 0x07,
	0xdc, 0x2b, 0xf5, 0x9c, 0xd9, 0x38, 0x97, 0x35, 0xf7, 0xf2, 0xeb, 0x45, 0x65, 0x9d, 0x49, 0xe7,
	0xd4, 0xbd, 0x8b, 0xff, 0x0b, 0x77, 0x27, 0xd0, 0x3e, 0x56, 0xae, 0x17, 0x23, 0x64, 0xba, 0x5c,
	0x91, 0xbb, 0x02, 0x3c, 0x6b, 0x72, 0xad, 0x90, 0xf1, 0x25, 0x97, 0xfa, 0xb3, 0x0a, 0x6b, 0xa7,
	0x32, 0x5a, 0x72, 0x19, 0xf2, 0x09, 0x5a, 0x0c, 0x15, 0x32, 0x61, 0xae, 0x8b, 0x1f, 0xd0, 0x51,
	0xfd, 0xd9, 0x53, 0x00, 0xd0, 0x0a, 0xea, 0x9f, 0x99, 0xd8, 0xa8, 0x33, 0x13, 0x53, 0x20, 0xa5,
	0xa1, 0x52, 0x19, 0xf1, 0x50, 0x2b, 0xc6, 0x99, 0xf3, 0xe6, 0x22, 0xbf, 0xae, 0xc2, 0x4b, 0x96,
	0x49, 0xe7, 0xa2, 0x72, 0xf8, 0xe4, 0x01, 0xc6, 0x59, 0x77, 0x0c, 0x1b, 0x83, 0x78, 0xaa, 0xcd,
	0xb2, 0x27, 0xc4, 0xab, 0x93, 0x8b, 0xc1, 0x58, 0x18, 0x9b, 0xca, 0x64, 0x72, 0xe3, 0x5e, 0xf5,
	0x04, 0x45, 0xcf, 0x5e, 0x60, 0xe6, 0xbb, 0xcc, 0x0c, 0xd7, 0x1d, 0x7d, 0x07, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x66, 0x45, 0xbd, 0x3f, 0xd2, 0x09, 0x00, 0x00,
}
