// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alameda_api/v1alpha1/datahub/resources/services.proto

package resources

import (
	fmt "fmt"
	common "github.com/containers-ai/api/alameda_api/v1alpha1/datahub/common"
	proto "github.com/golang/protobuf/proto"
	status "google.golang.org/genproto/googleapis/rpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Represents a request for creating pods
type CreatePodsRequest struct {
	Pods                 []*Pod   `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePodsRequest) Reset()         { *m = CreatePodsRequest{} }
func (m *CreatePodsRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePodsRequest) ProtoMessage()    {}
func (*CreatePodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{0}
}

func (m *CreatePodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePodsRequest.Unmarshal(m, b)
}
func (m *CreatePodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePodsRequest.Marshal(b, m, deterministic)
}
func (m *CreatePodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePodsRequest.Merge(m, src)
}
func (m *CreatePodsRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePodsRequest.Size(m)
}
func (m *CreatePodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePodsRequest proto.InternalMessageInfo

func (m *CreatePodsRequest) GetPods() []*Pod {
	if m != nil {
		return m.Pods
	}
	return nil
}

type CreateControllersRequest struct {
	Controllers          []*Controller `protobuf:"bytes,1,rep,name=controllers,proto3" json:"controllers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateControllersRequest) Reset()         { *m = CreateControllersRequest{} }
func (m *CreateControllersRequest) String() string { return proto.CompactTextString(m) }
func (*CreateControllersRequest) ProtoMessage()    {}
func (*CreateControllersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{1}
}

func (m *CreateControllersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateControllersRequest.Unmarshal(m, b)
}
func (m *CreateControllersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateControllersRequest.Marshal(b, m, deterministic)
}
func (m *CreateControllersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateControllersRequest.Merge(m, src)
}
func (m *CreateControllersRequest) XXX_Size() int {
	return xxx_messageInfo_CreateControllersRequest.Size(m)
}
func (m *CreateControllersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateControllersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateControllersRequest proto.InternalMessageInfo

func (m *CreateControllersRequest) GetControllers() []*Controller {
	if m != nil {
		return m.Controllers
	}
	return nil
}

type CreateApplicationsRequest struct {
	Applications         []*Application `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateApplicationsRequest) Reset()         { *m = CreateApplicationsRequest{} }
func (m *CreateApplicationsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateApplicationsRequest) ProtoMessage()    {}
func (*CreateApplicationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{2}
}

func (m *CreateApplicationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateApplicationsRequest.Unmarshal(m, b)
}
func (m *CreateApplicationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateApplicationsRequest.Marshal(b, m, deterministic)
}
func (m *CreateApplicationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateApplicationsRequest.Merge(m, src)
}
func (m *CreateApplicationsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateApplicationsRequest.Size(m)
}
func (m *CreateApplicationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateApplicationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateApplicationsRequest proto.InternalMessageInfo

func (m *CreateApplicationsRequest) GetApplications() []*Application {
	if m != nil {
		return m.Applications
	}
	return nil
}

type CreateNamespacesRequest struct {
	Namespaces           []*Namespace `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateNamespacesRequest) Reset()         { *m = CreateNamespacesRequest{} }
func (m *CreateNamespacesRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNamespacesRequest) ProtoMessage()    {}
func (*CreateNamespacesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{3}
}

func (m *CreateNamespacesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespacesRequest.Unmarshal(m, b)
}
func (m *CreateNamespacesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespacesRequest.Marshal(b, m, deterministic)
}
func (m *CreateNamespacesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespacesRequest.Merge(m, src)
}
func (m *CreateNamespacesRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNamespacesRequest.Size(m)
}
func (m *CreateNamespacesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespacesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespacesRequest proto.InternalMessageInfo

func (m *CreateNamespacesRequest) GetNamespaces() []*Namespace {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

// Represents a request for adding nodes that need to be predicted
type CreateNodesRequest struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNodesRequest) Reset()         { *m = CreateNodesRequest{} }
func (m *CreateNodesRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNodesRequest) ProtoMessage()    {}
func (*CreateNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{4}
}

func (m *CreateNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNodesRequest.Unmarshal(m, b)
}
func (m *CreateNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNodesRequest.Marshal(b, m, deterministic)
}
func (m *CreateNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNodesRequest.Merge(m, src)
}
func (m *CreateNodesRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNodesRequest.Size(m)
}
func (m *CreateNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNodesRequest proto.InternalMessageInfo

func (m *CreateNodesRequest) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type CreateClustersRequest struct {
	Clusters             []*Cluster `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateClustersRequest) Reset()         { *m = CreateClustersRequest{} }
func (m *CreateClustersRequest) String() string { return proto.CompactTextString(m) }
func (*CreateClustersRequest) ProtoMessage()    {}
func (*CreateClustersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{5}
}

func (m *CreateClustersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClustersRequest.Unmarshal(m, b)
}
func (m *CreateClustersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClustersRequest.Marshal(b, m, deterministic)
}
func (m *CreateClustersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClustersRequest.Merge(m, src)
}
func (m *CreateClustersRequest) XXX_Size() int {
	return xxx_messageInfo_CreateClustersRequest.Size(m)
}
func (m *CreateClustersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClustersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClustersRequest proto.InternalMessageInfo

func (m *CreateClustersRequest) GetClusters() []*Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

// Represents a request for listing pods that need to be predicted
type ListPodsRequest struct {
	TimeRange            *common.TimeRange `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	ObjectMeta           []*ObjectMeta     `protobuf:"bytes,2,rep,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Kind                 Kind              `protobuf:"varint,3,opt,name=kind,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.Kind" json:"kind,omitempty"`
	ScalingTool          ScalingTool       `protobuf:"varint,4,opt,name=scaling_tool,json=scalingTool,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.ScalingTool" json:"scaling_tool,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListPodsRequest) Reset()         { *m = ListPodsRequest{} }
func (m *ListPodsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPodsRequest) ProtoMessage()    {}
func (*ListPodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{6}
}

func (m *ListPodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodsRequest.Unmarshal(m, b)
}
func (m *ListPodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodsRequest.Marshal(b, m, deterministic)
}
func (m *ListPodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodsRequest.Merge(m, src)
}
func (m *ListPodsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPodsRequest.Size(m)
}
func (m *ListPodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodsRequest proto.InternalMessageInfo

func (m *ListPodsRequest) GetTimeRange() *common.TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *ListPodsRequest) GetObjectMeta() []*ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *ListPodsRequest) GetKind() Kind {
	if m != nil {
		return m.Kind
	}
	return Kind_POD
}

func (m *ListPodsRequest) GetScalingTool() ScalingTool {
	if m != nil {
		return m.ScalingTool
	}
	return ScalingTool_SCALING_TOOL_UNDEFINED
}

// Represents a response for a listing pods request
type ListPodsResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Pods                 []*Pod         `protobuf:"bytes,2,rep,name=pods,proto3" json:"pods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListPodsResponse) Reset()         { *m = ListPodsResponse{} }
func (m *ListPodsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPodsResponse) ProtoMessage()    {}
func (*ListPodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{7}
}

func (m *ListPodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodsResponse.Unmarshal(m, b)
}
func (m *ListPodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodsResponse.Marshal(b, m, deterministic)
}
func (m *ListPodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodsResponse.Merge(m, src)
}
func (m *ListPodsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPodsResponse.Size(m)
}
func (m *ListPodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodsResponse proto.InternalMessageInfo

func (m *ListPodsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListPodsResponse) GetPods() []*Pod {
	if m != nil {
		return m.Pods
	}
	return nil
}

type ListControllersRequest struct {
	QueryCondition       *common.QueryCondition `protobuf:"bytes,1,opt,name=query_condition,json=queryCondition,proto3" json:"query_condition,omitempty"`
	ObjectMeta           []*ObjectMeta          `protobuf:"bytes,2,rep,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Kind                 Kind                   `protobuf:"varint,3,opt,name=kind,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.Kind" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ListControllersRequest) Reset()         { *m = ListControllersRequest{} }
func (m *ListControllersRequest) String() string { return proto.CompactTextString(m) }
func (*ListControllersRequest) ProtoMessage()    {}
func (*ListControllersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{8}
}

func (m *ListControllersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListControllersRequest.Unmarshal(m, b)
}
func (m *ListControllersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListControllersRequest.Marshal(b, m, deterministic)
}
func (m *ListControllersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListControllersRequest.Merge(m, src)
}
func (m *ListControllersRequest) XXX_Size() int {
	return xxx_messageInfo_ListControllersRequest.Size(m)
}
func (m *ListControllersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListControllersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListControllersRequest proto.InternalMessageInfo

func (m *ListControllersRequest) GetQueryCondition() *common.QueryCondition {
	if m != nil {
		return m.QueryCondition
	}
	return nil
}

func (m *ListControllersRequest) GetObjectMeta() []*ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *ListControllersRequest) GetKind() Kind {
	if m != nil {
		return m.Kind
	}
	return Kind_POD
}

type ListControllersResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Controllers          []*Controller  `protobuf:"bytes,2,rep,name=controllers,proto3" json:"controllers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListControllersResponse) Reset()         { *m = ListControllersResponse{} }
func (m *ListControllersResponse) String() string { return proto.CompactTextString(m) }
func (*ListControllersResponse) ProtoMessage()    {}
func (*ListControllersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{9}
}

func (m *ListControllersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListControllersResponse.Unmarshal(m, b)
}
func (m *ListControllersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListControllersResponse.Marshal(b, m, deterministic)
}
func (m *ListControllersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListControllersResponse.Merge(m, src)
}
func (m *ListControllersResponse) XXX_Size() int {
	return xxx_messageInfo_ListControllersResponse.Size(m)
}
func (m *ListControllersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListControllersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListControllersResponse proto.InternalMessageInfo

func (m *ListControllersResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListControllersResponse) GetControllers() []*Controller {
	if m != nil {
		return m.Controllers
	}
	return nil
}

type ListApplicationsRequest struct {
	ObjectMeta           []*ObjectMeta `protobuf:"bytes,1,rep,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListApplicationsRequest) Reset()         { *m = ListApplicationsRequest{} }
func (m *ListApplicationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListApplicationsRequest) ProtoMessage()    {}
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{10}
}

func (m *ListApplicationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationsRequest.Unmarshal(m, b)
}
func (m *ListApplicationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationsRequest.Marshal(b, m, deterministic)
}
func (m *ListApplicationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationsRequest.Merge(m, src)
}
func (m *ListApplicationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListApplicationsRequest.Size(m)
}
func (m *ListApplicationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationsRequest proto.InternalMessageInfo

func (m *ListApplicationsRequest) GetObjectMeta() []*ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

type ListApplicationsResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Applications         []*Application `protobuf:"bytes,2,rep,name=applications,proto3" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListApplicationsResponse) Reset()         { *m = ListApplicationsResponse{} }
func (m *ListApplicationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListApplicationsResponse) ProtoMessage()    {}
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{11}
}

func (m *ListApplicationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationsResponse.Unmarshal(m, b)
}
func (m *ListApplicationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationsResponse.Marshal(b, m, deterministic)
}
func (m *ListApplicationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationsResponse.Merge(m, src)
}
func (m *ListApplicationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListApplicationsResponse.Size(m)
}
func (m *ListApplicationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationsResponse proto.InternalMessageInfo

func (m *ListApplicationsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListApplicationsResponse) GetApplications() []*Application {
	if m != nil {
		return m.Applications
	}
	return nil
}

type ListNamespacesRequest struct {
	ObjectMeta           []*ObjectMeta `protobuf:"bytes,1,rep,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListNamespacesRequest) Reset()         { *m = ListNamespacesRequest{} }
func (m *ListNamespacesRequest) String() string { return proto.CompactTextString(m) }
func (*ListNamespacesRequest) ProtoMessage()    {}
func (*ListNamespacesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{12}
}

func (m *ListNamespacesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNamespacesRequest.Unmarshal(m, b)
}
func (m *ListNamespacesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNamespacesRequest.Marshal(b, m, deterministic)
}
func (m *ListNamespacesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNamespacesRequest.Merge(m, src)
}
func (m *ListNamespacesRequest) XXX_Size() int {
	return xxx_messageInfo_ListNamespacesRequest.Size(m)
}
func (m *ListNamespacesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNamespacesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNamespacesRequest proto.InternalMessageInfo

func (m *ListNamespacesRequest) GetObjectMeta() []*ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

type ListNamespacesResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Namespaces           []*Namespace   `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListNamespacesResponse) Reset()         { *m = ListNamespacesResponse{} }
func (m *ListNamespacesResponse) String() string { return proto.CompactTextString(m) }
func (*ListNamespacesResponse) ProtoMessage()    {}
func (*ListNamespacesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{13}
}

func (m *ListNamespacesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNamespacesResponse.Unmarshal(m, b)
}
func (m *ListNamespacesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNamespacesResponse.Marshal(b, m, deterministic)
}
func (m *ListNamespacesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNamespacesResponse.Merge(m, src)
}
func (m *ListNamespacesResponse) XXX_Size() int {
	return xxx_messageInfo_ListNamespacesResponse.Size(m)
}
func (m *ListNamespacesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNamespacesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNamespacesResponse proto.InternalMessageInfo

func (m *ListNamespacesResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListNamespacesResponse) GetNamespaces() []*Namespace {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

// Represents a request for listing nodes that need to be predicted
type ListNodesRequest struct {
	TimeRange            *common.TimeRange `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	ObjectMeta           []*ObjectMeta     `protobuf:"bytes,2,rep,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListNodesRequest) Reset()         { *m = ListNodesRequest{} }
func (m *ListNodesRequest) String() string { return proto.CompactTextString(m) }
func (*ListNodesRequest) ProtoMessage()    {}
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{14}
}

func (m *ListNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodesRequest.Unmarshal(m, b)
}
func (m *ListNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodesRequest.Marshal(b, m, deterministic)
}
func (m *ListNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodesRequest.Merge(m, src)
}
func (m *ListNodesRequest) XXX_Size() int {
	return xxx_messageInfo_ListNodesRequest.Size(m)
}
func (m *ListNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodesRequest proto.InternalMessageInfo

func (m *ListNodesRequest) GetTimeRange() *common.TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *ListNodesRequest) GetObjectMeta() []*ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

// Represents a response for a listing nodes request
type ListNodesResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Nodes                []*Node        `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListNodesResponse) Reset()         { *m = ListNodesResponse{} }
func (m *ListNodesResponse) String() string { return proto.CompactTextString(m) }
func (*ListNodesResponse) ProtoMessage()    {}
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{15}
}

func (m *ListNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodesResponse.Unmarshal(m, b)
}
func (m *ListNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodesResponse.Marshal(b, m, deterministic)
}
func (m *ListNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodesResponse.Merge(m, src)
}
func (m *ListNodesResponse) XXX_Size() int {
	return xxx_messageInfo_ListNodesResponse.Size(m)
}
func (m *ListNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodesResponse proto.InternalMessageInfo

func (m *ListNodesResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListNodesResponse) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type ListClustersRequest struct {
	ObjectMeta           []*ObjectMeta `protobuf:"bytes,1,rep,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListClustersRequest) Reset()         { *m = ListClustersRequest{} }
func (m *ListClustersRequest) String() string { return proto.CompactTextString(m) }
func (*ListClustersRequest) ProtoMessage()    {}
func (*ListClustersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{16}
}

func (m *ListClustersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClustersRequest.Unmarshal(m, b)
}
func (m *ListClustersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClustersRequest.Marshal(b, m, deterministic)
}
func (m *ListClustersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClustersRequest.Merge(m, src)
}
func (m *ListClustersRequest) XXX_Size() int {
	return xxx_messageInfo_ListClustersRequest.Size(m)
}
func (m *ListClustersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClustersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListClustersRequest proto.InternalMessageInfo

func (m *ListClustersRequest) GetObjectMeta() []*ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

type ListClustersResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Clusters             []*Cluster     `protobuf:"bytes,2,rep,name=clusters,proto3" json:"clusters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListClustersResponse) Reset()         { *m = ListClustersResponse{} }
func (m *ListClustersResponse) String() string { return proto.CompactTextString(m) }
func (*ListClustersResponse) ProtoMessage()    {}
func (*ListClustersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{17}
}

func (m *ListClustersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClustersResponse.Unmarshal(m, b)
}
func (m *ListClustersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClustersResponse.Marshal(b, m, deterministic)
}
func (m *ListClustersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClustersResponse.Merge(m, src)
}
func (m *ListClustersResponse) XXX_Size() int {
	return xxx_messageInfo_ListClustersResponse.Size(m)
}
func (m *ListClustersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClustersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListClustersResponse proto.InternalMessageInfo

func (m *ListClustersResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListClustersResponse) GetClusters() []*Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

// Represents a request for deleting pods data
type DeletePodsRequest struct {
	Pods                 []*Pod   `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePodsRequest) Reset()         { *m = DeletePodsRequest{} }
func (m *DeletePodsRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePodsRequest) ProtoMessage()    {}
func (*DeletePodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{18}
}

func (m *DeletePodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePodsRequest.Unmarshal(m, b)
}
func (m *DeletePodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePodsRequest.Marshal(b, m, deterministic)
}
func (m *DeletePodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePodsRequest.Merge(m, src)
}
func (m *DeletePodsRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePodsRequest.Size(m)
}
func (m *DeletePodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePodsRequest proto.InternalMessageInfo

func (m *DeletePodsRequest) GetPods() []*Pod {
	if m != nil {
		return m.Pods
	}
	return nil
}

type DeleteControllersRequest struct {
	Controllers          []*Controller `protobuf:"bytes,1,rep,name=controllers,proto3" json:"controllers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeleteControllersRequest) Reset()         { *m = DeleteControllersRequest{} }
func (m *DeleteControllersRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteControllersRequest) ProtoMessage()    {}
func (*DeleteControllersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{19}
}

func (m *DeleteControllersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteControllersRequest.Unmarshal(m, b)
}
func (m *DeleteControllersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteControllersRequest.Marshal(b, m, deterministic)
}
func (m *DeleteControllersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteControllersRequest.Merge(m, src)
}
func (m *DeleteControllersRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteControllersRequest.Size(m)
}
func (m *DeleteControllersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteControllersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteControllersRequest proto.InternalMessageInfo

func (m *DeleteControllersRequest) GetControllers() []*Controller {
	if m != nil {
		return m.Controllers
	}
	return nil
}

// Represents a request for stoping predicting nodes
type DeleteNodesRequest struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNodesRequest) Reset()         { *m = DeleteNodesRequest{} }
func (m *DeleteNodesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNodesRequest) ProtoMessage()    {}
func (*DeleteNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_081eed3a684e3192, []int{20}
}

func (m *DeleteNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNodesRequest.Unmarshal(m, b)
}
func (m *DeleteNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNodesRequest.Marshal(b, m, deterministic)
}
func (m *DeleteNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNodesRequest.Merge(m, src)
}
func (m *DeleteNodesRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNodesRequest.Size(m)
}
func (m *DeleteNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNodesRequest proto.InternalMessageInfo

func (m *DeleteNodesRequest) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*CreatePodsRequest)(nil), "containersai.alameda.v1alpha1.datahub.resources.CreatePodsRequest")
	proto.RegisterType((*CreateControllersRequest)(nil), "containersai.alameda.v1alpha1.datahub.resources.CreateControllersRequest")
	proto.RegisterType((*CreateApplicationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.resources.CreateApplicationsRequest")
	proto.RegisterType((*CreateNamespacesRequest)(nil), "containersai.alameda.v1alpha1.datahub.resources.CreateNamespacesRequest")
	proto.RegisterType((*CreateNodesRequest)(nil), "containersai.alameda.v1alpha1.datahub.resources.CreateNodesRequest")
	proto.RegisterType((*CreateClustersRequest)(nil), "containersai.alameda.v1alpha1.datahub.resources.CreateClustersRequest")
	proto.RegisterType((*ListPodsRequest)(nil), "containersai.alameda.v1alpha1.datahub.resources.ListPodsRequest")
	proto.RegisterType((*ListPodsResponse)(nil), "containersai.alameda.v1alpha1.datahub.resources.ListPodsResponse")
	proto.RegisterType((*ListControllersRequest)(nil), "containersai.alameda.v1alpha1.datahub.resources.ListControllersRequest")
	proto.RegisterType((*ListControllersResponse)(nil), "containersai.alameda.v1alpha1.datahub.resources.ListControllersResponse")
	proto.RegisterType((*ListApplicationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.resources.ListApplicationsRequest")
	proto.RegisterType((*ListApplicationsResponse)(nil), "containersai.alameda.v1alpha1.datahub.resources.ListApplicationsResponse")
	proto.RegisterType((*ListNamespacesRequest)(nil), "containersai.alameda.v1alpha1.datahub.resources.ListNamespacesRequest")
	proto.RegisterType((*ListNamespacesResponse)(nil), "containersai.alameda.v1alpha1.datahub.resources.ListNamespacesResponse")
	proto.RegisterType((*ListNodesRequest)(nil), "containersai.alameda.v1alpha1.datahub.resources.ListNodesRequest")
	proto.RegisterType((*ListNodesResponse)(nil), "containersai.alameda.v1alpha1.datahub.resources.ListNodesResponse")
	proto.RegisterType((*ListClustersRequest)(nil), "containersai.alameda.v1alpha1.datahub.resources.ListClustersRequest")
	proto.RegisterType((*ListClustersResponse)(nil), "containersai.alameda.v1alpha1.datahub.resources.ListClustersResponse")
	proto.RegisterType((*DeletePodsRequest)(nil), "containersai.alameda.v1alpha1.datahub.resources.DeletePodsRequest")
	proto.RegisterType((*DeleteControllersRequest)(nil), "containersai.alameda.v1alpha1.datahub.resources.DeleteControllersRequest")
	proto.RegisterType((*DeleteNodesRequest)(nil), "containersai.alameda.v1alpha1.datahub.resources.DeleteNodesRequest")
}

func init() {
	proto.RegisterFile("alameda_api/v1alpha1/datahub/resources/services.proto", fileDescriptor_081eed3a684e3192)
}

var fileDescriptor_081eed3a684e3192 = []byte{
	// 722 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x97, 0xcf, 0x4f, 0xd4, 0x40,
	0x14, 0xc7, 0xd3, 0x82, 0x44, 0xdf, 0x12, 0x90, 0x2a, 0x52, 0x39, 0x91, 0x9e, 0x88, 0x89, 0x6d,
	0x40, 0x51, 0xa3, 0x5c, 0x74, 0x35, 0xd1, 0xe0, 0x0f, 0x1c, 0x88, 0x07, 0x22, 0x59, 0x87, 0xf6,
	0x65, 0x19, 0x6d, 0x3b, 0xa5, 0x33, 0xc5, 0x70, 0xf0, 0xee, 0xc1, 0x3f, 0xc0, 0xa3, 0x07, 0x0f,
	0xfc, 0x29, 0xfe, 0x3f, 0xfe, 0x03, 0xa6, 0x9d, 0xd9, 0x6e, 0x77, 0x21, 0x66, 0x5b, 0x77, 0x4d,
	0xb8, 0xb5, 0xd3, 0x7d, 0xdf, 0xcf, 0xec, 0x9b, 0x37, 0xdf, 0x37, 0x03, 0x1b, 0x34, 0xa4, 0x11,
	0x06, 0xb4, 0x43, 0x13, 0xe6, 0x1d, 0xaf, 0xd1, 0x30, 0x39, 0xa4, 0x6b, 0x5e, 0x40, 0x25, 0x3d,
	0xcc, 0x0e, 0xbc, 0x14, 0x05, 0xcf, 0x52, 0x1f, 0x85, 0x27, 0x30, 0x3d, 0x66, 0x3e, 0x0a, 0x37,
	0x49, 0xb9, 0xe4, 0x96, 0xe7, 0xf3, 0x58, 0x52, 0x16, 0x63, 0x2a, 0x28, 0x73, 0xb5, 0x86, 0xdb,
	0x8b, 0x77, 0x75, 0xbc, 0x5b, 0xc6, 0x2f, 0xaf, 0xfd, 0x95, 0xe3, 0xf3, 0x28, 0xe2, 0xb1, 0x77,
	0x94, 0x61, 0xca, 0x7a, 0x8c, 0xe5, 0x51, 0xa7, 0x16, 0xa1, 0xa4, 0xf9, 0xa8, 0x0e, 0xbb, 0x37,
	0x62, 0x58, 0xf9, 0xa4, 0xe3, 0x96, 0xba, 0x9c, 0x77, 0x43, 0xf4, 0xd2, 0xc4, 0xf7, 0x84, 0xa4,
	0x32, 0xd3, 0x1f, 0x9c, 0x7d, 0x58, 0x68, 0xa7, 0x48, 0x25, 0x6e, 0xf3, 0x40, 0x10, 0x3c, 0xca,
	0x50, 0x48, 0xeb, 0x39, 0x4c, 0x27, 0x3c, 0x10, 0xb6, 0xb1, 0x32, 0xb5, 0xda, 0x5a, 0xbf, 0xeb,
	0xd6, 0xcc, 0x87, 0xbb, 0xcd, 0x03, 0x52, 0x28, 0x38, 0x27, 0x60, 0x2b, 0xf9, 0x36, 0x8f, 0x65,
	0xca, 0xc3, 0x10, 0xd3, 0x92, 0xb2, 0x0f, 0x2d, 0xbf, 0x3f, 0xaa, 0x61, 0x8f, 0x6a, 0xc3, 0xfa,
	0xca, 0xa4, 0xaa, 0xe7, 0x7c, 0x81, 0x9b, 0x0a, 0xfd, 0x38, 0x49, 0x42, 0xe6, 0x53, 0xc9, 0x78,
	0x5c, 0xb2, 0x3f, 0xc0, 0x2c, 0xad, 0x0c, 0x6b, 0xf8, 0x66, 0x6d, 0x78, 0x45, 0x9b, 0x0c, 0x28,
	0x3a, 0x19, 0x2c, 0x29, 0xfc, 0x6b, 0x1a, 0xa1, 0x48, 0xa8, 0x8f, 0x25, 0x7c, 0x0f, 0x20, 0x2e,
	0x07, 0x35, 0xfa, 0x61, 0x6d, 0x74, 0xa9, 0x4b, 0x2a, 0x6a, 0x0e, 0x05, 0x4b, 0x63, 0x79, 0xd0,
	0x27, 0x6e, 0xc1, 0xa5, 0x38, 0x7f, 0xd7, 0xb0, 0x8d, 0xfa, 0x30, 0x1e, 0x20, 0x51, 0x1a, 0x4e,
	0x04, 0x8b, 0x7a, 0x4d, 0xc3, 0x4c, 0xc8, 0xca, 0x82, 0xee, 0xc2, 0x65, 0x5f, 0x0f, 0x69, 0xd0,
	0x83, 0xfa, 0xab, 0xa9, 0x04, 0x48, 0xa9, 0xe4, 0xfc, 0x36, 0x61, 0xfe, 0x25, 0x13, 0xb2, 0x5a,
	0xa0, 0xef, 0x00, 0x24, 0x8b, 0xb0, 0x93, 0xd2, 0xb8, 0x8b, 0xb6, 0xb1, 0x62, 0xac, 0xb6, 0xd6,
	0xef, 0x8f, 0xc8, 0x52, 0xdb, 0xd1, 0xdd, 0x65, 0x11, 0x92, 0x3c, 0x9c, 0x5c, 0x91, 0xbd, 0x47,
	0xeb, 0x3d, 0xb4, 0xf8, 0xc1, 0x47, 0xf4, 0x65, 0x27, 0xdf, 0x77, 0xb6, 0xd9, 0xb0, 0x24, 0xdf,
	0x14, 0x1a, 0xaf, 0x50, 0x52, 0x02, 0xbc, 0x7c, 0xb6, 0x5e, 0xc0, 0xf4, 0x27, 0x16, 0x07, 0xf6,
	0xd4, 0x8a, 0xb1, 0x3a, 0xd7, 0x60, 0x11, 0xb6, 0x58, 0x1c, 0x90, 0x42, 0xc2, 0xea, 0xc0, 0xac,
	0xf0, 0x69, 0xc8, 0xe2, 0x6e, 0x47, 0x72, 0x1e, 0xda, 0xd3, 0x85, 0x64, 0xfd, 0xfa, 0xdd, 0x51,
	0x22, 0xbb, 0x9c, 0x87, 0xa4, 0x25, 0xfa, 0x2f, 0xce, 0x57, 0x03, 0xae, 0xf6, 0xb3, 0x2e, 0x12,
	0x1e, 0x0b, 0xb4, 0x6e, 0xc1, 0x8c, 0x32, 0x0f, 0x9d, 0x72, 0xcb, 0x55, 0xb6, 0xe2, 0xa6, 0x89,
	0xef, 0xee, 0x14, 0x5f, 0x88, 0xfe, 0x45, 0xe9, 0x21, 0xe6, 0x3f, 0x7b, 0xc8, 0xa9, 0x09, 0x37,
	0xf2, 0xa9, 0x9c, 0x63, 0x21, 0x08, 0xf3, 0xb9, 0xad, 0x9e, 0x74, 0x7c, 0x1e, 0x07, 0x2c, 0xdf,
	0x78, 0x7a, 0x66, 0x9b, 0xf5, 0x8a, 0xe1, 0x6d, 0x2e, 0xd2, 0xee, 0x69, 0x90, 0xb9, 0xa3, 0x81,
	0xf7, 0x0b, 0x53, 0x16, 0xce, 0x4f, 0x03, 0x96, 0xce, 0xa4, 0xaa, 0xc1, 0xe2, 0x0d, 0x59, 0xb3,
	0x39, 0x66, 0x6b, 0xfe, 0xac, 0x66, 0x79, 0x9e, 0x31, 0x0f, 0xa5, 0xda, 0x18, 0x6b, 0xaa, 0x9d,
	0x53, 0x03, 0xec, 0xb3, 0xe4, 0x06, 0x09, 0x1a, 0xee, 0x1f, 0xe6, 0x04, 0xfa, 0xc7, 0x62, 0x3e,
	0xd3, 0xb3, 0xdd, 0x63, 0xb2, 0x19, 0xfa, 0x61, 0xa8, 0xcd, 0x56, 0xe5, 0x36, 0xc8, 0xcf, 0x60,
	0x8b, 0x33, 0xc7, 0xda, 0xe2, 0x7e, 0x69, 0x6b, 0x1a, 0xe8, 0x70, 0x17, 0xb2, 0x23, 0x38, 0xdf,
	0x0c, 0x58, 0xa8, 0xfc, 0x95, 0x06, 0x89, 0x2e, 0x3b, 0xbb, 0x39, 0x86, 0xce, 0x2e, 0xe0, 0x5a,
	0xe1, 0x1e, 0x43, 0x7d, 0x7d, 0xb2, 0x15, 0xf7, 0xdd, 0x80, 0xeb, 0x83, 0xd4, 0x06, 0x69, 0xa8,
	0x1e, 0x3d, 0xcc, 0xb1, 0x1d, 0x3d, 0xf6, 0x61, 0xe1, 0x29, 0x86, 0x38, 0xc1, 0xc3, 0xb1, 0x92,
	0xff, 0xff, 0x87, 0x63, 0x0a, 0x96, 0x42, 0x4f, 0xec, 0x98, 0xf8, 0xe4, 0xd9, 0x5e, 0xbb, 0xcb,
	0xa4, 0xde, 0x5f, 0x95, 0x2b, 0xd5, 0x6d, 0xca, 0xbc, 0xfc, 0xf6, 0x32, 0xda, 0x4d, 0xe6, 0x60,
	0xa6, 0xb8, 0xa7, 0xdc, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x50, 0x2b, 0x23, 0xcc, 0x0d,
	0x00, 0x00,
}
