// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datahub/resource/metadata/v1alpha2/metadata.proto

package v1alpha2 // import "github.com/containers-ai/api/datahub/resource/metadata/v1alpha2"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Represents kubernetes resource with namespace and name
type NamespacedName struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamespacedName) Reset()         { *m = NamespacedName{} }
func (m *NamespacedName) String() string { return proto.CompactTextString(m) }
func (*NamespacedName) ProtoMessage()    {}
func (*NamespacedName) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_6c60dd7ff24c7093, []int{0}
}
func (m *NamespacedName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespacedName.Unmarshal(m, b)
}
func (m *NamespacedName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespacedName.Marshal(b, m, deterministic)
}
func (dst *NamespacedName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespacedName.Merge(dst, src)
}
func (m *NamespacedName) XXX_Size() int {
	return xxx_messageInfo_NamespacedName.Size(m)
}
func (m *NamespacedName) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespacedName.DiscardUnknown(m)
}

var xxx_messageInfo_NamespacedName proto.InternalMessageInfo

func (m *NamespacedName) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *NamespacedName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ObjectMeta struct {
	NamespacedName       *NamespacedName `protobuf:"bytes,1,opt,name=namespaced_name,json=namespacedName,proto3" json:"namespaced_name,omitempty"`
	Uid                  string          `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	ClusterId            string          `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ObjectMeta) Reset()         { *m = ObjectMeta{} }
func (m *ObjectMeta) String() string { return proto.CompactTextString(m) }
func (*ObjectMeta) ProtoMessage()    {}
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_6c60dd7ff24c7093, []int{1}
}
func (m *ObjectMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectMeta.Unmarshal(m, b)
}
func (m *ObjectMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectMeta.Marshal(b, m, deterministic)
}
func (dst *ObjectMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectMeta.Merge(dst, src)
}
func (m *ObjectMeta) XXX_Size() int {
	return xxx_messageInfo_ObjectMeta.Size(m)
}
func (m *ObjectMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectMeta proto.InternalMessageInfo

func (m *ObjectMeta) GetNamespacedName() *NamespacedName {
	if m != nil {
		return m.NamespacedName
	}
	return nil
}

func (m *ObjectMeta) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ObjectMeta) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func init() {
	proto.RegisterType((*NamespacedName)(nil), "containersai.datahub.resource.metadata.v1alpha2.NamespacedName")
	proto.RegisterType((*ObjectMeta)(nil), "containersai.datahub.resource.metadata.v1alpha2.ObjectMeta")
}

func init() {
	proto.RegisterFile("datahub/resource/metadata/v1alpha2/metadata.proto", fileDescriptor_metadata_6c60dd7ff24c7093)
}

var fileDescriptor_metadata_6c60dd7ff24c7093 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x14, 0x84, 0x59, 0x2b, 0x42, 0x9f, 0x50, 0x25, 0xa7, 0x3d, 0x28, 0x48, 0x4f, 0x5e, 0x4c, 0x68,
	0xfd, 0x01, 0xc5, 0xde, 0x3c, 0xa8, 0xd0, 0xa3, 0x97, 0xf2, 0x36, 0x79, 0xb8, 0x91, 0xee, 0x26,
	0x24, 0x2f, 0xfe, 0x25, 0xff, 0xa6, 0x24, 0xee, 0xae, 0xf6, 0x24, 0xde, 0x26, 0x93, 0x99, 0xe4,
	0x63, 0x60, 0x65, 0x90, 0xb1, 0x4d, 0x8d, 0x0a, 0x14, 0x5d, 0x0a, 0x9a, 0x54, 0x47, 0x8c, 0xd9,
	0x54, 0x1f, 0x2b, 0x3c, 0xf8, 0x16, 0xd7, 0x93, 0x23, 0x7d, 0x70, 0xec, 0x84, 0xd2, 0xae, 0x67,
	0xb4, 0x3d, 0x85, 0x88, 0x56, 0x0e, 0x7d, 0x39, 0xf6, 0xe5, 0x94, 0x1e, 0xfb, 0xcb, 0x2d, 0x2c,
	0x9e, 0xb1, 0xa3, 0xe8, 0x51, 0x93, 0xc9, 0x4a, 0x5c, 0xc1, 0xbc, 0x1f, 0x9d, 0xba, 0xba, 0xa9,
	0x6e, 0xe7, 0xbb, 0x1f, 0x43, 0x08, 0x38, 0xcd, 0x87, 0xfa, 0xa4, 0x5c, 0x14, 0xbd, 0xfc, 0xac,
	0x00, 0x5e, 0x9a, 0x77, 0xd2, 0xfc, 0x44, 0x8c, 0xa2, 0x85, 0x8b, 0x29, 0x6f, 0xf6, 0x25, 0x9d,
	0x9f, 0x39, 0x5f, 0x6f, 0xe4, 0x3f, 0xe9, 0xe4, 0x31, 0xda, 0x6e, 0xd1, 0x1f, 0xa3, 0x5e, 0xc2,
	0x2c, 0x59, 0x33, 0xb0, 0x64, 0x29, 0xae, 0x01, 0xf4, 0x21, 0x45, 0xa6, 0xb0, 0xb7, 0xa6, 0x9e,
	0x7d, 0xd3, 0x0f, 0xce, 0xa3, 0xd9, 0x3e, 0xbc, 0x6e, 0xde, 0x2c, 0xe7, 0x4f, 0xb5, 0xeb, 0x7e,
	0x6d, 0x75, 0x87, 0x56, 0xa1, 0xb7, 0xea, 0xef, 0xc1, 0x9b, 0xb3, 0x32, 0xf4, 0xfd, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x18, 0x24, 0x1f, 0xf4, 0x9d, 0x01, 0x00, 0x00,
}
