// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alameda_api/v1alpha1/datahub/plannings/plannings.proto

package plannings

import (
	fmt "fmt"
	resources "github.com/containers-ai/api/alameda_api/v1alpha1/datahub/resources"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Planning struct {
	Resources            []*resources.ResourceRequirements `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	InitialResources     []*resources.ResourceRequirements `protobuf:"bytes,2,rep,name=initial_resources,json=initialResources,proto3" json:"initial_resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *Planning) Reset()         { *m = Planning{} }
func (m *Planning) String() string { return proto.CompactTextString(m) }
func (*Planning) ProtoMessage()    {}
func (*Planning) Descriptor() ([]byte, []int) {
	return fileDescriptor_36c6a4155f49dbb5, []int{0}
}

func (m *Planning) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Planning.Unmarshal(m, b)
}
func (m *Planning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Planning.Marshal(b, m, deterministic)
}
func (m *Planning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Planning.Merge(m, src)
}
func (m *Planning) XXX_Size() int {
	return xxx_messageInfo_Planning.Size(m)
}
func (m *Planning) XXX_DiscardUnknown() {
	xxx_messageInfo_Planning.DiscardUnknown(m)
}

var xxx_messageInfo_Planning proto.InternalMessageInfo

func (m *Planning) GetResources() []*resources.ResourceRequirements {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Planning) GetInitialResources() []*resources.ResourceRequirements {
	if m != nil {
		return m.InitialResources
	}
	return nil
}

type ContainerPlanning struct {
	Name                 string                            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Resources            []*resources.ResourceRequirements `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	InitialResources     []*resources.ResourceRequirements `protobuf:"bytes,3,rep,name=initial_resources,json=initialResources,proto3" json:"initial_resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ContainerPlanning) Reset()         { *m = ContainerPlanning{} }
func (m *ContainerPlanning) String() string { return proto.CompactTextString(m) }
func (*ContainerPlanning) ProtoMessage()    {}
func (*ContainerPlanning) Descriptor() ([]byte, []int) {
	return fileDescriptor_36c6a4155f49dbb5, []int{1}
}

func (m *ContainerPlanning) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerPlanning.Unmarshal(m, b)
}
func (m *ContainerPlanning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerPlanning.Marshal(b, m, deterministic)
}
func (m *ContainerPlanning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerPlanning.Merge(m, src)
}
func (m *ContainerPlanning) XXX_Size() int {
	return xxx_messageInfo_ContainerPlanning.Size(m)
}
func (m *ContainerPlanning) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerPlanning.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerPlanning proto.InternalMessageInfo

func (m *ContainerPlanning) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContainerPlanning) GetResources() []*resources.ResourceRequirements {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *ContainerPlanning) GetInitialResources() []*resources.ResourceRequirements {
	if m != nil {
		return m.InitialResources
	}
	return nil
}

type PodPlanning struct {
	ObjectMeta           *resources.ObjectMeta      `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	PlanningType         PlanningType               `protobuf:"varint,2,opt,name=planning_type,json=planningType,proto3,enum=containersai.alameda.v1alpha1.datahub.plannings.PlanningType" json:"planning_type,omitempty"`
	PlanningId           string                     `protobuf:"bytes,3,opt,name=planning_id,json=planningId,proto3" json:"planning_id,omitempty"`
	TotalCost            float64                    `protobuf:"fixed64,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	ApplyPlanningNow     bool                       `protobuf:"varint,5,opt,name=apply_planning_now,json=applyPlanningNow,proto3" json:"apply_planning_now,omitempty"`
	StartTime            *timestamp.Timestamp       `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp       `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	AssignPodPolicy      *resources.AssignPodPolicy `protobuf:"bytes,8,opt,name=assign_pod_policy,json=assignPodPolicy,proto3" json:"assign_pod_policy,omitempty"`
	TopController        *resources.Controller      `protobuf:"bytes,9,opt,name=top_controller,json=topController,proto3" json:"top_controller,omitempty"`
	ContainerPlannings   []*ContainerPlanning       `protobuf:"bytes,10,rep,name=container_plannings,json=containerPlannings,proto3" json:"container_plannings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PodPlanning) Reset()         { *m = PodPlanning{} }
func (m *PodPlanning) String() string { return proto.CompactTextString(m) }
func (*PodPlanning) ProtoMessage()    {}
func (*PodPlanning) Descriptor() ([]byte, []int) {
	return fileDescriptor_36c6a4155f49dbb5, []int{2}
}

func (m *PodPlanning) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodPlanning.Unmarshal(m, b)
}
func (m *PodPlanning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodPlanning.Marshal(b, m, deterministic)
}
func (m *PodPlanning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodPlanning.Merge(m, src)
}
func (m *PodPlanning) XXX_Size() int {
	return xxx_messageInfo_PodPlanning.Size(m)
}
func (m *PodPlanning) XXX_DiscardUnknown() {
	xxx_messageInfo_PodPlanning.DiscardUnknown(m)
}

var xxx_messageInfo_PodPlanning proto.InternalMessageInfo

func (m *PodPlanning) GetObjectMeta() *resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *PodPlanning) GetPlanningType() PlanningType {
	if m != nil {
		return m.PlanningType
	}
	return PlanningType_PT_UNDEFINED
}

func (m *PodPlanning) GetPlanningId() string {
	if m != nil {
		return m.PlanningId
	}
	return ""
}

func (m *PodPlanning) GetTotalCost() float64 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

func (m *PodPlanning) GetApplyPlanningNow() bool {
	if m != nil {
		return m.ApplyPlanningNow
	}
	return false
}

func (m *PodPlanning) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *PodPlanning) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *PodPlanning) GetAssignPodPolicy() *resources.AssignPodPolicy {
	if m != nil {
		return m.AssignPodPolicy
	}
	return nil
}

func (m *PodPlanning) GetTopController() *resources.Controller {
	if m != nil {
		return m.TopController
	}
	return nil
}

func (m *PodPlanning) GetContainerPlannings() []*ContainerPlanning {
	if m != nil {
		return m.ContainerPlannings
	}
	return nil
}

type ControllerPlanning struct {
	ObjectMeta           *resources.ObjectMeta `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Kind                 resources.Kind        `protobuf:"varint,2,opt,name=kind,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.Kind" json:"kind,omitempty"`
	PlanningType         PlanningType          `protobuf:"varint,3,opt,name=planning_type,json=planningType,proto3,enum=containersai.alameda.v1alpha1.datahub.plannings.PlanningType" json:"planning_type,omitempty"`
	PlanningId           string                `protobuf:"bytes,4,opt,name=planning_id,json=planningId,proto3" json:"planning_id,omitempty"`
	TotalCost            float64               `protobuf:"fixed64,5,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	ApplyPlanningNow     bool                  `protobuf:"varint,6,opt,name=apply_planning_now,json=applyPlanningNow,proto3" json:"apply_planning_now,omitempty"`
	StartTime            *timestamp.Timestamp  `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp  `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Plannings            []*Planning           `protobuf:"bytes,9,rep,name=plannings,proto3" json:"plannings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ControllerPlanning) Reset()         { *m = ControllerPlanning{} }
func (m *ControllerPlanning) String() string { return proto.CompactTextString(m) }
func (*ControllerPlanning) ProtoMessage()    {}
func (*ControllerPlanning) Descriptor() ([]byte, []int) {
	return fileDescriptor_36c6a4155f49dbb5, []int{3}
}

func (m *ControllerPlanning) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerPlanning.Unmarshal(m, b)
}
func (m *ControllerPlanning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerPlanning.Marshal(b, m, deterministic)
}
func (m *ControllerPlanning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerPlanning.Merge(m, src)
}
func (m *ControllerPlanning) XXX_Size() int {
	return xxx_messageInfo_ControllerPlanning.Size(m)
}
func (m *ControllerPlanning) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerPlanning.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerPlanning proto.InternalMessageInfo

func (m *ControllerPlanning) GetObjectMeta() *resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *ControllerPlanning) GetKind() resources.Kind {
	if m != nil {
		return m.Kind
	}
	return resources.Kind_KIND_UNDEFINED
}

func (m *ControllerPlanning) GetPlanningType() PlanningType {
	if m != nil {
		return m.PlanningType
	}
	return PlanningType_PT_UNDEFINED
}

func (m *ControllerPlanning) GetPlanningId() string {
	if m != nil {
		return m.PlanningId
	}
	return ""
}

func (m *ControllerPlanning) GetTotalCost() float64 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

func (m *ControllerPlanning) GetApplyPlanningNow() bool {
	if m != nil {
		return m.ApplyPlanningNow
	}
	return false
}

func (m *ControllerPlanning) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *ControllerPlanning) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *ControllerPlanning) GetPlannings() []*Planning {
	if m != nil {
		return m.Plannings
	}
	return nil
}

type ApplicationPlanning struct {
	ObjectMeta           *resources.ObjectMeta `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	PlanningType         PlanningType          `protobuf:"varint,2,opt,name=planning_type,json=planningType,proto3,enum=containersai.alameda.v1alpha1.datahub.plannings.PlanningType" json:"planning_type,omitempty"`
	PlanningId           string                `protobuf:"bytes,3,opt,name=planning_id,json=planningId,proto3" json:"planning_id,omitempty"`
	TotalCost            float64               `protobuf:"fixed64,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	ApplyPlanningNow     bool                  `protobuf:"varint,5,opt,name=apply_planning_now,json=applyPlanningNow,proto3" json:"apply_planning_now,omitempty"`
	StartTime            *timestamp.Timestamp  `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp  `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Plannings            []*Planning           `protobuf:"bytes,8,rep,name=plannings,proto3" json:"plannings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ApplicationPlanning) Reset()         { *m = ApplicationPlanning{} }
func (m *ApplicationPlanning) String() string { return proto.CompactTextString(m) }
func (*ApplicationPlanning) ProtoMessage()    {}
func (*ApplicationPlanning) Descriptor() ([]byte, []int) {
	return fileDescriptor_36c6a4155f49dbb5, []int{4}
}

func (m *ApplicationPlanning) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationPlanning.Unmarshal(m, b)
}
func (m *ApplicationPlanning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationPlanning.Marshal(b, m, deterministic)
}
func (m *ApplicationPlanning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationPlanning.Merge(m, src)
}
func (m *ApplicationPlanning) XXX_Size() int {
	return xxx_messageInfo_ApplicationPlanning.Size(m)
}
func (m *ApplicationPlanning) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationPlanning.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationPlanning proto.InternalMessageInfo

func (m *ApplicationPlanning) GetObjectMeta() *resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *ApplicationPlanning) GetPlanningType() PlanningType {
	if m != nil {
		return m.PlanningType
	}
	return PlanningType_PT_UNDEFINED
}

func (m *ApplicationPlanning) GetPlanningId() string {
	if m != nil {
		return m.PlanningId
	}
	return ""
}

func (m *ApplicationPlanning) GetTotalCost() float64 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

func (m *ApplicationPlanning) GetApplyPlanningNow() bool {
	if m != nil {
		return m.ApplyPlanningNow
	}
	return false
}

func (m *ApplicationPlanning) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *ApplicationPlanning) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *ApplicationPlanning) GetPlannings() []*Planning {
	if m != nil {
		return m.Plannings
	}
	return nil
}

type NamespacePlanning struct {
	ObjectMeta           *resources.ObjectMeta `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	PlanningType         PlanningType          `protobuf:"varint,2,opt,name=planning_type,json=planningType,proto3,enum=containersai.alameda.v1alpha1.datahub.plannings.PlanningType" json:"planning_type,omitempty"`
	PlanningId           string                `protobuf:"bytes,3,opt,name=planning_id,json=planningId,proto3" json:"planning_id,omitempty"`
	TotalCost            float64               `protobuf:"fixed64,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	ApplyPlanningNow     bool                  `protobuf:"varint,5,opt,name=apply_planning_now,json=applyPlanningNow,proto3" json:"apply_planning_now,omitempty"`
	StartTime            *timestamp.Timestamp  `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp  `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Plannings            []*Planning           `protobuf:"bytes,8,rep,name=plannings,proto3" json:"plannings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *NamespacePlanning) Reset()         { *m = NamespacePlanning{} }
func (m *NamespacePlanning) String() string { return proto.CompactTextString(m) }
func (*NamespacePlanning) ProtoMessage()    {}
func (*NamespacePlanning) Descriptor() ([]byte, []int) {
	return fileDescriptor_36c6a4155f49dbb5, []int{5}
}

func (m *NamespacePlanning) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespacePlanning.Unmarshal(m, b)
}
func (m *NamespacePlanning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespacePlanning.Marshal(b, m, deterministic)
}
func (m *NamespacePlanning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespacePlanning.Merge(m, src)
}
func (m *NamespacePlanning) XXX_Size() int {
	return xxx_messageInfo_NamespacePlanning.Size(m)
}
func (m *NamespacePlanning) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespacePlanning.DiscardUnknown(m)
}

var xxx_messageInfo_NamespacePlanning proto.InternalMessageInfo

func (m *NamespacePlanning) GetObjectMeta() *resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *NamespacePlanning) GetPlanningType() PlanningType {
	if m != nil {
		return m.PlanningType
	}
	return PlanningType_PT_UNDEFINED
}

func (m *NamespacePlanning) GetPlanningId() string {
	if m != nil {
		return m.PlanningId
	}
	return ""
}

func (m *NamespacePlanning) GetTotalCost() float64 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

func (m *NamespacePlanning) GetApplyPlanningNow() bool {
	if m != nil {
		return m.ApplyPlanningNow
	}
	return false
}

func (m *NamespacePlanning) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *NamespacePlanning) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *NamespacePlanning) GetPlannings() []*Planning {
	if m != nil {
		return m.Plannings
	}
	return nil
}

type NodePlanning struct {
	ObjectMeta           *resources.ObjectMeta `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	PlanningType         PlanningType          `protobuf:"varint,2,opt,name=planning_type,json=planningType,proto3,enum=containersai.alameda.v1alpha1.datahub.plannings.PlanningType" json:"planning_type,omitempty"`
	PlanningId           string                `protobuf:"bytes,3,opt,name=planning_id,json=planningId,proto3" json:"planning_id,omitempty"`
	TotalCost            float64               `protobuf:"fixed64,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	ApplyPlanningNow     bool                  `protobuf:"varint,5,opt,name=apply_planning_now,json=applyPlanningNow,proto3" json:"apply_planning_now,omitempty"`
	StartTime            *timestamp.Timestamp  `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp  `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Plannings            []*Planning           `protobuf:"bytes,8,rep,name=plannings,proto3" json:"plannings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *NodePlanning) Reset()         { *m = NodePlanning{} }
func (m *NodePlanning) String() string { return proto.CompactTextString(m) }
func (*NodePlanning) ProtoMessage()    {}
func (*NodePlanning) Descriptor() ([]byte, []int) {
	return fileDescriptor_36c6a4155f49dbb5, []int{6}
}

func (m *NodePlanning) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodePlanning.Unmarshal(m, b)
}
func (m *NodePlanning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodePlanning.Marshal(b, m, deterministic)
}
func (m *NodePlanning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodePlanning.Merge(m, src)
}
func (m *NodePlanning) XXX_Size() int {
	return xxx_messageInfo_NodePlanning.Size(m)
}
func (m *NodePlanning) XXX_DiscardUnknown() {
	xxx_messageInfo_NodePlanning.DiscardUnknown(m)
}

var xxx_messageInfo_NodePlanning proto.InternalMessageInfo

func (m *NodePlanning) GetObjectMeta() *resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *NodePlanning) GetPlanningType() PlanningType {
	if m != nil {
		return m.PlanningType
	}
	return PlanningType_PT_UNDEFINED
}

func (m *NodePlanning) GetPlanningId() string {
	if m != nil {
		return m.PlanningId
	}
	return ""
}

func (m *NodePlanning) GetTotalCost() float64 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

func (m *NodePlanning) GetApplyPlanningNow() bool {
	if m != nil {
		return m.ApplyPlanningNow
	}
	return false
}

func (m *NodePlanning) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *NodePlanning) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *NodePlanning) GetPlannings() []*Planning {
	if m != nil {
		return m.Plannings
	}
	return nil
}

type ClusterPlanning struct {
	ObjectMeta           *resources.ObjectMeta `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	PlanningType         PlanningType          `protobuf:"varint,2,opt,name=planning_type,json=planningType,proto3,enum=containersai.alameda.v1alpha1.datahub.plannings.PlanningType" json:"planning_type,omitempty"`
	PlanningId           string                `protobuf:"bytes,3,opt,name=planning_id,json=planningId,proto3" json:"planning_id,omitempty"`
	TotalCost            float64               `protobuf:"fixed64,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	ApplyPlanningNow     bool                  `protobuf:"varint,5,opt,name=apply_planning_now,json=applyPlanningNow,proto3" json:"apply_planning_now,omitempty"`
	StartTime            *timestamp.Timestamp  `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp  `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Plannings            []*Planning           `protobuf:"bytes,8,rep,name=plannings,proto3" json:"plannings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ClusterPlanning) Reset()         { *m = ClusterPlanning{} }
func (m *ClusterPlanning) String() string { return proto.CompactTextString(m) }
func (*ClusterPlanning) ProtoMessage()    {}
func (*ClusterPlanning) Descriptor() ([]byte, []int) {
	return fileDescriptor_36c6a4155f49dbb5, []int{7}
}

func (m *ClusterPlanning) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterPlanning.Unmarshal(m, b)
}
func (m *ClusterPlanning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterPlanning.Marshal(b, m, deterministic)
}
func (m *ClusterPlanning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterPlanning.Merge(m, src)
}
func (m *ClusterPlanning) XXX_Size() int {
	return xxx_messageInfo_ClusterPlanning.Size(m)
}
func (m *ClusterPlanning) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterPlanning.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterPlanning proto.InternalMessageInfo

func (m *ClusterPlanning) GetObjectMeta() *resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *ClusterPlanning) GetPlanningType() PlanningType {
	if m != nil {
		return m.PlanningType
	}
	return PlanningType_PT_UNDEFINED
}

func (m *ClusterPlanning) GetPlanningId() string {
	if m != nil {
		return m.PlanningId
	}
	return ""
}

func (m *ClusterPlanning) GetTotalCost() float64 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

func (m *ClusterPlanning) GetApplyPlanningNow() bool {
	if m != nil {
		return m.ApplyPlanningNow
	}
	return false
}

func (m *ClusterPlanning) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *ClusterPlanning) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *ClusterPlanning) GetPlannings() []*Planning {
	if m != nil {
		return m.Plannings
	}
	return nil
}

func init() {
	proto.RegisterType((*Planning)(nil), "containersai.alameda.v1alpha1.datahub.plannings.Planning")
	proto.RegisterType((*ContainerPlanning)(nil), "containersai.alameda.v1alpha1.datahub.plannings.ContainerPlanning")
	proto.RegisterType((*PodPlanning)(nil), "containersai.alameda.v1alpha1.datahub.plannings.PodPlanning")
	proto.RegisterType((*ControllerPlanning)(nil), "containersai.alameda.v1alpha1.datahub.plannings.ControllerPlanning")
	proto.RegisterType((*ApplicationPlanning)(nil), "containersai.alameda.v1alpha1.datahub.plannings.ApplicationPlanning")
	proto.RegisterType((*NamespacePlanning)(nil), "containersai.alameda.v1alpha1.datahub.plannings.NamespacePlanning")
	proto.RegisterType((*NodePlanning)(nil), "containersai.alameda.v1alpha1.datahub.plannings.NodePlanning")
	proto.RegisterType((*ClusterPlanning)(nil), "containersai.alameda.v1alpha1.datahub.plannings.ClusterPlanning")
}

func init() {
	proto.RegisterFile("alameda_api/v1alpha1/datahub/plannings/plannings.proto", fileDescriptor_36c6a4155f49dbb5)
}

var fileDescriptor_36c6a4155f49dbb5 = []byte{
	// 701 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x4f, 0x6b, 0xdb, 0x3e,
	0x18, 0xc6, 0x89, 0xdb, 0xc6, 0x6f, 0xfa, 0x2f, 0xea, 0xc5, 0x14, 0x7e, 0x34, 0xe4, 0x94, 0xc3,
	0x6f, 0x36, 0xcd, 0x68, 0xa1, 0x8c, 0xc1, 0xda, 0xd0, 0x43, 0x19, 0xeb, 0x8a, 0x28, 0x0c, 0xc6,
	0xc0, 0x28, 0xb6, 0x96, 0x6a, 0xb3, 0x25, 0xcd, 0x52, 0x56, 0x72, 0xdb, 0x75, 0x30, 0xc6, 0x3e,
	0xdf, 0xae, 0xfb, 0x0e, 0x3b, 0x0f, 0xab, 0xfe, 0xd3, 0xae, 0xb0, 0x3a, 0xa5, 0x2d, 0x1b, 0xe4,
	0xf6, 0xea, 0xb5, 0x9e, 0xe7, 0x95, 0x5e, 0x3d, 0x8f, 0x48, 0x04, 0xbb, 0x24, 0x26, 0x09, 0x8d,
	0x48, 0x40, 0x24, 0xf3, 0x3f, 0x6e, 0x93, 0x58, 0x9e, 0x91, 0x6d, 0x3f, 0x22, 0x9a, 0x9c, 0x4d,
	0x46, 0xbe, 0x8c, 0x09, 0xe7, 0x8c, 0x8f, 0x55, 0x15, 0x79, 0x32, 0x15, 0x5a, 0x20, 0x3f, 0x14,
	0x5c, 0x13, 0xc6, 0x69, 0xaa, 0x08, 0xf3, 0x72, 0x12, 0xaf, 0x20, 0xf0, 0x72, 0x02, 0xaf, 0x84,
	0x6d, 0x0e, 0x6a, 0x16, 0xd2, 0x53, 0x49, 0xf3, 0x22, 0x9b, 0x3b, 0x7f, 0xc4, 0xa4, 0x54, 0x89,
	0x49, 0x1a, 0x52, 0xe5, 0x27, 0x54, 0x93, 0x2c, 0x3b, 0x23, 0x4c, 0x8a, 0x98, 0x85, 0xac, 0xac,
	0xb6, 0x5b, 0x13, 0x56, 0x46, 0x39, 0x6e, 0x50, 0x13, 0x77, 0x79, 0x67, 0x5b, 0x63, 0x21, 0xc6,
	0x31, 0xf5, 0xcd, 0x68, 0x34, 0x79, 0xeb, 0x6b, 0x96, 0x50, 0xa5, 0x49, 0x22, 0x2f, 0x26, 0xf4,
	0x7e, 0x58, 0xd0, 0x3a, 0xc9, 0x9b, 0x82, 0x42, 0x70, 0x4a, 0x1a, 0xd7, 0xea, 0x36, 0xfb, 0xed,
	0xc1, 0xa1, 0x57, 0xef, 0x00, 0xaa, 0xc5, 0xe2, 0x3c, 0xc2, 0xf4, 0xc3, 0x84, 0xa5, 0x34, 0xa1,
	0x5c, 0x2b, 0x5c, 0xf1, 0xa2, 0x14, 0x3a, 0x8c, 0x33, 0xcd, 0x48, 0x1c, 0x54, 0xc5, 0x1a, 0x77,
	0x59, 0x6c, 0x3d, 0xe7, 0x2f, 0x3e, 0xaa, 0xde, 0xa7, 0x06, 0x74, 0x86, 0x05, 0x75, 0xb9, 0x5d,
	0x04, 0x36, 0x27, 0x09, 0x75, 0xad, 0xae, 0xd5, 0x77, 0xb0, 0x89, 0xaf, 0xb6, 0xa0, 0xf1, 0x90,
	0x2d, 0x68, 0xde, 0x6f, 0x0b, 0x7e, 0x2e, 0x40, 0xfb, 0x44, 0x44, 0xe5, 0xe6, 0xdf, 0x40, 0x5b,
	0x8c, 0xde, 0xd1, 0x50, 0x07, 0x99, 0xaa, 0x4d, 0x0f, 0xda, 0x83, 0x27, 0x33, 0x57, 0x7f, 0x69,
	0x38, 0x5e, 0x50, 0x4d, 0x30, 0x88, 0x32, 0x46, 0x23, 0x58, 0x29, 0xac, 0x16, 0x64, 0x7a, 0x74,
	0x1b, 0x5d, 0xab, 0xbf, 0x3a, 0x78, 0xea, 0xcd, 0x68, 0x67, 0xaf, 0x58, 0xef, 0xe9, 0x54, 0x52,
	0xbc, 0x2c, 0x2f, 0x8d, 0xd0, 0x16, 0xb4, 0xcb, 0x1a, 0x2c, 0x72, 0x9b, 0xe6, 0x14, 0xa1, 0x48,
	0x1d, 0x45, 0xe8, 0x3f, 0x00, 0x2d, 0x34, 0x89, 0x83, 0x50, 0x28, 0xed, 0xda, 0x5d, 0xab, 0x6f,
	0x61, 0xc7, 0x64, 0x86, 0x42, 0x69, 0xf4, 0x3f, 0x20, 0x22, 0x65, 0x3c, 0x0d, 0x4a, 0x16, 0x2e,
	0xce, 0xdd, 0x85, 0xae, 0xd5, 0x6f, 0xe1, 0x75, 0xf3, 0xa5, 0x28, 0x7e, 0x2c, 0xce, 0xd1, 0x1e,
	0x80, 0xd2, 0x24, 0xd5, 0x41, 0xe6, 0x20, 0x77, 0xd1, 0xb4, 0x6b, 0xd3, 0xbb, 0xb0, 0x97, 0x57,
	0xd8, 0xcb, 0x3b, 0x2d, 0xec, 0x85, 0x1d, 0x33, 0x3b, 0x1b, 0xa3, 0x1d, 0x68, 0x51, 0x1e, 0x5d,
	0x00, 0x97, 0x6e, 0x04, 0x2e, 0x51, 0x1e, 0x19, 0x58, 0x0c, 0x1d, 0xa2, 0x14, 0x1b, 0xf3, 0x40,
	0x8a, 0x28, 0x30, 0x97, 0xc8, 0xd4, 0x6d, 0x19, 0xfc, 0xb3, 0x99, 0xcf, 0x69, 0xdf, 0x30, 0x65,
	0x02, 0x30, 0x3c, 0x78, 0x8d, 0x5c, 0x4d, 0xa0, 0x11, 0xac, 0x6a, 0x21, 0x83, 0x8c, 0x37, 0x15,
	0x71, 0x4c, 0x53, 0xd7, 0xb9, 0xa5, 0x24, 0x86, 0x25, 0x05, 0x5e, 0xd1, 0x42, 0x56, 0x43, 0xa4,
	0x60, 0xa3, 0x24, 0x2b, 0xbb, 0xae, 0x5c, 0x30, 0xca, 0x3f, 0x98, 0x59, 0x1b, 0xd7, 0x1c, 0x8d,
	0x51, 0xf8, 0x7b, 0x4a, 0xf5, 0xbe, 0xdb, 0x80, 0xaa, 0x35, 0x3c, 0x90, 0xfe, 0x8f, 0xc0, 0x7e,
	0xcf, 0x78, 0x94, 0xcb, 0x7e, 0x67, 0x66, 0xda, 0xe7, 0x8c, 0x47, 0xd8, 0x50, 0x5c, 0xb7, 0x52,
	0xf3, 0xde, 0xad, 0x64, 0xdf, 0x60, 0xa5, 0x85, 0x7a, 0x56, 0x5a, 0xac, 0x65, 0xa5, 0xa5, 0xdb,
	0x5a, 0xa9, 0x55, 0xdf, 0x4a, 0xaf, 0xc0, 0xa9, 0xe4, 0xe6, 0x18, 0xb9, 0xed, 0xdd, 0xba, 0x7f,
	0xb8, 0xe2, 0xea, 0x7d, 0xb3, 0x61, 0x63, 0x5f, 0xca, 0x98, 0x85, 0x44, 0x33, 0xc1, 0xe7, 0xb7,
	0xeb, 0x3f, 0x73, 0xbb, 0x5e, 0x91, 0x44, 0xeb, 0x0e, 0x25, 0xf1, 0xd5, 0x86, 0xce, 0x31, 0x49,
	0xa8, 0x92, 0x24, 0xa4, 0x73, 0x41, 0xcc, 0x05, 0xf1, 0xd9, 0x86, 0xe5, 0x63, 0x11, 0xcd, 0xb5,
	0x30, 0xd7, 0x42, 0xef, 0x8b, 0x0d, 0x6b, 0xc3, 0x78, 0xa2, 0xf4, 0x83, 0xfd, 0x12, 0x99, 0xcb,
	0xe1, 0xef, 0x95, 0xc3, 0xc1, 0xe1, 0xeb, 0xe1, 0x98, 0xe9, 0x6c, 0x5e, 0x28, 0x92, 0x4b, 0x4f,
	0x1d, 0x8f, 0x08, 0xf3, 0xb3, 0x7f, 0xf9, 0xf5, 0xde, 0x32, 0x46, 0x8b, 0x66, 0xf1, 0x8f, 0x7f,
	0x05, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x83, 0x4d, 0x54, 0x65, 0x11, 0x00, 0x00,
}
