// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alameda_api/v1alpha1/datahub/recommendations/types.proto

package recommendations

import (
	fmt "fmt"
	resources "github.com/containers-ai/api/alameda_api/v1alpha1/datahub/resources"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ControllerRecommendedType int32

const (
	ControllerRecommendedType_CRT_Undefined ControllerRecommendedType = 0
	ControllerRecommendedType_CRT_Primitive ControllerRecommendedType = 1
	ControllerRecommendedType_CRT_K8s       ControllerRecommendedType = 2
)

var ControllerRecommendedType_name = map[int32]string{
	0: "CRT_Undefined",
	1: "CRT_Primitive",
	2: "CRT_K8s",
}

var ControllerRecommendedType_value = map[string]int32{
	"CRT_Undefined": 0,
	"CRT_Primitive": 1,
	"CRT_K8s":       2,
}

func (x ControllerRecommendedType) String() string {
	return proto.EnumName(ControllerRecommendedType_name, int32(x))
}

func (ControllerRecommendedType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b37098e336d1ed15, []int{0}
}

type ControllerRecommendedSpec struct {
	ObjectMeta           *resources.ObjectMeta `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Kind                 resources.Kind        `protobuf:"varint,2,opt,name=kind,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.Kind" json:"kind,omitempty"`
	CurrentReplicas      int32                 `protobuf:"varint,3,opt,name=current_replicas,json=currentReplicas,proto3" json:"current_replicas,omitempty"`
	DesiredReplicas      int32                 `protobuf:"varint,4,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	Time                 *timestamp.Timestamp  `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	CreateTime           *timestamp.Timestamp  `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	CurrentCpuRequests   float64               `protobuf:"fixed64,7,opt,name=current_cpu_requests,json=currentCpuRequests,proto3" json:"current_cpu_requests,omitempty"`
	CurrentMemRequests   float64               `protobuf:"fixed64,8,opt,name=current_mem_requests,json=currentMemRequests,proto3" json:"current_mem_requests,omitempty"`
	CurrentCpuLimits     float64               `protobuf:"fixed64,9,opt,name=current_cpu_limits,json=currentCpuLimits,proto3" json:"current_cpu_limits,omitempty"`
	CurrentMemLimits     float64               `protobuf:"fixed64,10,opt,name=current_mem_limits,json=currentMemLimits,proto3" json:"current_mem_limits,omitempty"`
	DesiredCpuLimits     float64               `protobuf:"fixed64,11,opt,name=desired_cpu_limits,json=desiredCpuLimits,proto3" json:"desired_cpu_limits,omitempty"`
	DesiredMemLimits     float64               `protobuf:"fixed64,12,opt,name=desired_mem_limits,json=desiredMemLimits,proto3" json:"desired_mem_limits,omitempty"`
	TotalCost            float64               `protobuf:"fixed64,13,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ControllerRecommendedSpec) Reset()         { *m = ControllerRecommendedSpec{} }
func (m *ControllerRecommendedSpec) String() string { return proto.CompactTextString(m) }
func (*ControllerRecommendedSpec) ProtoMessage()    {}
func (*ControllerRecommendedSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_b37098e336d1ed15, []int{0}
}

func (m *ControllerRecommendedSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerRecommendedSpec.Unmarshal(m, b)
}
func (m *ControllerRecommendedSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerRecommendedSpec.Marshal(b, m, deterministic)
}
func (m *ControllerRecommendedSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerRecommendedSpec.Merge(m, src)
}
func (m *ControllerRecommendedSpec) XXX_Size() int {
	return xxx_messageInfo_ControllerRecommendedSpec.Size(m)
}
func (m *ControllerRecommendedSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerRecommendedSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerRecommendedSpec proto.InternalMessageInfo

func (m *ControllerRecommendedSpec) GetObjectMeta() *resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *ControllerRecommendedSpec) GetKind() resources.Kind {
	if m != nil {
		return m.Kind
	}
	return resources.Kind_POD
}

func (m *ControllerRecommendedSpec) GetCurrentReplicas() int32 {
	if m != nil {
		return m.CurrentReplicas
	}
	return 0
}

func (m *ControllerRecommendedSpec) GetDesiredReplicas() int32 {
	if m != nil {
		return m.DesiredReplicas
	}
	return 0
}

func (m *ControllerRecommendedSpec) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *ControllerRecommendedSpec) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *ControllerRecommendedSpec) GetCurrentCpuRequests() float64 {
	if m != nil {
		return m.CurrentCpuRequests
	}
	return 0
}

func (m *ControllerRecommendedSpec) GetCurrentMemRequests() float64 {
	if m != nil {
		return m.CurrentMemRequests
	}
	return 0
}

func (m *ControllerRecommendedSpec) GetCurrentCpuLimits() float64 {
	if m != nil {
		return m.CurrentCpuLimits
	}
	return 0
}

func (m *ControllerRecommendedSpec) GetCurrentMemLimits() float64 {
	if m != nil {
		return m.CurrentMemLimits
	}
	return 0
}

func (m *ControllerRecommendedSpec) GetDesiredCpuLimits() float64 {
	if m != nil {
		return m.DesiredCpuLimits
	}
	return 0
}

func (m *ControllerRecommendedSpec) GetDesiredMemLimits() float64 {
	if m != nil {
		return m.DesiredMemLimits
	}
	return 0
}

func (m *ControllerRecommendedSpec) GetTotalCost() float64 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

type ControllerRecommendedSpecK8S struct {
	ObjectMeta           *resources.ObjectMeta `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Kind                 resources.Kind        `protobuf:"varint,2,opt,name=kind,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.Kind" json:"kind,omitempty"`
	CurrentReplicas      int32                 `protobuf:"varint,3,opt,name=current_replicas,json=currentReplicas,proto3" json:"current_replicas,omitempty"`
	DesiredReplicas      int32                 `protobuf:"varint,4,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	Time                 *timestamp.Timestamp  `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	CreateTime           *timestamp.Timestamp  `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ControllerRecommendedSpecK8S) Reset()         { *m = ControllerRecommendedSpecK8S{} }
func (m *ControllerRecommendedSpecK8S) String() string { return proto.CompactTextString(m) }
func (*ControllerRecommendedSpecK8S) ProtoMessage()    {}
func (*ControllerRecommendedSpecK8S) Descriptor() ([]byte, []int) {
	return fileDescriptor_b37098e336d1ed15, []int{1}
}

func (m *ControllerRecommendedSpecK8S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerRecommendedSpecK8S.Unmarshal(m, b)
}
func (m *ControllerRecommendedSpecK8S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerRecommendedSpecK8S.Marshal(b, m, deterministic)
}
func (m *ControllerRecommendedSpecK8S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerRecommendedSpecK8S.Merge(m, src)
}
func (m *ControllerRecommendedSpecK8S) XXX_Size() int {
	return xxx_messageInfo_ControllerRecommendedSpecK8S.Size(m)
}
func (m *ControllerRecommendedSpecK8S) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerRecommendedSpecK8S.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerRecommendedSpecK8S proto.InternalMessageInfo

func (m *ControllerRecommendedSpecK8S) GetObjectMeta() *resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *ControllerRecommendedSpecK8S) GetKind() resources.Kind {
	if m != nil {
		return m.Kind
	}
	return resources.Kind_POD
}

func (m *ControllerRecommendedSpecK8S) GetCurrentReplicas() int32 {
	if m != nil {
		return m.CurrentReplicas
	}
	return 0
}

func (m *ControllerRecommendedSpecK8S) GetDesiredReplicas() int32 {
	if m != nil {
		return m.DesiredReplicas
	}
	return 0
}

func (m *ControllerRecommendedSpecK8S) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *ControllerRecommendedSpecK8S) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func init() {
	proto.RegisterEnum("containersai.alameda.v1alpha1.datahub.recommendations.ControllerRecommendedType", ControllerRecommendedType_name, ControllerRecommendedType_value)
	proto.RegisterType((*ControllerRecommendedSpec)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ControllerRecommendedSpec")
	proto.RegisterType((*ControllerRecommendedSpecK8S)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ControllerRecommendedSpecK8s")
}

func init() {
	proto.RegisterFile("alameda_api/v1alpha1/datahub/recommendations/types.proto", fileDescriptor_b37098e336d1ed15)
}

var fileDescriptor_b37098e336d1ed15 = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xc9, 0xd6, 0x6e, 0xcc, 0x65, 0x50, 0x22, 0x0e, 0xa1, 0x02, 0x51, 0xed, 0x54, 0x10,
	0x38, 0x6c, 0xa8, 0x52, 0xa5, 0xdd, 0xe8, 0x69, 0x2a, 0x05, 0x14, 0xca, 0x05, 0x21, 0x45, 0xae,
	0xf3, 0xd6, 0x19, 0xe2, 0x38, 0xd8, 0x2f, 0x93, 0xf6, 0x15, 0xf8, 0x58, 0x7c, 0x32, 0x64, 0xc7,
	0x69, 0x5a, 0xa4, 0x69, 0xec, 0xc2, 0x89, 0x5b, 0xfb, 0xf7, 0xef, 0xfd, 0x9e, 0xfd, 0x62, 0x99,
	0x4c, 0x58, 0xce, 0x24, 0x64, 0x2c, 0x65, 0xa5, 0x88, 0x2f, 0x8f, 0x59, 0x5e, 0x5e, 0xb0, 0xe3,
	0x38, 0x63, 0xc8, 0x2e, 0xaa, 0x65, 0xac, 0x81, 0x2b, 0x29, 0xa1, 0xc8, 0x18, 0x0a, 0x55, 0x98,
	0x18, 0xaf, 0x4a, 0x30, 0xb4, 0xd4, 0x0a, 0x55, 0x38, 0xe6, 0xaa, 0x40, 0x26, 0x0a, 0xd0, 0x86,
	0x09, 0xea, 0x35, 0xb4, 0x51, 0x50, 0xaf, 0xa0, 0x7f, 0x28, 0x06, 0xe3, 0x1b, 0x1a, 0x1a, 0x55,
	0x69, 0x0e, 0x26, 0x96, 0x80, 0xcc, 0xa6, 0x75, 0xb7, 0xc1, 0xb3, 0x95, 0x52, 0xab, 0x1c, 0x62,
	0xf7, 0x6f, 0x59, 0x9d, 0xc7, 0x28, 0x24, 0x18, 0x64, 0xb2, 0xac, 0x81, 0xa3, 0x5f, 0x5d, 0xf2,
	0x78, 0xaa, 0x0a, 0xd4, 0x2a, 0xcf, 0x41, 0x27, 0x4d, 0x57, 0xc8, 0x3e, 0x95, 0xc0, 0xc3, 0xaf,
	0xa4, 0xa7, 0x96, 0xdf, 0x80, 0x63, 0x6a, 0xbd, 0x51, 0x30, 0x0c, 0x46, 0xbd, 0x93, 0x53, 0xfa,
	0xb7, 0x47, 0xf0, 0x9b, 0xa2, 0x1f, 0x9c, 0x63, 0x0e, 0xc8, 0x12, 0xa2, 0xd6, 0xbf, 0xc3, 0x33,
	0xd2, 0xf9, 0x2e, 0x8a, 0x2c, 0xda, 0x19, 0x06, 0xa3, 0xfb, 0x27, 0xe3, 0x5b, 0x6b, 0x67, 0xa2,
	0xc8, 0x12, 0xa7, 0x08, 0x9f, 0x93, 0x3e, 0xaf, 0xb4, 0x86, 0x02, 0x53, 0x0d, 0x65, 0x2e, 0x38,
	0x33, 0xd1, 0xee, 0x30, 0x18, 0x75, 0x93, 0x07, 0x3e, 0x4f, 0x7c, 0x6c, 0xd1, 0x0c, 0x8c, 0xd0,
	0x90, 0xb5, 0x68, 0xa7, 0x46, 0x7d, 0xbe, 0x46, 0x29, 0xe9, 0xd8, 0x79, 0x45, 0x5d, 0x77, 0xee,
	0x01, 0xad, 0x87, 0x49, 0x9b, 0x61, 0xd2, 0x45, 0x33, 0xcc, 0xc4, 0x71, 0xe1, 0x29, 0xe9, 0x71,
	0x0d, 0x0c, 0x21, 0x75, 0x65, 0x7b, 0x37, 0x96, 0x91, 0x1a, 0xb7, 0x41, 0xf8, 0x9a, 0x3c, 0x6a,
	0x8e, 0xc0, 0xcb, 0x2a, 0xd5, 0xf0, 0xa3, 0x02, 0x83, 0x26, 0xda, 0x1f, 0x06, 0xa3, 0x20, 0x09,
	0xfd, 0xda, 0xb4, 0xac, 0x12, 0xbf, 0xb2, 0x59, 0x21, 0x41, 0xb6, 0x15, 0x77, 0xb7, 0x2a, 0xe6,
	0x20, 0xd7, 0x15, 0x2f, 0x49, 0xb8, 0xd9, 0x23, 0x17, 0x52, 0xa0, 0x89, 0x0e, 0x1c, 0xdf, 0x6f,
	0x3b, 0xbc, 0x73, 0xf9, 0x26, 0x6d, 0xfd, 0x9e, 0x26, 0x5b, 0xf4, 0x1c, 0x64, 0x4b, 0x37, 0x73,
	0xdd, 0x70, 0xf7, 0x6a, 0xda, 0xaf, 0x6c, 0xb9, 0x1b, 0x7a, 0xc3, 0x7d, 0x6f, 0x8b, 0x6e, 0xdd,
	0x4f, 0x09, 0x41, 0x85, 0x2c, 0x4f, 0xb9, 0x32, 0x18, 0x1d, 0x3a, 0xea, 0xc0, 0x25, 0x53, 0x65,
	0xf0, 0xe8, 0xe7, 0x2e, 0x79, 0x72, 0xed, 0x25, 0x9e, 0x4d, 0xcc, 0xff, 0x7b, 0xfc, 0xef, 0xee,
	0xf1, 0x8b, 0xf7, 0xd7, 0x3c, 0x28, 0x8b, 0xab, 0x12, 0xc2, 0x87, 0xe4, 0x70, 0x9a, 0x2c, 0xd2,
	0xcf, 0x45, 0x06, 0xe7, 0xa2, 0x80, 0xac, 0x7f, 0xa7, 0x89, 0x3e, 0x6a, 0xfb, 0xa9, 0xc5, 0x25,
	0xf4, 0x83, 0xb0, 0x47, 0xf6, 0x6d, 0x34, 0x9b, 0x98, 0xfe, 0xce, 0xdb, 0xd9, 0x97, 0xb3, 0x95,
	0x40, 0x3b, 0x31, 0xae, 0x64, 0xdc, 0xce, 0xf6, 0x15, 0x13, 0xb1, 0x7d, 0x0c, 0x6f, 0xf3, 0x12,
	0x2f, 0xf7, 0xdc, 0xe6, 0xdf, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x4e, 0xcc, 0x74, 0xc0,
	0x05, 0x00, 0x00,
}
