// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datahub/resource/v1alpha2/resource.proto

package containersai_datahub_resource_v1alpha2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import v1alpha2 "datahub/metric/v1alpha2"
import v1alpha22 "datahub/prediction/v1alpha2"
import v1alpha21 "datahub/resource/metadata/v1alpha2"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Represents a container and its containing limit and requeset configurations
//
type Container struct {
	Name                 string                          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LimitResource        map[string]*v1alpha2.MetricData `protobuf:"bytes,2,rep,name=limit_resource,json=limitResource,proto3" json:"limit_resource,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RequestResource      map[string]*v1alpha2.MetricData `protobuf:"bytes,3,rep,name=request_resource,json=requestResource,proto3" json:"request_resource,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_9b5d9292dd139eff, []int{0}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (dst *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(dst, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Container) GetLimitResource() map[string]*v1alpha2.MetricData {
	if m != nil {
		return m.LimitResource
	}
	return nil
}

func (m *Container) GetRequestResource() map[string]*v1alpha2.MetricData {
	if m != nil {
		return m.RequestResource
	}
	return nil
}

// *
// Represents a Kubernetes pod
//
type Pod struct {
	NamespacedName       *v1alpha21.NamespacedName      `protobuf:"bytes,1,opt,name=namespaced_name,json=namespacedName,proto3" json:"namespaced_name,omitempty"`
	ResourceLink         string                         `protobuf:"bytes,2,opt,name=resource_link,json=resourceLink,proto3" json:"resource_link,omitempty"`
	Containers           []*Container                   `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	Predict              bool                           `protobuf:"varint,4,opt,name=predict,proto3" json:"predict,omitempty"`
	Scaler               *v1alpha21.NamespacedName      `protobuf:"bytes,5,opt,name=scaler,proto3" json:"scaler,omitempty"`
	NodeName             string                         `protobuf:"bytes,6,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	StartTime            *timestamp.Timestamp           `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Policy               v1alpha22.RecommendationPolicy `protobuf:"varint,8,opt,name=policy,proto3,enum=containersai.datahub.prediction.v1alpha2.RecommendationPolicy" json:"policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Pod) Reset()         { *m = Pod{} }
func (m *Pod) String() string { return proto.CompactTextString(m) }
func (*Pod) ProtoMessage()    {}
func (*Pod) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_9b5d9292dd139eff, []int{1}
}
func (m *Pod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pod.Unmarshal(m, b)
}
func (m *Pod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pod.Marshal(b, m, deterministic)
}
func (dst *Pod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pod.Merge(dst, src)
}
func (m *Pod) XXX_Size() int {
	return xxx_messageInfo_Pod.Size(m)
}
func (m *Pod) XXX_DiscardUnknown() {
	xxx_messageInfo_Pod.DiscardUnknown(m)
}

var xxx_messageInfo_Pod proto.InternalMessageInfo

func (m *Pod) GetNamespacedName() *v1alpha21.NamespacedName {
	if m != nil {
		return m.NamespacedName
	}
	return nil
}

func (m *Pod) GetResourceLink() string {
	if m != nil {
		return m.ResourceLink
	}
	return ""
}

func (m *Pod) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Pod) GetPredict() bool {
	if m != nil {
		return m.Predict
	}
	return false
}

func (m *Pod) GetScaler() *v1alpha21.NamespacedName {
	if m != nil {
		return m.Scaler
	}
	return nil
}

func (m *Pod) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *Pod) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Pod) GetPolicy() v1alpha22.RecommendationPolicy {
	if m != nil {
		return m.Policy
	}
	return v1alpha22.RecommendationPolicy_RECOMMENDATIONPOLICY_UNDEFINED
}

// *
// Represents a Kubernetes node
//
type Node struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_9b5d9292dd139eff, []int{2}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Container)(nil), "containersai.datahub.resource.v1alpha2.Container")
	proto.RegisterMapType((map[string]*v1alpha2.MetricData)(nil), "containersai.datahub.resource.v1alpha2.Container.LimitResourceEntry")
	proto.RegisterMapType((map[string]*v1alpha2.MetricData)(nil), "containersai.datahub.resource.v1alpha2.Container.RequestResourceEntry")
	proto.RegisterType((*Pod)(nil), "containersai.datahub.resource.v1alpha2.Pod")
	proto.RegisterType((*Node)(nil), "containersai.datahub.resource.v1alpha2.Node")
}

func init() {
	proto.RegisterFile("datahub/resource/v1alpha2/resource.proto", fileDescriptor_resource_9b5d9292dd139eff)
}

var fileDescriptor_resource_9b5d9292dd139eff = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0xeb, 0x34, 0x8d, 0x27, 0x34, 0xad, 0x56, 0x1c, 0x2c, 0x73, 0x20, 0x0a, 0x08, 0xf9,
	0x80, 0x1c, 0x62, 0x2e, 0xc0, 0x01, 0x0e, 0x94, 0x9e, 0x4a, 0x55, 0x56, 0x08, 0x8e, 0xd1, 0xc6,
	0x5e, 0x9a, 0x55, 0xec, 0x5d, 0x77, 0xbd, 0xae, 0x94, 0x5f, 0xe0, 0x4f, 0xf9, 0x0b, 0xb4, 0xeb,
	0x5d, 0x27, 0x51, 0x23, 0x41, 0x24, 0xb8, 0xed, 0x3c, 0xcd, 0xbc, 0xf7, 0x66, 0xc6, 0x63, 0x88,
	0x73, 0xa2, 0xc8, 0xb2, 0x59, 0x4c, 0x25, 0xad, 0x45, 0x23, 0x33, 0x3a, 0xbd, 0x9f, 0x91, 0xa2,
	0x5a, 0x92, 0xb4, 0x43, 0x92, 0x4a, 0x0a, 0x25, 0xd0, 0x8b, 0x4c, 0x70, 0x45, 0x18, 0xa7, 0xb2,
	0x26, 0x2c, 0xb1, 0x65, 0x49, 0x97, 0xe4, 0xca, 0xa2, 0xd9, 0x03, 0xc6, 0x92, 0x2a, 0xa2, 0xc1,
	0x0d, 0xb5, 0x43, 0x5a, 0xea, 0xe8, 0xa5, 0x2b, 0xa9, 0x24, 0xcd, 0x59, 0xa6, 0x98, 0xe0, 0x9b,
	0xdc, 0x0d, 0x66, 0xb3, 0x9f, 0xde, 0x0a, 0x71, 0x5b, 0xd0, 0xa9, 0x89, 0x16, 0xcd, 0x8f, 0xa9,
	0x62, 0x25, 0xad, 0x15, 0x29, 0x2b, 0x9b, 0xf0, 0xdc, 0xd1, 0x95, 0x54, 0x49, 0x96, 0xed, 0xc8,
	0x4a, 0x96, 0xb5, 0x59, 0x93, 0x5f, 0x3e, 0x04, 0x1f, 0x5d, 0x4b, 0x08, 0x41, 0x8f, 0x93, 0x92,
	0x86, 0xde, 0xd8, 0x8b, 0x03, 0x6c, 0xde, 0x68, 0x05, 0xa3, 0x82, 0x95, 0x4c, 0xcd, 0x5d, 0x27,
	0xe1, 0xd1, 0xd8, 0x8f, 0x87, 0xe9, 0x45, 0xf2, 0x77, 0xa3, 0x48, 0x3a, 0xfa, 0xe4, 0x4a, 0xf3,
	0x60, 0x9b, 0xf0, 0x89, 0x2b, 0xb9, 0xc6, 0xa7, 0xc5, 0x36, 0x86, 0xee, 0xe0, 0x5c, 0xd2, 0xbb,
	0x86, 0xd6, 0x5b, 0x72, 0xbe, 0x91, 0xbb, 0x3c, 0x5c, 0x0e, 0xb7, 0x4c, 0xbb, 0x82, 0x67, 0x72,
	0x17, 0x8d, 0x24, 0xa0, 0x87, 0xbe, 0xd0, 0x39, 0xf8, 0x2b, 0xba, 0xb6, 0x83, 0xd0, 0x4f, 0x74,
	0x09, 0xc7, 0xf7, 0xa4, 0x68, 0x74, 0xfb, 0x5e, 0x3c, 0x4c, 0x5f, 0xed, 0xf7, 0x63, 0x87, 0xdb,
	0xb9, 0xf9, 0x6c, 0xe2, 0x0b, 0xa2, 0x08, 0x6e, 0xcb, 0xdf, 0x1d, 0xbd, 0xf1, 0x22, 0x05, 0x8f,
	0xf7, 0x99, 0xfb, 0xbf, 0xaa, 0x93, 0x9f, 0x3d, 0xf0, 0x6f, 0x44, 0x8e, 0x96, 0x70, 0xa6, 0x37,
	0x5b, 0x57, 0x24, 0xa3, 0xf9, 0xbc, 0x5b, 0xf8, 0x30, 0xfd, 0xf0, 0x87, 0x19, 0x77, 0x1f, 0x6c,
	0x27, 0x74, 0xdd, 0xf1, 0xe8, 0x17, 0x1e, 0xf1, 0x9d, 0x18, 0x3d, 0x83, 0x53, 0x57, 0x3c, 0x2f,
	0x18, 0x5f, 0x99, 0x2e, 0x02, 0xfc, 0xc8, 0x81, 0x57, 0x8c, 0xaf, 0xd0, 0x17, 0x80, 0x8d, 0xac,
	0xdd, 0xf6, 0xec, 0xe0, 0x6d, 0xe3, 0x2d, 0x12, 0x14, 0xc2, 0x89, 0x3d, 0x98, 0xb0, 0x37, 0xf6,
	0xe2, 0x01, 0x76, 0x21, 0xfa, 0x0e, 0xfd, 0x3a, 0x23, 0x05, 0x95, 0xe1, 0xf1, 0xbf, 0x69, 0xd9,
	0xd2, 0xa1, 0x27, 0x10, 0x70, 0x91, 0xd3, 0x76, 0x9c, 0x7d, 0xd3, 0xe6, 0x40, 0x03, 0x66, 0x0e,
	0x6f, 0x01, 0x6a, 0x45, 0xa4, 0x9a, 0xeb, 0x23, 0x0d, 0x4f, 0x8c, 0x72, 0x94, 0xb4, 0x17, 0x9c,
	0xb8, 0x0b, 0x4e, 0xbe, 0xba, 0x0b, 0xc6, 0x81, 0xc9, 0xd6, 0x31, 0xfa, 0x06, 0xfd, 0x4a, 0x14,
	0x2c, 0x5b, 0x87, 0x83, 0xb1, 0x17, 0x8f, 0xd2, 0xf7, 0xfb, 0x0d, 0x6f, 0xfd, 0x1f, 0x3a, 0xa7,
	0x98, 0x66, 0xa2, 0x2c, 0x29, 0xcf, 0x89, 0xc6, 0x6f, 0x0c, 0x0b, 0xb6, 0x6c, 0x93, 0x08, 0x7a,
	0xd7, 0x22, 0xa7, 0xfb, 0x4e, 0x7e, 0xd1, 0x37, 0x96, 0x5e, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0x0e, 0x17, 0x39, 0x0e, 0x17, 0x05, 0x00, 0x00,
}
